package cardSets;
import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetGvG {

	public ArrayList<Card> gvgList() {
		ArrayList<Card> gvg = new ArrayList<Card>();
		gvg.add(new Minion("Clockwork Gnome", " Common", " Minion", " Mech", "  Any", 1, 2, 1));
		gvg.add(new Minion("Cogmaster", " Common", " Minion", " General", "  Any", 1, 1, 2));
		gvg.add(new Minion("Warbot", " Common", " Minion", " Mech", "  Warrior", 1, 1, 3));
		gvg.add(new Minion("Annoy-o-Tron", " Common", " Minion", " Mech", "  Any", 2, 1, 2));
		gvg.add(new Minion("Anodized Robo Cub", " Common", " Minion", " Mech", "  Druid", 2, 2, 2));
		gvg.add(new Spell("Crackle", " Common", " Spell", " ", "  Shaman", 2, " ", "  "));
		gvg.add(new Spell("Darkbomb", " Common", " Spell", " ", "  Warlock", 2, " ", "  "));
		gvg.add(new Minion("Explosive Sheep", " Common", " Minion", " Mech", "  Any", 2, 1, 1));
		gvg.add(new Spell("Flamecannon", " Common", " Spell", " ", "  Mage", 2, " ", "  "));
		gvg.add(new Minion("Gilblin Stalker", " Common", " Minion", " General", "  Any", 2, 2, 3));
		gvg.add(new Minion("Glaivezooka", " Common", " Weapon", " ", "  Hunter", 2, 2, 2));
		gvg.add(new Minion("Goblin Auto-Barber", " Common", " Minion", " Mech", "  Rogue", 2, 3, 2));
		gvg.add(new Minion("Mechwarper", " Common", " Minion", " Mech", "  Any", 2, 2, 3));
		gvg.add(new Minion("Micro Machine", " Common", " Minion", " Mech", "  Any", 2, 1, 2));
		gvg.add(new Minion("Puddlestomper", " Common", " Minion", " Murloc", "  Any", 2, 3, 2));
		gvg.add(new Spell("Seal of Light", " Common", " Spell", " ", "  Paladin", 2, " ", "  "));
		gvg.add(new Minion("Shielded Minibot", " Common", " Minion", " Mech", "  Paladin", 2, 2, 2));
		gvg.add(new Minion("Ship's Cannon", " Common", " Minion", " General", "  Any", 2, 2, 3));
		gvg.add(new Minion("Shrinkmeister", " Common", " Minion", " General", "  Priest", 2, 3, 2));
		gvg.add(new Minion("Snowchugger", " Common", " Minion", " Mech", "  Mage", 2, 2, 3));
		gvg.add(new Minion("Stonesplinter Trogg", " Common", " Minion", " General", "  Any", 2, 2, 3));
		gvg.add(new Minion("Whirling Zap-o-matic", " Common", " Minion", " Mech", "  Shaman", 2, 3, 2));
		gvg.add(new Minion("Flying Machine", " Common", " Minion", " Mech", "  Any", 3, 1, 4));
		gvg.add(new Minion("Gnomeregan Infantry", " Common", " Minion", " General", "  Any", 3, 1, 4));
		gvg.add(new Minion("Ogre Brute", " Common", " Minion", " General", "  Any", 3, 4, 4));
		gvg.add(new Minion("Ogre Warmaul", " Common", " Weapon", " ", "  Warrior", 3, 4, 2));
		gvg.add(new Minion("Spider Tank", " Common", " Minion", " Mech", "  Any", 3, 3, 4));
		gvg.add(new Minion("Tinkertown Technician", " Common", " Minion", " General", "  Any", 3, 3, 3));
		gvg.add(new Spell("Velen's Chosen", " Common", " Spell", " ", "  Priest", 3, " ", "  "));
		gvg.add(new Minion("Burly Rockjaw Trogg", " Common", " Minion", " General", "  Any", 4, 3, 5));
		gvg.add(new Minion("Lost Tallstrider", " Common", " Minion", " Beast", "  Any", 4, 5, 4));
		gvg.add(new Minion("Mechanical Yeti", " Common", " Minion", " Mech", "  Any", 4, 4, 5));
		gvg.add(new Minion("Piloted Shredder", " Common", " Minion", " Mech", "  Any", 4, 4, 3));
		gvg.add(new Spell("Tinker's Sharpsword Oil", " Common", " Spell", " ", "  Rogue", 4, " ", "  "));
		gvg.add(new Minion("Antique Healbot", " Common", " Minion", " Mech", "  Any", 5, 3, 3));
		gvg.add(new Spell("Cobra Shot", " Common", " Spell", " ", "  Hunter", 5, " ", "  "));
		gvg.add(new Minion("Druid of the Fang", " Common", " Minion", " General", "  Druid", 5, 4, 4));
		gvg.add(new Minion("Floating Watcher", " Common", " Minion", " Demon", "  Warlock", 5, 4, 4));
		gvg.add(new Minion("Salty Dog", " Common", " Minion", " Pirate", "  Any", 5, 7, 4));
		gvg.add(new Minion("Force-Tank MAX", " Common", " Minion", " Mech", "  Any", 8, 7, 7));
		gvg.add(new Minion("Target Dummy", " Rare", " Minion", " Mech", "  Any", 0, 0, 2));
		gvg.add(new Spell("Light of the Naaru", " Rare", " Spell", " ", "  Priest", 1, " ", "  "));
		gvg.add(new Spell("Call Pet", " Rare", " Spell", " ", "  Hunter", 2, " ", "  "));
		gvg.add(new Minion("One-eyed Cheat", " Rare", " Minion", " Pirate", "  Rogue", 2, 4, 1));
		gvg.add(new Minion("Queen of Pain", " Rare", " Minion", " Demon", "  Warlock", 2, 1, 4));
		gvg.add(new Minion("Shadowboxer", " Rare", " Minion", " Mech", "  Priest", 2, 2, 3));
		gvg.add(new Spell("Unstable Portal", " Rare", " Spell", " ", "  Mage", 2, " ", "  "));
		gvg.add(new Minion("Vitality Totem", " Rare", " Minion", " Totem", "  Shaman", 2, 0, 3));
		gvg.add(new Minion("Gnomish Experimenter", " Rare", " Minion", " General", "  Any", 3, 3, 2));
		gvg.add(new Minion("Goblin Sapper", " Rare", " Minion", " General", "  Any", 3, 2, 4));
		gvg.add(new Minion("Grove Tender", " Rare", " Minion", " General", "  Druid", 3, 2, 4));
		gvg.add(new Minion("Illuminator", " Rare", " Minion", " General", "  Any", 3, 2, 4));
		gvg.add(new Minion("Iron Sensei", " Rare", " Minion", " Mech", "  Rogue", 3, 2, 2));
		gvg.add(new Minion("Lil' Exorcist", " Rare", " Minion", " General", "  Any", 3, 2, 3));
		gvg.add(new Minion("Metaltooth Leaper", " Rare", " Minion", " Mech", "  Hunter", 3, 3, 3));
		gvg.add(new Spell("Muster for Battle", " Rare", " Spell", " ", "  Paladin", 3, " ", "  "));
		gvg.add(new Minion("Powermace", " Rare", " Weapon", " ", "  Shaman", 3, 3, 2));
		gvg.add(new Minion("Scarlet Purifier", " Rare", " Minion", " General", "  Paladin", 3, 4, 3));
		gvg.add(new Minion("Soot Spewer", " Rare", " Minion", " Mech", "  Mage", 3, 3, 3));
		gvg.add(new Minion("Arcane Nullifier X-21", " Rare", " Minion", " Mech", "  Any", 4, 2, 5));
		gvg.add(new Minion("Dunemaul Shaman", " Rare", " Minion", " General", "  Shaman", 4, 5, 4));
		gvg.add(new Minion("Fel Cannon", " Rare", " Minion", " Mech", "  Warlock", 4, 3, 5));
		gvg.add(new Minion("Goblin Blastmage", " Rare", " Minion", " General", "  Mage", 4, 5, 4));
		gvg.add(new Spell("Imp-losion", " Rare", " Spell", " ", "  Warlock", 4, " ", "  "));
		gvg.add(new Minion("Jeeves", " Rare", " Minion", " Mech", "  Any", 4, 1, 4));
		gvg.add(new Minion("Kezan Mystic", " Rare", " Minion", " General", "  Any", 4, 4, 3));
		gvg.add(new Minion("Screwjank Clunker", " Rare", " Minion", " Mech", "  Warrior", 4, 2, 5));
		gvg.add(new Minion("Bomb Lobber", " Rare", " Minion", " General", "  Any", 5, 3, 3));
		gvg.add(new Minion("Cobalt Guardian", " Rare", " Minion", " Mech", "  Paladin", 5, 6, 3));
		gvg.add(new Minion("King of Beasts", " Rare", " Minion", " Beast", "  Hunter", 5, 2, 6));
		gvg.add(new Minion("Madder Bomber", " Rare", " Minion", " General", "  Any", 5, 5, 4));
		gvg.add(new Minion("Ogre Ninja", " Rare", " Minion", " General", "  Rogue", 5, 6, 6));
		gvg.add(new Minion("Siege Engine", " Rare", " Minion", " Mech", "  Warrior", 5, 5, 5));
		gvg.add(new Minion("Upgraded Repair Bot", " Rare", " Minion", " Mech", "  Priest", 5, 5, 5));
		gvg.add(new Minion("Mech-Bear-Cat", " Rare", " Minion", " Mech", "  Druid", 6, 7, 6));
		gvg.add(new Spell("Recycle", " Rare", " Spell", " ", "  Druid", 6, " ", "  "));
		gvg.add(new Minion("Shieldmaiden", " Rare", " Minion", " General", "  Warrior", 6, 5, 5));
		gvg.add(new Minion("Shadowbomber", " Epic", " Minion", " General", "  Priest", 1, 2, 1));
		gvg.add(new Spell("Feign Death", " Epic", " Spell", " ", "  Hunter", 2, " ", "  "));
		gvg.add(new Minion("Recombobulator", " Epic", " Minion", " General", "  Any", 2, 3, 2));
		gvg.add(new Minion("Steamwheedle Sniper", " Epic", " Minion", " General", "  Hunter", 2, 2, 3));
		gvg.add(new Spell("Bouncing Blade", " Epic", " Spell", " ", "  Warrior", 3, " ", "  "));
		gvg.add(new Minion("Coghammer", " Epic", " Weapon", " ", "  Paladin", 3, 2, 3));
		gvg.add(new Minion("Cogmaster's Wrench", " Epic", " Weapon", " ", "  Rogue", 3, 1, 3));
		gvg.add(new Minion("Hobgoblin", " Epic", " Minion", " General", "  Any", 3, 2, 3));
		gvg.add(new Spell("Ancestor's Call", " Epic", " Spell", " ", "  Shaman", 4, " ", "  "));
		gvg.add(new Spell("Echo of Medivh", " Epic", " Spell", " ", "  Mage", 4, " ", "  "));
		gvg.add(new Minion("Enhance-o Mechano", " Epic", " Minion", " Mech", "  Any", 4, 3, 2));
		gvg.add(new Minion("Mini-Mage", " Epic", " Minion", " General", "  Any", 4, 4, 1));
		gvg.add(new Spell("Sabotage", " Epic", " Spell", " ", "  Rogue", 4, " ", "  "));
		gvg.add(new Minion("Siltfin Spiritwalker", " Epic", " Minion", " Murloc", "  Shaman", 4, 2, 5));
		gvg.add(new Minion("Wee Spellstopper", " Epic", " Minion", " General", "  Mage", 4, 2, 5));
		gvg.add(new Spell("Demonheart", " Epic", " Spell", " ", "  Warlock", 5, " ", "  "));
		gvg.add(new Minion("Fel Reaver", " Epic", " Minion", " Mech", "  Any", 5, 8, 8));
		gvg.add(new Minion("Junkbot", " Epic", " Minion", " Mech", "  Any", 5, 1, 5));
		gvg.add(new Minion("Quartermaster", " Epic", " Minion", " General", "  Paladin", 5, 2, 5));
		gvg.add(new Minion("Anima Golem", " Epic", " Minion", " Mech", "  Warlock", 6, 9, 9));
		gvg.add(new Spell("Dark Wispers", " Epic", " Spell", " ", "  Druid", 6, " ", "  "));
		gvg.add(new Spell("Lightbomb", " Epic", " Spell", " ", "  Priest", 6, " ", "  "));
		gvg.add(new Minion("Piloted Sky Golem", " Epic", " Minion", " Mech", "  Any", 6, 6, 4));
		gvg.add(new Spell("Crush", " Epic", " Spell", " ", "  Warrior", 7, " ", "  "));
		gvg.add(new Spell("Tree of Life", " Epic", " Spell", " ", "  Druid", 9, " ", "  "));
		gvg.add(new Minion("Clockwork Giant", " Epic", " Minion", " Mech", "  Any", 12, 8, 8));
		gvg.add(new Minion("Blingtron 3000", " Legendary", " Minion", " Mech", "  Any", 5, 3, 4));
		gvg.add(new Minion("Bolvar Fordragon", " Legendary", " Minion", " General", "  Paladin", 5, 1, 7));
		gvg.add(new Minion("Hemet Nesingwary", " Legendary", " Minion", " General", "  Any", 5, 6, 3));
		gvg.add(new Minion("Mimiron's Head", " Legendary", " Minion", " Mech", "  Any", 5, 4, 5));
		gvg.add(new Minion("Vol'jin", " Legendary", " Minion", " General", "  Priest", 5, 6, 2));
		gvg.add(new Minion("Gazlowe", " Legendary", " Minion", " General", "  Any", 6, 3, 6));
		gvg.add(new Minion("Iron Juggernaut", " Legendary", " Minion", " Mech", "  Warrior", 6, 6, 5));
		gvg.add(new Minion("Mogor the Ogre", " Legendary", " Minion", " General", "  Any", 6, 7, 6));
		gvg.add(new Minion("Toshley", " Legendary", " Minion", " General", "  Any", 6, 5, 7));
		gvg.add(new Minion("Trade Prince Gallywix", " Legendary", " Minion", " General", "  Rogue", 6, 5, 8));
		gvg.add(new Minion("Dr. Boom", " Legendary", " Minion", " General", "  Any", 7, 7, 7));
		gvg.add(new Minion("Flame Leviathan", " Legendary", " Minion", " Mech", "  Mage", 7, 7, 7));
		gvg.add(new Minion("Gahz'rilla", " Legendary", " Minion", " Beast", "  Hunter", 7, 6, 9));
		gvg.add(new Minion("Malorne", " Legendary", " Minion", " Beast", "  Druid", 7, 9, 7));
		gvg.add(new Minion("Neptulon", " Legendary", " Minion", " Elemental", "  Shaman", 7, 7, 7));
		gvg.add(new Minion("Troggzor the Earthinator", " Legendary", " Minion", " General", "  Any", 7, 6, 6));
		gvg.add(new Minion("Foe Reaper 4000", " Legendary", " Minion", " Mech", "  Any", 8, 6, 9));
		gvg.add(new Minion("Sneed's Old Shredder", " Legendary", " Minion", " Mech", "  Any", 8, 5, 7));
		gvg.add(new Minion("Mal'Ganis", " Legendary", " Minion", " Demon", "  Warlock", 9, 9, 7));
		gvg.add(new Minion("Mekgineer Thermaplugg", " Legendary", " Minion", " Mech", "  Any", 9, 9, 7));

		return gvg;
	}

	public static void main(String[] args) {

	}
}