package cardSets;
import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetJTU {

	public ArrayList<Card> JTUList() {
		ArrayList<Card> JTU = new ArrayList<Card>();
		
		JTU.add(new Spell("Adaptation"," Common"," Spell"," ","  Paladin",1," ","  "));
		JTU.add(new Minion("Air Elemental"," Common"," Minion"," Elemental","  Shaman", 1 , 2 , 1    ));
		JTU.add(new Minion("Arcanologist"," Common"," Minion"," General","  Mage", 2 , 2 , 3    ));
		JTU.add(new Spell("Awaken the Makers"," Legendary"," Spell"," ","  Priest",1," ","  "));
		JTU.add(new Spell("Binding Heal"," Common"," Spell"," ","  Priest",1," ","  "));
		JTU.add(new Minion("Biteweed"," Epic"," Minion"," General","  Rogue", 2 , 1 , 1    ));
		JTU.add(new Minion("Bittertide Hydra"," Epic"," Minion"," Beast","  Any", 5 , 8 , 8    ));
		JTU.add(new Minion("Blazecaller"," Epic"," Minion"," Elemental","  Any", 7 , 6 , 6    ));
		JTU.add(new Spell("Bloodbloom"," Epic"," Spell"," ","  Warlock",2," ","  "));
		JTU.add(new Minion("Bright-Eyed Scout"," Epic"," Minion"," General","  Any", 4 , 3 , 4    ));
		JTU.add(new Minion("Charged Devilsaur"," Epic"," Minion"," Beast","  Any", 8 , 7 , 7    ));
		JTU.add(new Minion("Chittering Tunneler"," Epic"," Minion"," Beast","  Warlock", 3 , 3 , 3    ));
		JTU.add(new Minion("Clutchmother Zavas"," Legendary"," Minion"," Beast","  Warlock", 2 , 2 , 2    ));
		JTU.add(new Minion("Cornered Sentry"," Rare"," Minion"," General","  Warrior", 2 , 2 , 6    ));
		JTU.add(new Spell("Corrupting Mist"," Rare"," Spell"," ","  Warlock",2," ","  "));
		JTU.add(new Minion("Crackling Razormaw"," Common"," Minion"," Beast","  Hunter", 2 , 3 , 2    ));
		JTU.add(new Minion("Cruel Dinomancer"," Rare"," Minion"," General","  Warlock", 6 , 5 , 5    ));
		JTU.add(new Minion("Crystalline Oracle"," Rare"," Minion"," Elemental","  Priest", 1 , 1 , 1    ));
		JTU.add(new Minion("Curious Glimmerroot"," Epic"," Minion"," General","  Priest", 3 , 3 , 3    ));
		JTU.add(new Minion("Devilsaur Egg"," Rare"," Minion"," General","  Any", 3 , 0 , 3    ));
		JTU.add(new Spell("Dinomancy"," Epic"," Spell"," ","  Hunter",2," ","  "));
		JTU.add(new Spell("Dinosize"," Epic"," Spell"," ","  Paladin",8," ","  "));
		JTU.add(new Minion("Direhorn Hatchling"," Rare"," Minion"," Beast","  Warrior", 5 , 3 , 6    ));
		JTU.add(new Spell("Earthen Scales"," Rare"," Spell"," ","  Druid",1," ","  "));
		JTU.add(new Minion("Eggnapper"," Common"," Minion"," General","  Any", 3 , 3 , 1    ));
		JTU.add(new Minion("Elder Longneck"," Common"," Minion"," Beast","  Druid", 3 , 5 , 1    ));
		JTU.add(new Minion("Elise the Trailblazer"," Legendary"," Minion"," General","  Any", 5 , 5 , 5    ));
		JTU.add(new Minion("Emerald Hive Queen"," Epic"," Minion"," Beast","  Any", 1 , 2 , 3    ));
		JTU.add(new Minion("Emerald Reaver"," Common"," Minion"," Beast","  Any", 1 , 2 , 1    ));
		JTU.add(new Spell("Envenom Weapon"," Rare"," Spell"," ","  Rogue",3," ","  "));
		JTU.add(new Spell("Evolving Spores"," Rare"," Spell"," ","  Druid",4," ","  "));
		JTU.add(new Spell("Explore Un'Goro"," Epic"," Spell"," ","  Warrior",2," ","  "));
		JTU.add(new Spell("Feeding Time"," Rare"," Spell"," ","  Warlock",5," ","  "));
		JTU.add(new Minion("Fire Fly"," Common"," Minion"," Elemental","  Any", 1 , 1 , 2    ));
		JTU.add(new Minion("Fire Plume Harbinger"," Rare"," Minion"," Elemental","  Shaman", 2 , 1 , 1    ));
		JTU.add(new Minion("Fire Plume Phoenix"," Common"," Minion"," Elemental","  Any", 4 , 3 , 3    ));
		JTU.add(new Spell("Fire Plume's Heart"," Legendary"," Spell"," ","  Warrior",1," ","  "));
 		JTU.add(new Spell("Flame Geyser"," Common"," Spell"," ","  Mage",2," ","  "));
		JTU.add(new Spell("Free From Amber"," Rare"," Spell"," ","  Priest",8," ","  "));
 		JTU.add(new Minion("Frozen Crusher"," Rare"," Minion"," Elemental","  Any", 6 , 8 , 8    ));
		JTU.add(new Minion("Gentle Megasaur"," Epic"," Minion"," Beast","  Any", 4 , 5 , 4    ));
		JTU.add(new Minion("Giant Anaconda"," Epic"," Minion"," Beast","  Druid", 7 , 5 , 3    ));
		JTU.add(new Minion("Giant Mastodon"," Common"," Minion"," Beast","  Any", 9 , 6 , 10    ));
		JTU.add(new Minion("Giant Wasp"," Common"," Minion"," Beast","  Any", 3 , 2 , 2    ));
		JTU.add(new Minion("Glacial Shard"," Common"," Minion"," Elemental","  Any", 1 , 2 , 1    ));
		JTU.add(new Minion("Gluttonous Ooze"," Epic"," Minion"," General","  Any", 3 , 3 , 3    ));
		JTU.add(new Minion("Golakka Crawler"," Rare"," Minion"," Beast","  Any", 2 , 2 , 3    ));
		JTU.add(new Spell("Grievous Bite"," Common"," Spell"," ","  Hunter",2," ","  "));
		JTU.add(new Spell("Hallucination"," Common"," Spell"," ","  Rogue",1," ","  "));
		JTU.add(new Minion("Hemet, Jungle Hunter"," Legendary"," Minion"," General","  Any", 6 , 6 , 6    ));
		JTU.add(new Minion("Hot Spring Guardian"," Common"," Minion"," Elemental","  Shaman", 3 , 2 , 4    ));
		JTU.add(new Minion("Humongous Razorleaf"," Rare"," Minion"," General","  Any", 3 , 4 , 8    ));
		JTU.add(new Minion("Hydrologist"," Common"," Minion"," Murloc","  Paladin", 2 , 2 , 2    ));
		JTU.add(new Minion("Igneous Elemental"," Common"," Minion"," Elemental","  Any", 3 , 2 , 3    ));
		JTU.add(new Spell("Iron Hide"," Common"," Spell"," ","  Warrior",1," ","  "));
		JTU.add(new Minion("Jeweled Macaw"," Common"," Minion"," Beast","  Hunter", 1 , 1 , 1    ));
		JTU.add(new Spell("Jungle Giants"," Legendary"," Spell"," ","  Druid",1," ","  "));
		JTU.add(new Minion("Kalimos, Primal Lord"," Legendary"," Minion"," Elemental","  Shaman", 8 , 7 , 7    ));
		JTU.add(new Minion("King Mosh"," Legendary"," Minion"," Beast","  Warrior", 9 , 9 , 7    ));
 		JTU.add(new Minion("Lakkari Felhound"," Common"," Minion"," Demon","  Warlock", 4 , 3 , 8    ));
		JTU.add(new Spell("Lakkari Sacrifice"," Legendary"," Spell"," ","  Warlock",1," ","  "));
		JTU.add(new Minion("Lightfused Stegodon"," Rare"," Minion"," Beast","  Paladin", 4 , 3 , 4    ));
		JTU.add(new Spell("Living Mana"," Epic"," Spell"," ","  Druid",5," ","  "));
		JTU.add(new Spell("Lost in the Jungle"," Common"," Spell"," ","  Paladin",1," ","  "));
		JTU.add(new Minion("Lyra the Sunshard"," Legendary"," Minion"," Elemental","  Priest", 5 , 3 , 5    ));
		JTU.add(new Spell("Mana Bind"," Rare"," Spell"," ","  Mage",3," ","  "));
		JTU.add(new Spell("Meteor"," Epic"," Spell"," ","  Mage",6," ","  "));
		JTU.add(new Spell("Mimic Pod"," Rare"," Spell"," ","  Rogue",3," ","  "));
		JTU.add(new Minion("Mirage Caller"," Rare"," Minion"," General","  Priest", 3 , 2 , 3    ));
		JTU.add(new Minion("Molten Blade"," Rare"," Weapon"," ","  Warrior", 1 , 1 , 1    ));
		JTU.add(new Spell("Molten Reflection"," Rare"," Spell"," ","  Mage",4," ","  "));
		JTU.add(new Minion("Nesting Roc"," Common"," Minion"," Beast","  Any", 5 , 4 , 7    ));
		JTU.add(new Minion("Obsidian Shard"," Rare"," Weapon"," ","  Rogue", 4 , 3 , 3    ));
		JTU.add(new Spell("Open the Waygate"," Legendary"," Spell"," ","  Mage",1," ","  "));
		JTU.add(new Minion("Ornery Direhorn"," Common"," Minion"," Beast","  Warrior", 6 , 5 , 5    ));
		JTU.add(new Minion("Ozruk"," Legendary"," Minion"," Elemental","  Any", 9 , 5 , 5    ));
		JTU.add(new Minion("Primalfin Champion"," Epic"," Minion"," Murloc","  Paladin", 2 , 1 , 2    ));
		JTU.add(new Minion("Primalfin Lookout"," Common"," Minion"," Murloc","  Any", 3 , 3 , 2    ));
		JTU.add(new Minion("Primalfin Totem"," Rare"," Minion"," Totem","  Shaman", 2 , 0 , 3    ));
		JTU.add(new Minion("Primordial Drake"," Epic"," Minion"," Dragon","  Any", 8 , 4 , 8    ));
		JTU.add(new Spell("Primordial Glyph"," Epic"," Spell"," ","  Mage",2," ","  "));
		JTU.add(new Minion("Pterrordax Hatchling"," Common"," Minion"," Beast","  Any", 3 , 2 , 2    ));
		JTU.add(new Minion("Pyros"," Legendary"," Minion"," Elemental","  Mage", 2 , 2 , 2    ));
		JTU.add(new Minion("Radiant Elemental"," Common"," Minion"," Elemental","  Priest", 2 , 2 , 3    ));
		JTU.add(new Minion("Raptor Hatchling"," Rare"," Minion"," Beast","  Hunter", 1 , 2 , 1    ));
		JTU.add(new Minion("Ravasaur Runt"," Common"," Minion"," Beast","  Any", 2 , 2 , 2    ));
		JTU.add(new Minion("Ravenous Pterrordax"," Common"," Minion"," Beast","  Warlock", 4 , 4 , 4    ));
		JTU.add(new Minion("Razorpetal Lasher"," Common"," Minion"," General","  Rogue", 2 , 2 , 2    ));
		JTU.add(new Spell("Razorpetal Volley"," Common"," Spell"," ","  Rogue",2," ","  "));
		JTU.add(new Minion("Rockpool Hunter"," Common"," Minion"," Murloc","  Any", 2 , 2 , 3    ));
		JTU.add(new Minion("Sabretooth Stalker"," Common"," Minion"," Beast","  Any", 6 , 8 , 2    ));
		JTU.add(new Minion("Sated Threshadon"," Common"," Minion"," Beast","  Any", 7 , 5 , 7    ));
		JTU.add(new Minion("Servant of Kalimos"," Rare"," Minion"," Elemental","  Any", 5 , 4 , 5    ));
		JTU.add(new Spell("Shadow Visions"," Epic"," Spell"," ","  Priest",2," ","  "));
		JTU.add(new Minion("Shellshifter"," Rare"," Minion"," General","  Druid", 4 , 3 , 3    ));
		JTU.add(new Minion("Sherazin, Corpse Flower"," Legendary"," Minion"," General","  Rogue", 4 , 5 , 3    ));
		JTU.add(new Minion("Shimmering Tempest"," Common"," Minion"," Elemental","  Mage", 2 , 2 , 1    ));
		JTU.add(new Spell("Spikeridged Steed"," Rare"," Spell"," ","  Paladin",6," ","  "));
		JTU.add(new Spell("Spirit Echo"," Epic"," Spell"," ","  Shaman",3," ","  "));
		JTU.add(new Minion("Spiritsinger Umbra"," Legendary"," Minion"," General","  Any", 4 , 3 , 4    ));
		JTU.add(new Spell("Stampede"," Epic"," Spell"," ","  Hunter",1," ","  "));
		JTU.add(new Minion("Steam Surger"," Rare"," Minion"," Elemental","  Mage", 4 , 5 , 4    ));
		JTU.add(new Minion("Stegodon"," Common"," Minion"," Beast","  Any", 4 , 2 , 6    ));
		JTU.add(new Minion("Stone Sentinel"," Epic"," Minion"," Elemental","  Shaman", 7 , 4 , 4    ));
		JTU.add(new Minion("Stonehill Defender"," Rare"," Minion"," General","  Any", 3 , 1 , 4    ));
		JTU.add(new Minion("Stormwatcher"," Common"," Minion"," Elemental","  Any", 7 , 4 , 8    ));
		JTU.add(new Minion("Stubborn Gastropod"," Common"," Minion"," Beast","  Any", 2 , 1 , 2    ));
		JTU.add(new Spell("Sudden Genesis"," Epic"," Spell"," ","  Warrior",5," ","  "));
		JTU.add(new Minion("Sunkeeper Tarim"," Legendary"," Minion"," General","  Paladin", 6 , 3 , 7    ));
		JTU.add(new Minion("Swamp King Dred"," Legendary"," Minion"," Beast","  Hunter", 7 , 9 , 9    ));
		JTU.add(new Minion("Tar Creeper"," Common"," Minion"," Elemental","  Any", 3 , 1 , 5    ));
		JTU.add(new Minion("Tar Lord"," Common"," Minion"," Elemental","  Warrior", 7 , 1 , 11    ));
		JTU.add(new Minion("Tar Lurker"," Common"," Minion"," Elemental","  Warlock", 5 , 1 , 7    ));
		JTU.add(new Minion("Terrorscale Stalker"," Rare"," Minion"," General","  Hunter", 3 , 3 , 3    ));
		JTU.add(new Spell("The Caverns Below"," Legendary"," Spell"," ","  Rogue",1," ","  "));
		JTU.add(new Spell("The Last Kaleidosaur"," Legendary"," Spell"," ","  Paladin",1," ","  "));
		JTU.add(new Spell("The Marsh Queen"," Legendary"," Spell"," ","  Hunter",1," ","  "));
		JTU.add(new Minion("The Voraxx"," Legendary"," Minion"," General","  Any", 4 , 3 , 3    ));
		JTU.add(new Minion("Thunder Lizard"," Common"," Minion"," Beast","  Any", 3 , 3 , 3    ));
		JTU.add(new Spell("Tidal Surge"," Common"," Spell"," ","  Shaman",4," ","  "));
		JTU.add(new Minion("Tol'vir Stoneshaper"," Rare"," Minion"," General","  Any", 4 , 3 , 5    ));
		JTU.add(new Minion("Tol'vir Warden"," Rare"," Minion"," General","  Hunter", 5 , 3 , 5    ));
		JTU.add(new Minion("Tortollan Forager"," Common"," Minion"," General","  Druid", 2 , 2 , 2    ));
		JTU.add(new Minion("Tortollan Primalist"," Epic"," Minion"," General","  Any", 8 , 5 , 4    ));
		JTU.add(new Minion("Tortollan Shellraiser"," Common"," Minion"," General","  Priest", 4 , 2 , 6    ));
		JTU.add(new Minion("Tyrantus"," Legendary"," Minion"," Beast","  Druid", 10 , 12 , 12    ));
		JTU.add(new Minion("Ultrasaur"," Common"," Minion"," Beast","  Any", 10 , 7  , 14   ));
		JTU.add(new Spell("Unite the Murlocs"," Legendary"," Spell"," ","  Shaman",1," ","  "));
		JTU.add(new Minion("Verdant Longneck"," Common"," Minion"," Beast","  Druid", 5 , 5 , 4    ));
		JTU.add(new Minion("Vicious Fledgling"," Rare"," Minion"," Beast","  Any", 3 , 3 , 3    ));
		JTU.add(new Minion("Vilespine Slayer"," Epic"," Minion"," General","  Rogue", 5 , 3 , 4    ));
		JTU.add(new Minion("Vinecleaver"," Rare"," Weapon"," ","  Paladin", 7 , 4 , 3    ));
		JTU.add(new Minion("Volatile Elemental"," Common"," Minion"," Elemental","  Any", 2 , 1 , 1    ));
		JTU.add(new Spell("Volcano"," Rare"," Spell"," ","  Shaman",5," ","  "));
		JTU.add(new Minion("Volcanosaur"," Rare"," Minion"," Beast","  Any", 7 , 5 , 6    ));
		return JTU;

}
}
