package cardSets;

import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetKaC {

	public ArrayList<Card> KaCList() {
		ArrayList<Card> KaC = new ArrayList<Card>();
		KaC.add(new Minion("Aluneth"," Legendary"," Weapon"," ","  Mage", 6 , 0 , 3    ));
		KaC.add(new Minion("Arcane Artificer"," Common"," Minion"," Elemental","  Mage", 1 , 1 , 2    ));
		KaC.add(new Minion("Arcane Tyrant"," Epic"," Minion"," Elemental","  Any", 5 , 4 , 4    ));
		KaC.add(new Minion("Astral Tiger"," Epic"," Minion"," General","  Druid", 4 , 3 , 5    ));
		KaC.add(new Spell("Barkskin"," Common"," Spell"," ","  Druid",1," ","  "));
		KaC.add(new Minion("Benevolent Djinn"," Common"," Minion"," Elemental","  Paladin", 3 , 2 , 4    ));
		KaC.add(new Minion("Bladed Gauntlet"," Epic"," Weapon"," ","  Warrior", 2 , 0 , 2    ));
		KaC.add(new Minion("Boisterous Bard"," Common"," Minion"," General","  Any", 3 , 3 , 2    ));
		KaC.add(new Spell("Branching Paths"," Epic"," Spell"," ","  Druid",4," ","  "));
		KaC.add(new Spell("Call to Arms"," Epic"," Spell"," ","  Paladin",5," ","  "));
		KaC.add(new Minion("Candleshot"," Common"," Weapon"," ","  Hunter", 1 , 1 , 3    ));
		KaC.add(new Minion("Carnivorous Cube"," Epic"," Minion"," General","  Any", 5 , 4 , 6    ));
		KaC.add(new Spell("Cataclysm"," Epic"," Spell"," ","  Warlock",4," ","  "));
		KaC.add(new Minion("Cave Hydra"," Common"," Minion"," Beast","  Hunter", 3 , 2 , 4    ));
		KaC.add(new Minion("Cavern Shinyfinder"," Common"," Minion"," General","  Rogue", 2 , 3 , 1    ));
		KaC.add(new Spell("Cheat Death"," Common"," Spell"," ","  Rogue",2," ","  "));
		KaC.add(new Minion("Corridor Creeper"," Epic"," Minion"," Beast","  Any", 7 , 2 , 5    ));
		KaC.add(new Minion("Corrosive Sludge"," Common"," Minion"," General","  Any", 5 , 5 , 5    ));
		KaC.add(new Spell("Crushing Hand"," Common"," Spell"," ","  Shaman",2," ","  "));
		KaC.add(new Spell("Crushing Walls"," Epic"," Spell"," ","  Hunter",7," ","  "));
		KaC.add(new Minion("Crystal Lion"," Rare"," Minion"," General","  Paladin", 6 , 5 , 5    ));
		KaC.add(new Minion("Cursed Disciple"," Common"," Minion"," General","  Any", 4 , 5 , 1    ));
		KaC.add(new Spell("Dark Pact"," Common"," Spell"," ","  Warlock",1," ","  "));
		KaC.add(new Spell("Deck of Wonders"," Epic"," Spell"," ","  Mage",5," ","  "));
		KaC.add(new Minion("Dire Mole"," Common"," Minion"," Beast","  Any", 1 , 1 , 3    ));
		KaC.add(new Minion("Dragon Soul"," Legendary"," Weapon"," ","  Priest", 3 , 0 , 3    ));
		KaC.add(new Spell("Dragon's Fury"," Epic"," Spell"," ","  Mage",5," ","  "));
		KaC.add(new Minion("Dragoncaller Alanna"," Legendary"," Minion"," General","  Mage", 9 , 3 , 3    ));
		KaC.add(new Minion("Dragonhatcher"," Epic"," Minion"," General","  Any", 9 , 2 , 4    ));
		KaC.add(new Minion("Dragonslayer"," Common"," Minion"," General","  Any", 3 , 4 , 3    ));
		KaC.add(new Minion("Drygulch Jailor"," Common"," Minion"," General","  Paladin", 2 , 1 , 1    ));
		KaC.add(new Minion("Drywhisker Armorer"," Common"," Minion"," General","  Warrior", 2 , 2 , 2    ));
		KaC.add(new Minion("Duskbreaker"," Rare"," Minion"," Dragon","  Priest", 4 , 3 , 3    ));
		KaC.add(new Minion("Ebon Dragonsmith"," Rare"," Minion"," Dragon","  Any", 4 , 3 , 4    ));
		KaC.add(new Minion("Elven Minstrel"," Rare"," Minion"," General","  Rogue", 4 , 3 , 2    ));
		KaC.add(new Spell("Evasion"," Epic"," Spell"," ","  Rogue",2," ","  "));
		KaC.add(new Spell("Explosive Runes"," Rare"," Spell"," ","  Mage",3," ","  "));
		KaC.add(new Minion("Fal'dorei Strider"," Epic"," Minion"," General","  Rogue", 4 , 4 , 4    ));
		KaC.add(new Minion("Feral Gibberer"," Rare"," Minion"," General","  Any", 1 , 1 , 1    ));
		KaC.add(new Spell("Flanking Strike"," Common"," Spell"," ","  Hunter",4," ","  "));
		KaC.add(new Minion("Fungal Enchanter"," Common"," Minion"," General","  Any", 3 , 3 , 3    ));
		KaC.add(new Minion("Fungalmancer"," Common"," Minion"," General","  Any", 5 , 2 , 2    ));
		KaC.add(new Minion("Furbolg Mossbinder"," Rare"," Minion"," General","  Any", 5 , 1 , 1    ));
		KaC.add(new Spell("Gather Your Party"," Rare"," Spell"," ","  Warrior",6," ","  "));
		KaC.add(new Minion("Gemstudded Golem"," Common"," Minion"," General","  Warrior", 6 , 5 , 9    ));
		KaC.add(new Minion("Geosculptor Yip"," Legendary"," Minion"," General","  Warrior", 8 , 4 , 8    ));
		KaC.add(new Minion("Gilded Gargoyle"," Common"," Minion"," General","  Priest", 3 , 2 , 2    ));
		KaC.add(new Minion("Grand Archivist"," Epic"," Minion"," General","  Any", 8 , 4 , 7    ));
		KaC.add(new Minion("Gravelsnout Knight"," Rare"," Minion"," General","  Any", 1 , 2 , 3    ));
		KaC.add(new Minion("Greedy Sprite"," Rare"," Minion"," General","  Druid", 3 , 3 , 1    ));
		KaC.add(new Minion("Green Jelly"," Common"," Minion"," General","  Any", 5 , 3 , 3    ));
		KaC.add(new Minion("Grizzled Guardian"," Rare"," Minion"," Beast","  Druid", 8 , 3 , 5    ));
		KaC.add(new Minion("Grumble, Worldshaker"," Legendary"," Minion"," Elemental","  Shaman", 6 , 7 , 7    ));
		KaC.add(new Minion("Guild Recruiter"," Common"," Minion"," General","  Any", 5 , 2 , 4    ));
		KaC.add(new Spell("Healing Rain"," Common"," Spell"," ","  Shaman",3," ","  "));
		KaC.add(new Minion("Hoarding Dragon"," Common"," Minion"," Dragon","  Any", 4 , 5 , 6    ));
		KaC.add(new Minion("Hooked Reaver"," Rare"," Minion"," Demon","  Warlock", 4 , 4 , 4    ));
		KaC.add(new Minion("Hungry Ettin"," Rare"," Minion"," General","  Any", 6 , 4 , 10    ));
		KaC.add(new Minion("Ironwood Golem"," Common"," Minion"," General","  Druid", 4 , 3 , 6    ));
		KaC.add(new Minion("Ixlid, Fungal Lord"," Legendary"," Minion"," General","  Druid", 5 , 2 , 4    ));
		KaC.add(new Minion("Kathrena Winterwisp"," Legendary"," Minion"," General","  Hunter", 8 , 6 , 6    ));
		KaC.add(new Minion("King Togwaggle"," Legendary"," Minion"," General","  Any", 8 , 5 , 5    ));
		KaC.add(new Minion("Kingsbane"," Legendary"," Weapon"," ","  Rogue", 1 , 1 , 3    ));
		KaC.add(new Minion("Kobold Apprentice"," Common"," Minion"," General","  Any", 3 , 2 , 1    ));
		KaC.add(new Minion("Kobold Barbarian"," Rare"," Minion"," General","  Warrior", 3 , 4 , 4    ));
		KaC.add(new Minion("Kobold Hermit"," Common"," Minion"," General","  Shaman", 2 , 1 , 1    ));
		KaC.add(new Minion("Kobold Illusionist"," Rare"," Minion"," General","  Rogue", 4 , 3 , 3    ));
		KaC.add(new Minion("Kobold Librarian"," Common"," Minion"," General","  Warlock", 1 , 2 , 1    ));
		KaC.add(new Minion("Kobold Monk"," Rare"," Minion"," General","  Any", 4 , 3 , 6    ));
		KaC.add(new Spell("Lesser Amethyst Spellstone"," Rare"," Spell"," ","  Warlock",4," ","  "));
		KaC.add(new Spell("Lesser Diamond Spellstone"," Rare"," Spell"," ","  Priest",7," ","  "));
		KaC.add(new Spell("Lesser Emerald Spellstone"," Rare"," Spell"," ","  Hunter",6," ","  "));
		KaC.add(new Spell("Lesser Jasper Spellstone"," Rare"," Spell"," ","  Druid",1," ","  "));
		KaC.add(new Spell("Lesser Mithril Spellstone"," Rare"," Spell"," ","  Warrior",7," ","  "));
		KaC.add(new Spell("Lesser Onyx Spellstone"," Rare"," Spell"," ","  Rogue",5," ","  "));
		KaC.add(new Spell("Lesser Pearl Spellstone"," Rare"," Spell"," ","  Paladin",2," ","  "));
		KaC.add(new Spell("Lesser Ruby Spellstone"," Rare"," Spell"," ","  Mage",2," ","  "));
		KaC.add(new Spell("Lesser Sapphire Spellstone"," Rare"," Spell"," ","  Shaman",7," ","  "));
		KaC.add(new Spell("Level Up!"," Epic"," Spell"," ","  Paladin",6," ","  "));
		KaC.add(new Minion("Leyline Manipulator"," Rare"," Minion"," Elemental","  Mage", 4 , 4 , 5    ));
		KaC.add(new Minion("Lone Champion"," Rare"," Minion"," General","  Any", 3 , 2 , 4    ));
		KaC.add(new Minion("Lynessa Sunsorrow"," Legendary"," Minion"," General","  Paladin", 7 , 1 , 1    ));
		KaC.add(new Minion("Marin the Fox"," Legendary"," Minion"," General","  Any", 8 , 6 , 6    ));
		KaC.add(new Minion("Master Oakheart"," Legendary"," Minion"," General","  Any", 9 , 5 , 5    ));
		KaC.add(new Minion("Murmuring Elemental"," Rare"," Minion"," Elemental","  Shaman", 2 , 1 , 1    ));
		KaC.add(new Spell("Oaken Summons"," Common"," Spell"," ","  Druid",4," ","  "));
		KaC.add(new Minion("Plated Beetle"," Common"," Minion"," Beast","  Any", 2 , 2 , 3    ));
		KaC.add(new Minion("Possessed Lackey"," Rare"," Minion"," General","  Warlock", 6 , 2 , 2    ));
		KaC.add(new Spell("Potion of Heroism"," Common"," Spell"," ","  Paladin",2," ","  "));
		KaC.add(new Spell("Primal Talismans"," Rare"," Spell"," ","  Shaman",3," ","  "));
		KaC.add(new Spell("Psionic Probe"," Common"," Spell"," ","  Priest",1," ","  "));
		KaC.add(new Spell("Psychic Scream"," Epic"," Spell"," ","  Priest",7," ","  "));
		KaC.add(new Minion("Raven Familiar"," Common"," Minion"," Beast","  Mage", 2 , 2 , 2    ));
		KaC.add(new Spell("Reckless Flurry"," Epic"," Spell"," ","  Warrior",3," ","  "));
		KaC.add(new Minion("Rhok'delar"," Legendary"," Weapon"," ","  Hunter", 7 , 4 , 2    ));
		KaC.add(new Minion("Rummaging Kobold"," Epic"," Minion"," General","  Any", 3 , 1 , 3    ));
		KaC.add(new Minion("Scorp-o-matic"," Rare"," Minion"," Mech","  Any", 2 , 1 , 2    ));
		KaC.add(new Minion("Seeping Oozeling"," Rare"," Minion"," General","  Hunter", 6 , 5 , 4    ));
		KaC.add(new Minion("Sewer Crawler"," Common"," Minion"," General","  Any", 3 , 1 , 1    ));
 		KaC.add(new Minion("Shimmering Courser"," Epic"," Minion"," Beast","  Any", 4 , 3 , 3    ));
		KaC.add(new Minion("Shrieking Shroom"," Rare"," Minion"," General","  Any", 3 , 1 , 2    ));
		KaC.add(new Minion("Shroom Brewer"," Common"," Minion"," General","  Any", 4 , 4 , 4    ));
		KaC.add(new Minion("Silver Vanguard"," Common"," Minion"," General","  Any", 7 , 3 , 3    ));
		KaC.add(new Minion("Skull of the Man'ari"," Legendary"," Weapon"," ","  Warlock", 5 , 0 , 3    ));
		KaC.add(new Minion("Sleepy Dragon"," Common"," Minion"," Dragon","  Any", 9 , 4 , 12    ));
		KaC.add(new Minion("Sneaky Devil"," Common"," Minion"," Demon","  Any", 4 , 2 , 2    ));
		KaC.add(new Minion("Sonya Shadowdancer"," Legendary"," Minion"," General","  Rogue", 3 , 2 , 2    ));
		KaC.add(new Minion("Spiteful Summoner"," Epic"," Minion"," General","  Any", 7 , 4 , 4    ));
		KaC.add(new Minion("Stoneskin Basilisk"," Common"," Minion"," Beast","  Any", 3 , 1 , 1    ));
		KaC.add(new Spell("Sudden Betrayal"," Common"," Spell"," ","  Rogue",2," ","  "));
		KaC.add(new Minion("Temporus"," Legendary"," Minion"," Dragon","  Priest", 7 , 6 , 6    ));
		KaC.add(new Minion("The Darkness"," Legendary"," Minion"," General","  Any", 4  , 20  ,20  ));
		KaC.add(new Minion("The Runespear"," Legendary"," Weapon"," ","  Shaman", 8 , 3 , 3    ));
		KaC.add(new Spell("To My Side!"," Epic"," Spell"," ","  Hunter",6," ","  "));
		KaC.add(new Minion("Toothy Chest"," Common"," Minion"," General","  Any", 3 , 0 , 4    ));
		KaC.add(new Minion("Trogg Gloomeater"," Common"," Minion"," General","  Any", 5 , 1 , 5    ));
		KaC.add(new Minion("Twig of the World Tree"," Legendary"," Weapon"," ","  Druid", 4 , 1 , 5    ));
		KaC.add(new Minion("Twilight Acolyte"," Epic"," Minion"," General","  Priest", 3 , 2 , 4    ));
		KaC.add(new Spell("Twilight's Call"," Rare"," Spell"," ","  Priest",3," ","  "));
		KaC.add(new Spell("Unidentified Elixir"," Common"," Spell"," ","  Priest",3," ","  "));
		KaC.add(new Minion("Unidentified Maul"," Rare"," Weapon"," ","  Paladin", 3 , 2 , 2    ));
		KaC.add(new Spell("Unidentified Shield"," Common"," Spell"," ","  Warrior",6," ","  "));
		KaC.add(new Spell("Unstable Evolution"," Epic"," Spell"," ","  Shaman",1," ","  "));
		KaC.add(new Minion("Val'anyr"," Legendary"," Weapon"," ","  Paladin", 6 , 4 , 2    ));
		KaC.add(new Minion("Violet Wurm"," Common"," Minion"," Beast","  Any", 8 , 7 , 7    ));
		KaC.add(new Minion("Void Ripper"," Epic"," Minion"," Demon","  Any", 3 , 3 , 3    ));
		KaC.add(new Minion("Voidlord"," Epic"," Minion"," Demon","  Warlock", 9 , 3 , 9    ));
		KaC.add(new Minion("Vulgar Homunculus"," Common"," Minion"," Demon","  Warlock", 2 , 2 , 4    ));
		KaC.add(new Spell("Wandering Monster"," Rare"," Spell"," ","  Hunter",2," ","  "));
		KaC.add(new Minion("Wax Elemental"," Common"," Minion"," Elemental","  Any", 1 , 0 , 2    ));
		KaC.add(new Minion("Windshear Stormcaller"," Epic"," Minion"," General","  Shaman", 5 , 5 , 5    ));
		KaC.add(new Minion("Woecleaver"," Legendary"," Weapon"," ","  Warrior", 8 , 3 , 3    ));
		KaC.add(new Minion("Zola the Gorgon"," Legendary"," Minion"," General","  Any", 3 , 2 , 2    ));
 				return KaC;
}
}