package cardSets;

import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetSoU {

	public ArrayList<Card> SoUList() {
		ArrayList<Card> SoU = new ArrayList<Card>();
		SoU.add(new Spell("Activate the Obelisk"," Legendary"," Spell"," ","  Priest",1," ","  "));
		SoU.add(new Minion("Ancestral Guardian"," Common"," Minion"," General","  Paladin", 4 , 4 , 2    ));
		SoU.add(new Spell("Ancient Mysteries"," Common"," Spell"," ","  Mage",2," ","  "));
		SoU.add(new Minion("Anka, the Buried"," Legendary"," Minion"," General","  Rogue", 5 , 5 , 5    ));
		SoU.add(new Minion("Anubisath Defender"," Epic"," Minion"," General","  Druid", 5 , 3 , 5    ));
		SoU.add(new Minion("Anubisath Warbringer"," Common"," Minion"," General","  Any", 9 , 9 , 9    ));
		SoU.add(new Minion("Arcane Flakmage"," Rare"," Minion"," General","  Mage", 2 , 3 , 2    ));
		SoU.add(new Minion("Armagedillo"," Legendary"," Minion"," Beast","  Warrior", 6 , 4 , 7    ));
		SoU.add(new Minion("Armored Goon"," Common"," Minion"," General","  Warrior", 6 , 6 , 7    ));
		SoU.add(new Spell("Bazaar Burglary"," Legendary"," Spell"," ","  Rogue",1," ","  "));
		SoU.add(new Minion("Bazaar Mugger"," Rare"," Minion"," General","  Rogue", 5 , 3 , 5    ));
		SoU.add(new Minion("Beaming Sidekick"," Common"," Minion"," General","  Any", 1 , 1 , 2    ));
		SoU.add(new Spell("BEEEES!!!"," Common"," Spell"," ","  Druid",3," ","  "));
		SoU.add(new Minion("Blatant Decoy"," Epic"," Minion"," General","  Any", 6 , 5 , 5    ));
		SoU.add(new Minion("Bloodsworn Mercenary"," Epic"," Minion"," General","  Warrior", 3 , 3 , 3    ));
		SoU.add(new Minion("Body Wrapper"," Epic"," Minion"," General","  Any", 4 , 4 , 4    ));
		SoU.add(new Minion("Bone Wraith"," Common"," Minion"," General","  Any", 4 , 2 , 5    ));
		SoU.add(new Minion("Brazen Zealot"," Rare"," Minion"," General","  Paladin", 1 , 2 , 1    ));
		SoU.add(new Minion("Bug Collector"," Common"," Minion"," General","  Any", 2 , 2 , 1    ));
		SoU.add(new Minion("Candletaker"," Common"," Minion"," General","  Any", 3 , 3 , 2    ));
		SoU.add(new Spell("Clever Disguise"," Common"," Spell"," ","  Rogue",2," ","  "));
		SoU.add(new Minion("Cloud Prince"," Common"," Minion"," Elemental","  Mage", 5 , 4 , 4    ));
		SoU.add(new Minion("Colossus of the Moon"," Legendary"," Minion"," General","  Any", 10 , 10 , 10    ));
		SoU.add(new Minion("Conjured Mirage"," Rare"," Minion"," General","  Any", 4 , 3 , 10    ));
		SoU.add(new Spell("Corrupt the Waters"," Legendary"," Spell"," ","  Shaman",1," ","  "));
		SoU.add(new Minion("Crystal Merchant"," Epic"," Minion"," General","  Druid", 2 , 1 , 4    ));
		SoU.add(new Minion("Dark Pharaoh Tekahn"," Legendary"," Minion"," General","  Warlock", 5 , 4 , 4    ));
		SoU.add(new Minion("Desert Hare"," Common"," Minion"," Beast","  Any", 3 , 1 , 1    ));
		SoU.add(new Minion("Desert Obelisk"," Epic"," Minion"," General","  Any", 5 , 0 , 5    ));
		SoU.add(new Minion("Desert Spear"," Common"," Weapon"," ","  Hunter", 3 , 1 , 3    ));
		SoU.add(new Minion("Dinotamer Brann"," Legendary"," Minion"," General","  Hunter", 7 , 2 , 4    ));
		SoU.add(new Minion("Diseased Vulture"," Epic"," Minion"," Beast","  Warlock", 4 , 3 , 5    ));
		SoU.add(new Minion("Dune Sculptor"," Rare"," Minion"," General","  Mage", 3 , 3 , 3    ));
		SoU.add(new Minion("Dwarven Archaeologist"," Epic"," Minion"," General","  Any", 2 , 2 , 3    ));
		SoU.add(new Spell("Earthquake"," Rare"," Spell"," ","  Shaman",7," ","  "));
		SoU.add(new Minion("Elise the Enlightened"," Legendary"," Minion"," General","  Druid", 5 , 5 , 5    ));
		SoU.add(new Spell("Embalming Ritual"," Common"," Spell"," ","  Priest",1," ","  "));
		SoU.add(new Minion("EVIL Recruiter"," Common"," Minion"," General","  Warlock", 3 , 3 , 3    ));
		SoU.add(new Minion("EVIL Totem"," Common"," Minion"," Totem","  Shaman", 2 , 0 , 2    ));
		SoU.add(new Minion("Expired Merchant"," Rare"," Minion"," General","  Warlock", 2 , 2 , 1    ));
		SoU.add(new Minion("Faceless Lurker"," Common"," Minion"," General","  Any", 5 , 3 , 3    ));
		SoU.add(new Minion("Fishflinger"," Common"," Minion"," Murloc","  Any", 2 , 3 , 2    ));
		SoU.add(new Spell("Flame Ward"," Common"," Spell"," ","  Mage",3," ","  "));
		SoU.add(new Minion("Frightened Flunky"," Common"," Minion"," General","  Warrior", 2 , 2 , 2    ));
		SoU.add(new Minion("Garden Gnome"," Rare"," Minion"," General","  Druid", 4 , 2 , 3    ));
		SoU.add(new Minion("Generous Mummy"," Rare"," Minion"," General","  Any", 3 , 5 , 4    ));
		SoU.add(new Minion("Golden Scarab"," Common"," Minion"," Beast","  Any", 3 , 2 , 2    ));
		SoU.add(new Minion("Grandmummy"," Rare"," Minion"," General","  Priest", 2 , 1 , 2    ));
		SoU.add(new Spell("Hack the System"," Legendary"," Spell"," ","  Warrior",1," ","  "));
		SoU.add(new Spell("Hidden Oasis"," Rare"," Spell"," ","  Druid",6," ","  "));
		SoU.add(new Minion("High Priest Amet"," Legendary"," Minion"," General","  Priest", 4 , 2 , 7    ));
		SoU.add(new Minion("History Buff"," Epic"," Minion"," General","  Any", 3 , 3 , 4    ));
		SoU.add(new Spell("Holy Ripple"," Rare"," Spell"," ","  Priest",2," ","  "));
		SoU.add(new Minion("Hooked Scimitar"," Common"," Weapon"," ","  Rogue", 3 , 2 , 2    ));
		SoU.add(new Spell("Hunter's Pack"," Common"," Spell"," ","  Hunter",3," ","  "));
		SoU.add(new Minion("Hyena Alpha"," Rare"," Minion"," Beast","  Hunter", 4 , 3 , 3    ));
		SoU.add(new Spell("Impbalming"," Rare"," Spell"," ","  Warlock",4," ","  "));
		SoU.add(new Minion("Infested Goblin"," Rare"," Minion"," General","  Any", 3 , 2 , 3    ));
		SoU.add(new Minion("Injured Tol'vir"," Common"," Minion"," General","  Any", 2 , 2 , 6    ));
		SoU.add(new Spell("Into the Fray"," Rare"," Spell"," ","  Warrior",1," ","  "));
		SoU.add(new Minion("Jar Dealer"," Common"," Minion"," General","  Any", 1 , 1 , 1    ));
		SoU.add(new Minion("Khartut Defender"," Rare"," Minion"," General","  Any", 6 , 3 , 4    ));
		SoU.add(new Minion("King Phaoris"," Legendary"," Minion"," General","  Any", 10 , 5 , 5    ));
		SoU.add(new Minion("Kobold Sandtrooper"," Common"," Minion"," General","  Any", 2 , 2 , 1    ));
		SoU.add(new Minion("Livewire Lance"," Epic"," Weapon"," ","  Warrior", 3 , 2 , 2    ));
		SoU.add(new Minion("Living Monument"," Common"," Minion"," General","  Any", 10 , 10 , 10    ));
		SoU.add(new Spell("Making Mummies"," Legendary"," Spell"," ","  Paladin",1," ","  "));
		SoU.add(new Minion("Micro Mummy"," Epic"," Minion"," Mech","  Paladin", 2 , 1 , 2    ));
		SoU.add(new Minion("Mischief Maker"," Epic"," Minion"," General","  Any", 3 , 3 , 3    ));
		SoU.add(new Minion("Mogu Cultist"," Epic"," Minion"," General","  Any", 1 , 1 , 1    ));
		SoU.add(new Minion("Mogu Fleshshaper"," Rare"," Minion"," General","  Shaman", 9 , 3 , 4    ));
		SoU.add(new Minion("Mortuary Machine"," Epic"," Minion"," Mech","  Any", 5 , 8 , 8    ));
		SoU.add(new Minion("Murmy"," Common"," Minion"," Murloc","  Any", 1 , 1 , 1    ));
		SoU.add(new Minion("Naga Sand Witch"," Rare"," Minion"," General","  Mage", 5 , 5 , 5    ));
		SoU.add(new Minion("Neferset Ritualist"," Rare"," Minion"," General","  Any", 2 , 2 , 3    ));
		SoU.add(new Minion("Neferset Thrasher"," Common"," Minion"," General","  Warlock", 3 , 4 , 5    ));
		SoU.add(new Minion("Oasis Surger"," Common"," Minion"," Elemental","  Druid", 5 , 3 , 3    ));
		SoU.add(new Minion("Octosari"," Legendary"," Minion"," Beast","  Any", 8 , 8 , 8    ));
		SoU.add(new Spell("Overflow"," Rare"," Spell"," ","  Druid",7," ","  "));
		SoU.add(new Spell("Penance"," Common"," Spell"," ","  Priest",2," ","  "));
		SoU.add(new Minion("Phalanx Commander"," Common"," Minion"," General","  Any", 5 , 4 , 5    ));
		SoU.add(new Minion("Pharaoh Cat"," Common"," Minion"," Beast","  Rogue", 1 , 1 , 2    ));
		SoU.add(new Spell("Pharaoh's Blessing"," Rare"," Spell"," ","  Paladin",6," ","  "));
		SoU.add(new Minion("Pit Crocolisk"," Common"," Minion"," Beast","  Any", 8 , 5 , 6    ));
		SoU.add(new Spell("Plague of Death"," Epic"," Spell"," ","  Priest",9," ","  "));
		SoU.add(new Spell("Plague of Flames"," Rare"," Spell"," ","  Warlock",1," ","  "));
		SoU.add(new Spell("Plague of Madness"," Rare"," Spell"," ","  Rogue",1," ","  "));
		SoU.add(new Spell("Plague of Murlocs"," Epic"," Spell"," ","  Shaman",3," ","  "));
		SoU.add(new Spell("Plague of Wrath"," Rare"," Spell"," ","  Warrior",5," ","  "));
		SoU.add(new Spell("Pressure Plate"," Common"," Spell"," ","  Hunter",2," ","  "));
		SoU.add(new Minion("Psychopomp"," Epic"," Minion"," General","  Priest", 4 , 3 , 1    ));
		SoU.add(new Spell("Puzzle Box of Yogg-Saron"," Epic"," Spell"," ","  Mage",10," ","  "));
		SoU.add(new Minion("Questing Explorer"," Rare"," Minion"," General","  Any", 2 , 2 , 3    ));
		SoU.add(new Minion("Quicksand Elemental"," Rare"," Minion"," Elemental","  Any", 2 , 3 , 2    ));
		SoU.add(new Spell("Raid the Sky Temple"," Legendary"," Spell"," ","  Mage",1," ","  "));
		SoU.add(new Minion("Ramkahen Wildtamer"," Rare"," Minion"," General","  Hunter", 3 , 4 , 3    ));
		SoU.add(new Minion("Reno the Relicologist"," Legendary"," Minion"," General","  Mage", 6 , 4 , 6    ));
		SoU.add(new Minion("Restless Mummy"," Common"," Minion"," General","  Warrior", 4 , 3 , 2    ));
		SoU.add(new Minion("Riftcleaver"," Epic"," Minion"," Demon","  Warlock", 6 , 7 , 5    ));
		SoU.add(new Minion("Sahket Sapper"," Rare"," Minion"," Pirate","  Rogue", 4 , 4 , 4    ));
		SoU.add(new Minion("Salhet's Pride"," Rare"," Minion"," Beast","  Paladin", 3 , 3 , 1    ));
		SoU.add(new Minion("Sandhoof Waterbearer"," Common"," Minion"," General","  Priest", 5 , 5 , 5    ));
		SoU.add(new Minion("Sandstorm Elemental"," Common"," Minion"," Elemental","  Shaman", 2 , 2 , 2    ));
		SoU.add(new Minion("Sandwasp Queen"," Common"," Minion"," Beast","  Paladin", 2 , 3 , 1    ));
		SoU.add(new Minion("Scarlet Webweaver"," Epic"," Minion"," Beast","  Hunter", 6 , 5 , 5    ));
		SoU.add(new Minion("Serpent Egg"," Common"," Minion"," General","  Any", 2 , 0 , 3    ));
		SoU.add(new Spell("Shadow of Death"," Epic"," Spell"," ","  Rogue",4," ","  "));
		SoU.add(new Minion("Siamat"," Legendary"," Minion"," Elemental","  Any", 7 , 6 , 6    ));
		SoU.add(new Spell("Sinister Deal"," Common"," Spell"," ","  Warlock",1," ","  "));
		SoU.add(new Minion("Sir Finley of the Sands"," Legendary"," Minion"," Murloc","  Paladin", 2 , 2 , 3    ));
		SoU.add(new Minion("Spitting Camel"," Common"," Minion"," Beast","  Any", 2 , 2 , 4    ));
		SoU.add(new Minion("Splitting Axe"," Epic"," Weapon"," ","  Shaman", 4 , 3 , 2    ));
		SoU.add(new Spell("Subdue"," Common"," Spell"," ","  Paladin",2," ","  "));
		SoU.add(new Minion("Sunstruck Henchman"," Rare"," Minion"," General","  Any", 4 , 6 , 5    ));
		SoU.add(new Spell("Supreme Archaeology"," Legendary"," Spell"," ","  Warlock",1," ","  "));
		SoU.add(new Spell("Swarm of Locusts"," Rare"," Spell"," ","  Hunter",6," ","  "));
		SoU.add(new Minion("Temple Berserker"," Common"," Minion"," General","  Any", 2 , 1 , 2    ));
		SoU.add(new Spell("Tip the Scales"," Epic"," Spell"," ","  Paladin",8," ","  "));
		SoU.add(new Minion("Tomb Warden"," Rare"," Minion"," Mech","  Warrior", 8 , 3 , 6    ));
		SoU.add(new Minion("Tortollan Pilgrim"," Epic"," Minion"," General","  Mage", 8 , 5 , 5    ));
		SoU.add(new Spell("Totemic Surge"," Common"," Spell"," ","  Shaman",0," ","  "));
		SoU.add(new Spell("Unseal the Vault"," Legendary"," Spell"," ","  Hunter",1," ","  "));
		SoU.add(new Spell("Untapped Potential"," Legendary"," Spell"," ","  Druid",1," ","  "));
		SoU.add(new Minion("Vessina"," Legendary"," Minion"," General","  Shaman", 4 , 2 , 6    ));
		SoU.add(new Minion("Vilefiend"," Common"," Minion"," Demon","  Any", 2 , 2 , 2    ));
		SoU.add(new Minion("Vulpera Scoundrel"," Epic"," Minion"," General","  Any", 3 , 2 , 3    ));
		SoU.add(new Minion("Wasteland Assassin"," Common"," Minion"," General","  Any", 5 , 4 , 2    ));
		SoU.add(new Minion("Wasteland Scorpid"," Common"," Minion"," Beast","  Any", 7 , 3 , 9    ));
		SoU.add(new Minion("Weaponized Wasp"," Rare"," Minion"," Beast","  Shaman", 3 , 3 , 3    ));
		SoU.add(new Minion("Whirlkick Master"," Epic"," Minion"," General","  Rogue", 2 , 1 , 2    ));
		SoU.add(new Minion("Wild Bloodstinger"," Epic"," Minion"," Beast","  Hunter", 6 , 6 , 9    ));
		SoU.add(new Spell("Worthy Expedition"," Common"," Spell"," ","  Druid",1," ","  "));
		SoU.add(new Minion("Wrapped Golem"," Rare"," Minion"," General","  Any", 7 , 7 , 5    ));
		SoU.add(new Minion("Wretched Reclaimer"," Rare"," Minion"," General","  Priest", 3 , 3 , 3    ));
		SoU.add(new Minion("Zephrys the Great"," Legendary"," Minion"," Elemental","  Any", 2 , 3 , 2    ));
		return SoU;
	}

}
