package cardSets;

import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSettBP {

	public ArrayList<Card> tBPList() {
		ArrayList<Card> tBP = new ArrayList<Card>();
		/*
		tBP.add(new Spell("Academic Espionage"," Epic"," Spell"," ","  Rogue",4," ","  "));
		tBP.add(new Minion("Annoy-o-Module"," Rare"," Minion"," Mech","  Paladin", 4 , 2 , 4    ));
		tBP.add(new Minion("Arcane Dynamo"," Rare"," Minion"," General","  Any", 6 , 3 , 4    ));
		tBP.add(new Spell("Astral Rift"," Rare"," Spell"," ","  Mage",2," ","  "));
		tBP.add(new Minion("Astromancer"," Epic"," Minion"," General","  Mage", 7 , 5 , 5    ));
		tBP.add(new Minion("Augmented Elekk"," Epic"," Minion"," Beast","  Any", 3 , 3 , 4    ));
		tBP.add(new Spell("Beakered Lightning"," Common"," Spell"," ","  Shaman",0," ","  "));
		tBP.add(new Minion("Beryllium Nullifier"," Epic"," Minion"," Mech","  Warrior", 7 , 4 , 8    ));
		tBP.add(new Spell("Biology Project"," Common"," Spell"," ","  Druid",1," ","  "));
		tBP.add(new Minion("Blightnozzle Crawler"," Rare"," Minion"," Mech","  Rogue", 4 , 2 , 4    ));
		tBP.add(new Spell("Bomb Toss"," Common"," Spell"," ","  Hunter",2," ","  "));
		tBP.add(new Minion("Boommaster Flark"," Legendary"," Minion"," General","  Hunter", 7 , 5 , 5    ));
		tBP.add(new Minion("Brainstormer"," Common"," Minion"," General","  Any", 3 , 3 , 1    ));
		tBP.add(new Minion("Bronze Gatekeeper"," Common"," Minion"," Mech","  Any", 3 , 1 , 5    ));
		tBP.add(new Minion("Bull Dozer"," Common"," Minion"," Mech","  Any", 9 , 9 , 7    ));
		tBP.add(new Minion("Celestial Emissary"," Rare"," Minion"," Elemental","  Mage", 2 , 2 , 1    ));
		tBP.add(new Minion("Cloakscale Chemist"," Common"," Minion"," General","  Any", 1 , 1 , 2    ));
		tBP.add(new Spell("Cloning Device"," Common"," Spell"," ","  Priest",1," ","  "));
		tBP.add(new Minion("Coppertail Imposter"," Common"," Minion"," Mech","  Any", 4 , 4 , 4    ));
		tBP.add(new Minion("Cosmic Anomaly"," Common"," Minion"," Elemental","  Mage", 4 , 4 , 3    ));
		tBP.add(new Minion("Crazed Chemist"," Common"," Minion"," General","  Rogue", 5 , 4 , 4    ));
		tBP.add(new Minion("Crystallizer"," Epic"," Minion"," General","  Any", 1 , 1 , 3    ));
		tBP.add(new Minion("Crystalsmith Kangor"," Legendary"," Minion"," General","  Paladin", 2 , 1 , 2    ));
		tBP.add(new Spell("Crystology"," Rare"," Spell"," ","  Paladin",1," ","  "));
		tBP.add(new Spell("Cybertech Chip"," Rare"," Spell"," ","  Hunter",2," ","  "));
		tBP.add(new Minion("Damaged Stegotron"," Common"," Minion"," Mech","  Any", 6 , 5 , 12    ));
		tBP.add(new Minion("Dead Ringer"," Common"," Minion"," Mech","  Priest", 2 , 2 , 1    ));
		tBP.add(new Spell("Demonic Project"," Common"," Spell"," ","  Warlock",2," ","  "));
		tBP.add(new Minion("Dendrologist"," Rare"," Minion"," General","  Druid", 2 , 2 , 3    ));
		tBP.add(new Minion("Doubling Imp"," Common"," Minion"," Demon","  Warlock", 3 , 2 , 2    ));
		tBP.add(new Minion("Dr. Morrigan"," Legendary"," Minion"," General","  Warlock", 6 , 5 , 5    ));
		tBP.add(new Minion("Dreampetal Florist"," Epic"," Minion"," General","  Druid", 7 , 4 , 4    ));
		tBP.add(new Minion("Dyn-o-matic"," Rare"," Minion"," Mech","  Warrior", 5 , 3 , 4    ));
		tBP.add(new Minion("E.M.P. Operative"," Epic"," Minion"," General","  Any", 5 , 3 , 3    ));
		tBP.add(new Spell("Ectomancy"," Epic"," Spell"," ","  Warlock",6," ","  "));
		tBP.add(new Minion("Electra Stormsurge"," Legendary"," Minion"," Elemental","  Shaman", 3 , 3 , 3    ));
		tBP.add(new Minion("Electrowright"," Common"," Minion"," General","  Any", 3 , 3 , 3    ));
		tBP.add(new Spell("Elementary Reaction"," Common"," Spell"," ","  Shaman",2," ","  "));
		tBP.add(new Minion("Eternium Rover"," Common"," Minion"," Mech","  Warrior", 1 , 1 , 3    ));
		tBP.add(new Spell("Eureka!"," Rare"," Spell"," ","  Shaman",6," ","  "));
		tBP.add(new Minion("Explodinator"," Common"," Minion"," Mech","  Any", 4 , 3 , 2    ));
		tBP.add(new Spell("Extra Arms"," Rare"," Spell"," ","  Priest",3," ","  "));
		tBP.add(new Minion("Faithful Lumi"," Common"," Minion"," Mech","  Any", 1 , 1 , 1    ));
		tBP.add(new Minion("Fireworks Tech"," Rare"," Minion"," General","  Hunter", 2 , 2 , 1    ));
		tBP.add(new Spell("Flark's Boom-Zooka"," Legendary"," Spell"," ","  Hunter",7," ","  "));
		tBP.add(new Minion("Flobbidinous Floop"," Legendary"," Minion"," General","  Druid", 4 , 3 , 4    ));
		tBP.add(new Spell("Floop's Glorious Gloop"," Legendary"," Spell"," ","  Druid",1," ","  "));
		tBP.add(new Minion("Galvanizer"," Rare"," Minion"," Mech","  Any", 2 , 1 , 2    ));
		tBP.add(new Minion("Giggling Inventor"," Rare"," Minion"," General","  Any", 7 , 2 , 1    ));
		tBP.add(new Minion("Gloop Sprayer"," Common"," Minion"," General","  Druid", 7 , 4 , 4    ));
		tBP.add(new Minion("Glow-Tron"," Common"," Minion"," Mech","  Paladin", 1 , 1 , 3    ));
		tBP.add(new Minion("Glowstone Technician"," Epic"," Minion"," General","  Paladin", 5 , 3 , 4    ));
		tBP.add(new Minion("Goblin Bomb"," Common"," Minion"," Mech","  Any", 1 , 0 , 2    ));
		tBP.add(new Spell("Goblin Prank"," Epic"," Spell"," ","  Hunter",2," ","  "));
		tBP.add(new Minion("Harbinger Celestia"," Legendary"," Minion"," General","  Any", 4 , 5 , 6    ));
		tBP.add(new Minion("Holomancer"," Epic"," Minion"," General","  Any", 5 , 3 , 3    ));
		tBP.add(new Spell("Juicy Psychmelon"," Epic"," Spell"," ","  Druid",4," ","  "));
		tBP.add(new Minion("Kaboom Bot"," Common"," Minion"," Mech","  Any", 3 , 2 , 2    ));
		tBP.add(new Spell("Kangor's Endless Army"," Legendary"," Spell"," ","  Paladin",7," ","  "));
		tBP.add(new Minion("Lab Recruiter"," Common"," Minion"," General","  Rogue", 2 , 3 , 2    ));
		tBP.add(new Spell("Landscaping"," Common"," Spell"," ","  Druid",3," ","  "));
		tBP.add(new Minion("Loose Specimen"," Epic"," Minion"," Beast","  Any", 5 , 6 , 6    ));
		tBP.add(new Spell("Luna's Pocket Galaxy"," Legendary"," Spell"," ","  Mage",7," ","  "));
		tBP.add(new Minion("Mecha'thun"," Legendary"," Minion"," Mech","  Any", 10 , 10 , 10    ));
		tBP.add(new Minion("Mechanical Whelp"," Rare"," Minion"," Mech","  Any", 6 , 2 , 2    ));
		tBP.add(new Minion("Mechano-Egg"," Common"," Minion"," Mech","  Paladin", 5 , 0 , 5    ));
		tBP.add(new Minion("Mecharoo"," Common"," Minion"," Mech","  Any", 1 , 1 , 1    ));
		tBP.add(new Minion("Menacing Nimbus"," Common"," Minion"," Elemental","  Shaman", 2 , 2 , 2    ));
		tBP.add(new Minion("Meteorologist"," Rare"," Minion"," General","  Mage", 6 , 3 , 3    ));
		tBP.add(new Minion("Microtech Controller"," Common"," Minion"," General","  Any", 3 , 2 , 1    ));
		tBP.add(new Minion("Missile Launcher"," Rare"," Minion"," Mech","  Any", 6 , 4 , 4    ));
		tBP.add(new Minion("Mulchmuncher"," Rare"," Minion"," Mech","  Druid", 9 , 8 , 8    ));
		tBP.add(new Minion("Myra Rotspring"," Legendary"," Minion"," General","  Rogue", 5 , 4 , 2    ));
		tBP.add(new Spell("Myra's Unstable Element"," Legendary"," Spell"," ","  Rogue",5," ","  "));
		tBP.add(new Minion("Necrium Blade"," Rare"," Weapon"," ","  Rogue", 3 , 3 , 2    ));
		tBP.add(new Spell("Necrium Vial"," Epic"," Spell"," ","  Rogue",5," ","  "));
		tBP.add(new Minion("Necromechanic"," Epic"," Minion"," General","  Hunter", 4 , 3 , 6    ));
		tBP.add(new Minion("Nethersoul Buster"," Rare"," Minion"," Demon","  Warlock", 3 , 1 , 5    ));
		tBP.add(new Minion("Omega Agent"," Epic"," Minion"," General","  Warlock", 5 , 4 , 5    ));
		tBP.add(new Spell("Omega Assembly"," Rare"," Spell"," ","  Warrior",1," ","  "));
		tBP.add(new Minion("Omega Defender"," Epic"," Minion"," General","  Any", 4 , 2 , 6    ));
		tBP.add(new Minion("Omega Medic"," Rare"," Minion"," General","  Priest", 3 , 3 , 4    ));
		tBP.add(new Minion("Omega Mind"," Epic"," Minion"," General","  Shaman", 2 , 2 , 3    ));
		tBP.add(new Minion("Piloted Reaper"," Common"," Minion"," Mech","  Any", 4 , 3 , 2    ));
		tBP.add(new Minion("Pogo-Hopper"," Rare"," Minion"," Mech","  Rogue", 1 , 1 , 1    ));
		tBP.add(new Spell("Power Word: Replicate"," Epic"," Spell"," ","  Priest",5," ","  "));
		tBP.add(new Spell("Prismatic Lens"," Epic"," Spell"," ","  Paladin",4," ","  "));
		tBP.add(new Minion("Reckless Experimenter"," Epic"," Minion"," General","  Priest", 5 , 4 , 6    ));
		tBP.add(new Minion("Replicating Menace"," Rare"," Minion"," Mech","  Any", 4 , 3 , 1    ));
		tBP.add(new Spell("Research Project"," Common"," Spell"," ","  Mage",2," ","  "));
		tBP.add(new Spell("Rocket Boots"," Common"," Spell"," ","  Warrior",2," ","  "));
		tBP.add(new Minion("Rusty Recycler"," Common"," Minion"," Mech","  Any", 5 , 2 , 6    ));
		tBP.add(new Minion("Seaforium Bomber"," Epic"," Minion"," General","  Any", 5 , 5 , 5    ));
		tBP.add(new Spell("Secret Plan"," Common"," Spell"," ","  Hunter",1," ","  "));
		tBP.add(new Minion("Security Rover"," Rare"," Minion"," Mech","  Warrior", 6 , 2 , 6    ));
		tBP.add(new Spell("Shooting Star"," Common"," Spell"," ","  Mage",1," ","  "));
		tBP.add(new Spell("Shrink Ray"," Rare"," Spell"," ","  Paladin",5," ","  "));
		tBP.add(new Minion("Skaterbot"," Common"," Minion"," Mech","  Any", 1 , 1 , 1    ));
		tBP.add(new Minion("SN1P-SN4P"," Legendary"," Minion"," Mech","  Any", 3 , 2 , 3    ));
		tBP.add(new Spell("Soul Infusion"," Rare"," Spell"," ","  Warlock",1," ","  "));
		tBP.add(new Minion("Spark Drill"," Rare"," Minion"," Mech","  Any", 6 , 5 , 1    ));
		tBP.add(new Minion("Spark Engine"," Rare"," Minion"," Mech","  Any", 2 , 2 , 1    ));
		tBP.add(new Minion("Spider Bomb"," Rare"," Minion"," Mech","  Hunter", 3 , 2 , 2    ));
		tBP.add(new Spell("Spirit Bomb"," Common"," Spell"," ","  Warlock",1," ","  "));
		tBP.add(new Minion("Spring Rocket"," Common"," Minion"," Mech","  Any", 3 , 2 , 1    ));
		tBP.add(new Minion("Star Aligner"," Epic"," Minion"," General","  Any", 7 , 7 , 7    ));
		tBP.add(new Minion("Stargazer Luna"," Legendary"," Minion"," General","  Mage", 3 , 2 , 4    ));
		tBP.add(new Minion("Steel Rager"," Common"," Minion"," Mech","  Any", 4 , 5 , 1    ));
		tBP.add(new Minion("Storm Chaser"," Rare"," Minion"," Elemental","  Shaman", 4 , 3 , 4    ));
		tBP.add(new Minion("Subject 9"," Legendary"," Minion"," Beast","  Any", 5 , 4 , 4    ));
		tBP.add(new Minion("Supercollider"," Epic"," Weapon"," ","  Warrior", 5 , 1 , 3    ));
		tBP.add(new Minion("Tending Tauren"," Rare"," Minion"," General","  Druid", 6 , 3 , 4    ));
		tBP.add(new Minion("Test Subject"," Rare"," Minion"," General","  Priest", 1 , 0 , 2    ));
		tBP.add(new Spell("The Boomship"," Legendary"," Spell"," ","  Warrior",9," ","  "));
		tBP.add(new Spell("The Soularium"," Legendary"," Spell"," ","  Warlock",1," ","  "));
		tBP.add(new Spell("The Storm Bringer"," Legendary"," Spell"," ","  Shaman",6," ","  "));
		tBP.add(new Minion("Thunderhead"," Epic"," Minion"," Elemental","  Shaman", 4 , 3 , 6    ));
		tBP.add(new Spell("Topsy Turvy"," Common"," Spell"," ","  Priest",0," ","  "));
		tBP.add(new Minion("Toxicologist"," Common"," Minion"," General","  Any", 2 , 2 , 2    ));
		tBP.add(new Spell("Unexpected Results"," Epic"," Spell"," ","  Mage",3," ","  "));
		tBP.add(new Minion("Unpowered Mauler"," Rare"," Minion"," Mech","  Any", 2 , 2 , 4    ));
		tBP.add(new Minion("Upgradeable Framebot"," Common"," Minion"," Mech","  Any", 2 , 1 , 5    ));
		tBP.add(new Minion("Venomizer"," Common"," Minion"," Mech","  Hunter", 2 , 2 , 2    ));
		tBP.add(new Spell("Violet Haze"," Common"," Spell"," ","  Rogue",2," ","  "));
		tBP.add(new Minion("Void Analyst"," Rare"," Minion"," Demon","  Warlock", 2 , 2 , 2    ));
		tBP.add(new Spell("Voltaic Burst"," Rare"," Spell"," ","  Shaman",1," ","  "));
		tBP.add(new Minion("Wargear"," Common"," Minion"," Mech","  Any", 5 , 5 , 5    ));
		tBP.add(new Minion("Weaponized Piñata"," Epic"," Minion"," Mech","  Any", 4 , 4 , 3    ));
		tBP.add(new Spell("Weapons Project"," Common"," Spell"," ","  Warrior",2," ","  "));
		tBP.add(new Minion("Whirliglider"," Common"," Minion"," General","  Any", 2 , 2 , 1    ));
		tBP.add(new Minion("Whizbang the Wonderful"," Legendary"," Minion"," General","  Any", 4 , 4 , 5    ));
		tBP.add(new Spell("Zerek's Cloning Gallery"," Legendary"," Spell"," ","  Priest",9," ","  "));
		tBP.add(new Minion("Zerek, Master Cloner"," Legendary"," Minion"," General","  Priest", 6 , 5 , 5    ));
		tBP.add(new Minion("Zilliax"," Legendary"," Minion"," Mech","  Any", 5 , 3 , 2    ));
		*/
		tBP.add(new Spell("Academic Espionage"," Epic"," Spell"," ","  Rogue",4," ","  "));
		tBP.add(new Minion("Annoy-o-Module"," Rare"," Minion"," Mech","  Paladin", 4 , 2 , 4    ));
		tBP.add(new Minion("Arcane Dynamo"," Rare"," Minion"," General","  Any", 6 , 3 , 4    ));
		tBP.add(new Spell("Astral Rift"," Rare"," Spell"," ","  Mage",2," ","  "));
		tBP.add(new Minion("Astromancer"," Epic"," Minion"," General","  Mage", 7 , 5 , 5    ));
		tBP.add(new Minion("Augmented Elekk"," Epic"," Minion"," Beast","  Any", 3 , 3 , 4    ));
		tBP.add(new Spell("Beakered Lightning"," Common"," Spell"," ","  Shaman",0," ","  "));
		tBP.add(new Minion("Beryllium Nullifier"," Epic"," Minion"," Mech","  Warrior", 7 , 4 , 8    ));
		tBP.add(new Spell("Biology Project"," Common"," Spell"," ","  Druid",1," ","  "));
		tBP.add(new Minion("Blightnozzle Crawler"," Rare"," Minion"," Mech","  Rogue", 4 , 2 , 4    ));
		tBP.add(new Spell("Bomb Toss"," Common"," Spell"," ","  Hunter",2," ","  "));
		tBP.add(new Minion("Boommaster Flark"," Legendary"," Minion"," General","  Hunter", 7 , 5 , 5    ));
		tBP.add(new Minion("Brainstormer"," Common"," Minion"," General","  Any", 3 , 3 , 1    ));
		tBP.add(new Minion("Bronze Gatekeeper"," Common"," Minion"," Mech","  Any", 3 , 1 , 5    ));
		tBP.add(new Minion("Bull Dozer"," Common"," Minion"," Mech","  Any", 9 , 9 , 7    ));
		tBP.add(new Minion("Celestial Emissary"," Rare"," Minion"," Elemental","  Mage", 2 , 2 , 1    ));
		tBP.add(new Minion("Cloakscale Chemist"," Common"," Minion"," General","  Any", 1 , 1 , 2    ));
		tBP.add(new Spell("Cloning Device"," Common"," Spell"," ","  Priest",1," ","  "));
		tBP.add(new Minion("Coppertail Imposter"," Common"," Minion"," Mech","  Any", 4 , 4 , 4    ));
		tBP.add(new Minion("Cosmic Anomaly"," Common"," Minion"," Elemental","  Mage", 4 , 4 , 3    ));
		tBP.add(new Minion("Crazed Chemist"," Common"," Minion"," General","  Rogue", 5 , 4 , 4    ));
		tBP.add(new Minion("Crystallizer"," Epic"," Minion"," General","  Any", 1 , 1 , 3    ));
		tBP.add(new Minion("Crystalsmith Kangor"," Legendary"," Minion"," General","  Paladin", 2 , 1 , 2    ));
		tBP.add(new Spell("Crystology"," Rare"," Spell"," ","  Paladin",1," ","  "));
		tBP.add(new Spell("Cybertech Chip"," Rare"," Spell"," ","  Hunter",2," ","  "));
		tBP.add(new Minion("Damaged Stegotron"," Common"," Minion"," Mech","  Any", 6 , 5 , 12    ));
		tBP.add(new Minion("Dead Ringer"," Common"," Minion"," Mech","  Priest", 2 , 2 , 1    ));
		tBP.add(new Spell("Demonic Project"," Common"," Spell"," ","  Warlock",2," ","  "));
		tBP.add(new Minion("Dendrologist"," Rare"," Minion"," General","  Druid", 2 , 2 , 3    ));
		tBP.add(new Minion("Doubling Imp"," Common"," Minion"," Demon","  Warlock", 3 , 2 , 2    ));
		tBP.add(new Minion("Dr. Morrigan"," Legendary"," Minion"," General","  Warlock", 6 , 5 , 5    ));
		tBP.add(new Minion("Dreampetal Florist"," Epic"," Minion"," General","  Druid", 7 , 4 , 4    ));
		tBP.add(new Minion("Dyn-o-matic"," Rare"," Minion"," Mech","  Warrior", 5 , 3 , 4    ));
		tBP.add(new Minion("E.M.P. Operative"," Epic"," Minion"," General","  Any", 5 , 3 , 3    ));
		tBP.add(new Spell("Ectomancy"," Epic"," Spell"," ","  Warlock",6," ","  "));
		tBP.add(new Minion("Electra Stormsurge"," Legendary"," Minion"," Elemental","  Shaman", 3 , 3 , 3    ));
		tBP.add(new Minion("Electrowright"," Common"," Minion"," General","  Any", 3 , 3 , 3    ));
		tBP.add(new Spell("Elementary Reaction"," Common"," Spell"," ","  Shaman",2," ","  "));
		tBP.add(new Minion("Eternium Rover"," Common"," Minion"," Mech","  Warrior", 1 , 1 , 3    ));
		tBP.add(new Spell("Eureka!"," Rare"," Spell"," ","  Shaman",6," ","  "));
		tBP.add(new Minion("Explodinator"," Common"," Minion"," Mech","  Any", 4 , 3 , 2    ));
		tBP.add(new Spell("Extra Arms"," Rare"," Spell"," ","  Priest",3," ","  "));
		tBP.add(new Minion("Faithful Lumi"," Common"," Minion"," Mech","  Any", 1 , 1 , 1    ));
		tBP.add(new Minion("Fireworks Tech"," Rare"," Minion"," General","  Hunter", 2 , 2 , 1    ));
		tBP.add(new Spell("Flark's Boom-Zooka"," Legendary"," Spell"," ","  Hunter",7," ","  "));
		tBP.add(new Minion("Flobbidinous Floop"," Legendary"," Minion"," General","  Druid", 4 , 3 , 4    ));
		tBP.add(new Spell("Floop's Glorious Gloop"," Legendary"," Spell"," ","  Druid",1," ","  "));
		tBP.add(new Minion("Galvanizer"," Rare"," Minion"," Mech","  Any", 2 , 1 , 2    ));
		tBP.add(new Minion("Giggling Inventor"," Rare"," Minion"," General","  Any", 7 , 2 , 1    ));
		tBP.add(new Minion("Gloop Sprayer"," Common"," Minion"," General","  Druid", 7 , 4 , 4    ));
		tBP.add(new Minion("Glow-Tron"," Common"," Minion"," Mech","  Paladin", 1 , 1 , 3    ));
		tBP.add(new Minion("Glowstone Technician"," Epic"," Minion"," General","  Paladin", 5 , 3 , 4    ));
		tBP.add(new Minion("Goblin Bomb"," Common"," Minion"," Mech","  Any", 1 , 0 , 2    ));
		tBP.add(new Spell("Goblin Prank"," Epic"," Spell"," ","  Hunter",2," ","  "));
		tBP.add(new Minion("Harbinger Celestia"," Legendary"," Minion"," General","  Any", 4 , 5 , 6    ));
		tBP.add(new Minion("Holomancer"," Epic"," Minion"," General","  Any", 5 , 3 , 3    ));
		tBP.add(new Spell("Juicy Psychmelon"," Epic"," Spell"," ","  Druid",4," ","  "));
		tBP.add(new Minion("Kaboom Bot"," Common"," Minion"," Mech","  Any", 3 , 2 , 2    ));
		tBP.add(new Spell("Kangor's Endless Army"," Legendary"," Spell"," ","  Paladin",7," ","  "));
		tBP.add(new Minion("Lab Recruiter"," Common"," Minion"," General","  Rogue", 2 , 3 , 2    ));
		tBP.add(new Spell("Landscaping"," Common"," Spell"," ","  Druid",3," ","  "));
		tBP.add(new Minion("Loose Specimen"," Epic"," Minion"," Beast","  Any", 5 , 6 , 6    ));
		tBP.add(new Spell("Luna's Pocket Galaxy"," Legendary"," Spell"," ","  Mage",7," ","  "));
		tBP.add(new Minion("Mecha'thun"," Legendary"," Minion"," Mech","  Any", 10 , 10 , 10    ));
		tBP.add(new Minion("Mechanical Whelp"," Rare"," Minion"," Mech","  Any", 6 , 2 , 2    ));
		tBP.add(new Minion("Mechano-Egg"," Common"," Minion"," Mech","  Paladin", 5 , 0 , 5    ));
		tBP.add(new Minion("Mecharoo"," Common"," Minion"," Mech","  Any", 1 , 1 , 1    ));
		tBP.add(new Minion("Menacing Nimbus"," Common"," Minion"," Elemental","  Shaman", 2 , 2 , 2    ));
		tBP.add(new Minion("Meteorologist"," Rare"," Minion"," General","  Mage", 6 , 3 , 3    ));
		tBP.add(new Minion("Microtech Controller"," Common"," Minion"," General","  Any", 3 , 2 , 1    ));
		tBP.add(new Minion("Missile Launcher"," Rare"," Minion"," Mech","  Any", 6 , 4 , 4    ));
		tBP.add(new Minion("Mulchmuncher"," Rare"," Minion"," Mech","  Druid", 9 , 8 , 8    ));
		tBP.add(new Minion("Myra Rotspring"," Legendary"," Minion"," General","  Rogue", 5 , 4 , 2    ));
		tBP.add(new Spell("Myra's Unstable Element"," Legendary"," Spell"," ","  Rogue",5," ","  "));
		tBP.add(new Minion("Necrium Blade"," Rare"," Weapon"," ","  Rogue", 3 , 3 , 2    ));
		tBP.add(new Spell("Necrium Vial"," Epic"," Spell"," ","  Rogue",5," ","  "));
		tBP.add(new Minion("Necromechanic"," Epic"," Minion"," General","  Hunter", 4 , 3 , 6    ));
		tBP.add(new Minion("Nethersoul Buster"," Rare"," Minion"," Demon","  Warlock", 3 , 1 , 5    ));
		tBP.add(new Minion("Omega Agent"," Epic"," Minion"," General","  Warlock", 5 , 4 , 5    ));
		tBP.add(new Spell("Omega Assembly"," Rare"," Spell"," ","  Warrior",1," ","  "));
		tBP.add(new Minion("Omega Defender"," Epic"," Minion"," General","  Any", 4 , 2 , 6    ));
		tBP.add(new Minion("Omega Medic"," Rare"," Minion"," General","  Priest", 3 , 3 , 4    ));
		tBP.add(new Minion("Omega Mind"," Epic"," Minion"," General","  Shaman", 2 , 2 , 3    ));
		tBP.add(new Minion("Piloted Reaper"," Common"," Minion"," Mech","  Any", 4 , 3 , 2    ));
		tBP.add(new Minion("Pogo-Hopper"," Rare"," Minion"," Mech","  Rogue", 1 , 1 , 1    ));
		tBP.add(new Spell("Power Word: Replicate"," Epic"," Spell"," ","  Priest",5," ","  "));
		tBP.add(new Spell("Prismatic Lens"," Epic"," Spell"," ","  Paladin",4," ","  "));
		tBP.add(new Minion("Reckless Experimenter"," Epic"," Minion"," General","  Priest", 5 , 4 , 6    ));
		tBP.add(new Minion("Replicating Menace"," Rare"," Minion"," Mech","  Any", 4 , 3 , 1    ));
		tBP.add(new Spell("Research Project"," Common"," Spell"," ","  Mage",2," ","  "));
		tBP.add(new Spell("Rocket Boots"," Common"," Spell"," ","  Warrior",2," ","  "));
		tBP.add(new Minion("Rusty Recycler"," Common"," Minion"," Mech","  Any", 5 , 2 , 6    ));
		tBP.add(new Minion("Seaforium Bomber"," Epic"," Minion"," General","  Any", 5 , 5 , 5    ));
		tBP.add(new Spell("Secret Plan"," Common"," Spell"," ","  Hunter",1," ","  "));
		tBP.add(new Minion("Security Rover"," Rare"," Minion"," Mech","  Warrior", 6 , 2 , 6    ));
		tBP.add(new Spell("Shooting Star"," Common"," Spell"," ","  Mage",1," ","  "));
		tBP.add(new Spell("Shrink Ray"," Rare"," Spell"," ","  Paladin",5," ","  "));
		tBP.add(new Minion("Skaterbot"," Common"," Minion"," Mech","  Any", 1 , 1 , 1    ));
		tBP.add(new Minion("SN1P-SN4P"," Legendary"," Minion"," Mech","  Any", 3 , 2 , 3    ));
		tBP.add(new Spell("Soul Infusion"," Rare"," Spell"," ","  Warlock",1," ","  "));
		tBP.add(new Minion("Spark Drill"," Rare"," Minion"," Mech","  Any", 6 , 5 , 1    ));
		tBP.add(new Minion("Spark Engine"," Rare"," Minion"," Mech","  Any", 2 , 2 , 1    ));
		tBP.add(new Minion("Spider Bomb"," Rare"," Minion"," Mech","  Hunter", 3 , 2 , 2    ));
		tBP.add(new Spell("Spirit Bomb"," Common"," Spell"," ","  Warlock",1," ","  "));
		tBP.add(new Minion("Spring Rocket"," Common"," Minion"," Mech","  Any", 3 , 2 , 1    ));
		tBP.add(new Minion("Star Aligner"," Epic"," Minion"," General","  Any", 7 , 7 , 7    ));
		tBP.add(new Minion("Stargazer Luna"," Legendary"," Minion"," General","  Mage", 3 , 2 , 4    ));
		tBP.add(new Minion("Steel Rager"," Common"," Minion"," Mech","  Any", 4 , 5 , 1    ));
		tBP.add(new Minion("Storm Chaser"," Rare"," Minion"," Elemental","  Shaman", 4 , 3 , 4    ));
		tBP.add(new Minion("Subject 9"," Legendary"," Minion"," Beast","  Any", 5 , 4 , 4    ));
		tBP.add(new Minion("Supercollider"," Epic"," Weapon"," ","  Warrior", 5 , 1 , 3    ));
		tBP.add(new Minion("Tending Tauren"," Rare"," Minion"," General","  Druid", 6 , 3 , 4    ));
		tBP.add(new Minion("Test Subject"," Rare"," Minion"," General","  Priest", 1 , 0 , 2    ));
		tBP.add(new Spell("The Boomship"," Legendary"," Spell"," ","  Warrior",9," ","  "));
		tBP.add(new Spell("The Soularium"," Legendary"," Spell"," ","  Warlock",1," ","  "));
		tBP.add(new Spell("The Storm Bringer"," Legendary"," Spell"," ","  Shaman",6," ","  "));
		tBP.add(new Minion("Thunderhead"," Epic"," Minion"," Elemental","  Shaman", 4 , 3 , 6    ));
		tBP.add(new Spell("Topsy Turvy"," Common"," Spell"," ","  Priest",0," ","  "));
		tBP.add(new Minion("Toxicologist"," Common"," Minion"," General","  Any", 2 , 2 , 2    ));
		tBP.add(new Spell("Unexpected Results"," Epic"," Spell"," ","  Mage",3," ","  "));
		tBP.add(new Minion("Unpowered Mauler"," Rare"," Minion"," Mech","  Any", 2 , 2 , 4    ));
		tBP.add(new Minion("Upgradeable Framebot"," Common"," Minion"," Mech","  Any", 2 , 1 , 5    ));
		tBP.add(new Minion("Venomizer"," Common"," Minion"," Mech","  Hunter", 2 , 2 , 2    ));
		tBP.add(new Spell("Violet Haze"," Common"," Spell"," ","  Rogue",2," ","  "));
		tBP.add(new Minion("Void Analyst"," Rare"," Minion"," Demon","  Warlock", 2 , 2 , 2    ));
		tBP.add(new Spell("Voltaic Burst"," Rare"," Spell"," ","  Shaman",1," ","  "));
		tBP.add(new Minion("Wargear"," Common"," Minion"," Mech","  Any", 5 , 5 , 5    ));
		tBP.add(new Minion("Weaponized Piñata"," Epic"," Minion"," Mech","  Any", 4 , 4 , 3    ));
		tBP.add(new Spell("Weapons Project"," Common"," Spell"," ","  Warrior",2," ","  "));
		tBP.add(new Minion("Weapons Project"," Common"," Minion"," ","  Warrior",2 , 2, 1));
		tBP.add(new Minion("Whirliglider"," Common"," Minion"," General","  Any", 2 , 2 , 1    ));
		tBP.add(new Minion("Whizbang the Wonderful"," Legendary"," Minion"," General","  Any", 4 , 4 , 5    ));
		tBP.add(new Spell("Zerek's Cloning Gallery"," Legendary"," Spell"," ","  Priest",9," ","  "));
		tBP.add(new Minion("Zerek, Master Cloner"," Legendary"," Minion"," General","  Priest", 6 , 5 , 5    ));
		tBP.add(new Minion("Zilliax"," Legendary"," Minion"," Mech","  Any", 5 , 3 , 2    ));
 		return tBP;
	}

}
