package cardSets;
import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

/*
 * ArrayList of Cards from Classic Set
 */
public class CardSetClassic {

	public ArrayList<Card> classicList() {
		ArrayList<Card> classic = new ArrayList<Card>();
		classic.add(new Minion("Abominaataion", " Rare", " Minion", " General", "  Any", 5, 4, 4));
		classic.add(new Minion("Abusive Sergeant", " Common", " Minion", " General", "  Any", 1, 1, 1));
		classic.add(new Minion("Acolyte of Pain", " Common", " Minion", " General", "  Any", 3, 1, 3));
		classic.add(new Minion("Al'Akir the Windlord", " Legendary", " Minion", " Elemental", "  Shaman", 8, 3, 5));
		classic.add(new Minion("Alarm-o-Bot", " Rare", " Minion", " Mech", "  Any", 3, 0, 3));
		classic.add(new Minion("Aldor Peacekeeper", " Rare", " Minion", " General", "  Paladin", 3, 3, 3));
		classic.add(new Minion("Alexstrasza", " Legendary", " Minion", " Dragon", "  Any", 9, 8, 8));
		classic.add(new Minion("Amani Berserker", " Common", " Minion", " General", "  Any", 2, 2, 3));
		classic.add(new Spell("Ancestral Spirit", " Rare", " Spell", " ", "  Shaman", 2, " ", "  "));
		classic.add(new Minion("Ancient Brewmaster", " Common", " Minion", " General", "  Any", 4, 5, 4));
		classic.add(new Minion("Ancient Mage", " Rare", " Minion", " General", "  Any", 4, 2, 5));
		classic.add(new Minion("Ancient of Lore", " Epic", " Minion", " General", "  Druid", 7, 5, 5));
		classic.add(new Minion("Ancient of War", " Epic", " Minion", " General", "  Druid", 7, 5, 5));
		classic.add(new Minion("Ancient Watcher", " Rare", " Minion", " General", "  Any", 2, 4, 5));
		classic.add(new Minion("Angry Chicken", " Rare", " Minion", " Beast", "  Any", 1, 1, 1));
		classic.add(new Minion("Arathi Weaponsmith", " Common", " Minion", " General", "  Warrior", 4, 3, 3));
		classic.add(new Minion("Arcane Devourer", " Rare", " Minion", " Elemental", "  Any", 8, 5, 5));
		classic.add(new Minion("Arcane Golem", " Rare", " Minion", " General", "  Any", 3, 4, 4));
		classic.add(new Minion("Archmage Antonidas", " Legendary", " Minion", " General", "  Mage", 7, 5, 7));
		classic.add(new Minion("Argent Commander", " Rare", " Minion", " General", "  Any", 6, 4, 2));
		classic.add(new Minion("Argent Protector", " Common", " Minion", " General", "  Paladin", 2, 2, 2));
		classic.add(new Minion("Argent Squire", " Common", " Minion", " General", "  Any", 1, 1, 1));
		classic.add(new Minion("Armorsmith", " Rare", " Minion", " General", "  Warrior", 2, 1, 4));
		classic.add(new Minion("Auchenai Soulpriest", " Rare", " Minion", " General", "  Priest", 4, 3, 5));
		classic.add(new Spell("Avenging Wrath", " Epic", " Spell", " ", "  Paladin", 6, " ", "  "));
		classic.add(new Spell("Bane of Doom", " Epic", " Spell", " ", "  Warlock", 5, " ", "  "));
		classic.add(new Minion("Baron Geddon", " Legendary", " Minion", " Elemental", "  Any", 7, 7, 5));
		classic.add(new Minion("Barrens Stablehand", " Epic", " Minion", " General", "  Any", 7, 4, 4));
		classic.add(new Spell("Battle Rage", " Common", " Spell", " ", "  Warrior", 2, " ", "  "));
		classic.add(new Spell("Bestial Wrath", " Epic", " Spell", " ", "  Hunter", 1, " ", "  "));
		classic.add(new Spell("Betrayal", " Common", " Spell", " ", "  Rogue", 2, " ", "  "));
		classic.add(new Minion("Big Game Hunter", " Epic", " Minion", " General", "  Any", 5, 4, 2));
		classic.add(new Spell("Bite", " Rare", " Spell", " ", "  Druid", 4, " ", "  "));
		classic.add(new Spell("Blade Flurry", " Rare", " Spell", " ", "  Rogue", 4, " ", "  "));
		classic.add(new Spell("Blessed Champion", " Rare", " Spell", " ", "  Paladin", 5, " ", "  "));
		classic.add(new Spell("Blessing of Wisdom", " Common", " Spell", " ", "  Paladin", 1, " ", "  "));
		classic.add(new Spell("Blizzard", " Rare", " Spell", " ", "  Mage", 6, " ", "  "));
		classic.add(new Minion("Blood Imp", " Common", " Minion", " Demon", "  Warlock", 1, 0, 1));
		classic.add(new Minion("Blood Knight", " Epic", " Minion", " General", "  Any", 3, 3, 3));
		classic.add(new Minion("Bloodmage Thalnos", " Legendary", " Minion", " General", "  Any", 2, 1, 1));
		classic.add(new Minion("Bloodsail Corsair", " Rare", " Minion", " Pirate", "  Any", 1, 1, 2));
		classic.add(new Minion("Bloodsail Raider", " Common", " Minion", " Pirate", "  Any", 2, 2, 3));
		classic.add(new Spell("Brawl", " Epic", " Spell", " ", "  Warrior", 5, " ", "  "));
		classic.add(new Minion("Brightwing", " Legendary", " Minion", " Dragon", "  Any", 3, 3, 2));
		classic.add(new Minion("Cabal Shadow Priest", " Epic", " Minion", " General", "  Priest", 6, 4, 5));
		classic.add(new Minion("Cairne Bloodhoof", " Legendary", " Minion", " General", "  Any", 6, 4, 5));
		classic.add(new Spell("Call of the Void", " Common", " Spell", " ", "  Warlock", 1, " ", "  "));
		classic.add(new Minion("Captain Greenskin", " Legendary", " Minion", " Pirate", "  Any", 5, 5, 4));
		classic.add(new Minion("Cenarius", " Legendary", " Minion", " General", "  Druid", 9, 5, 8));
		classic.add(new Spell("Circle of Healing", " Common", " Spell", " ", "  Priest", 0, " ", "  "));
		classic.add(new Spell("Cold Blood", " Common", " Spell", " ", "  Rogue", 2, " ", "  "));
		classic.add(new Minion("Coldlight Seer", " Rare", " Minion", " Murloc", "  Any", 3, 2, 3));
		classic.add(new Spell("Commanding Shout", " Rare", " Spell", " ", "  Warrior", 2, " ", "  "));
		classic.add(new Spell("Cone of Cold", " Common", " Spell", " ", "  Mage", 4, " ", "  "));
		classic.add(new Spell("Counterspell", " Rare", " Spell", " ", "  Mage", 3, " ", "  "));
		classic.add(new Minion("Crazed Alchemist", " Rare", " Minion", " General", "  Any", 2, 2, 2));
		classic.add(new Minion("Cruel Taskmaster", " Common", " Minion", " General", "  Warrior", 2, 2, 2));
		classic.add(new Minion("Cult Master", " Common", " Minion", " General", "  Any", 4, 4, 2));
		classic.add(new Minion("Dark Iron Dwarf", " Common", " Minion", " General", "  Any", 4, 4, 4));
		classic.add(new Spell("Deadly Shot", " Common", " Spell", " ", "  Hunter", 3, " ", "  "));
		classic.add(new Minion("Deathwing", " Legendary", " Minion", " Dragon", "  Any", 10, 12, 12));
		classic.add(new Minion("Defender of Argus", " Rare", " Minion", " General", "  Any", 4, 2, 3));
		classic.add(new Minion("Defias Ringleader", " Common", " Minion", " General", "  Rogue", 2, 2, 2));
		classic.add(new Minion("Demolisher", " Rare", " Minion", " Mech", "  Any", 3, 1, 4));
		classic.add(new Spell("Demonfire", " Common", " Spell", " ", "  Warlock", 2, " ", "  "));
		classic.add(new Minion("Dire Wolf Alpha", " Common", " Minion", " Beast", "  Any", 2, 2, 2));
		classic.add(new Minion("Doomhammer", " Epic", " Weapon", " ", "  Shaman", 5, 2, 8));
		classic.add(new Minion("Doomsayer", " Epic", " Minion", " General", "  Any", 2, 0, 7));
		classic.add(new Minion("Dread Corsair", " Common", " Minion", " Pirate", "  Any", 4, 3, 3));
		classic.add(new Minion("Druid of the Claw", " Common", " Minion", " General", "  Druid", 5, 4, 4));
		classic.add(new Minion("Dust Devil", " Common", " Minion", " Elemental", "  Shaman", 1, 3, 1));
		classic.add(new Minion("Eaglehorn Bow", " Rare", " Weapon", " ", "  Hunter", 3, 3, 2));
		classic.add(new Minion("Earth Elemental", " Epic", " Minion", " Elemental", "  Shaman", 5, 7, 8));
		classic.add(new Spell("Earth Shock", " Common", " Spell", " ", "  Shaman", 1, " ", "  "));
		classic.add(new Minion("Earthen Ring Farseer", " Common", " Minion", " General", "  Any", 3, 3, 3));
		classic.add(new Minion("Edwin VanCleef", " Legendary", " Minion", " General", "  Rogue", 3, 2, 2));
		classic.add(new Minion("Emperor Cobra", " Rare", " Minion", " Beast", "  Any", 3, 2, 3));
		classic.add(new Spell("Equality", " Rare", " Spell", " ", "  Paladin", 4, " ", "  "));
		classic.add(new Minion("Ethereal Arcanist", " Rare", " Minion", " General", "  Mage", 4, 3, 3));
		classic.add(new Spell("Eviscerate", " Common", " Spell", " ", "  Rogue", 2, " ", "  "));
		classic.add(new Spell("Explosive Shot", " Rare", " Spell", " ", "  Hunter", 5, " ", "  "));
		classic.add(new Spell("Explosive Trap", " Common", " Spell", " ", "  Hunter", 2, " ", "  "));
		classic.add(new Spell("Eye for an Eye", " Common", " Spell", " ", "  Paladin", 1, " ", "  "));
		classic.add(new Minion("Faceless Manipulator", " Epic", " Minion", " General", "  Any", 5, 3, 3));
		classic.add(new Minion("Faerie Dragon", " Common", " Minion", " Dragon", "  Any", 2, 3, 2));
		classic.add(new Spell("Far Sight", " Epic", " Spell", " ", "  Shaman", 3, " ", "  "));
		classic.add(new Minion("Felguard", " Rare", " Minion", " Demon", "  Warlock", 3, 3, 5));
		classic.add(new Minion("Fen Creeper", " Common", " Minion", " General", "  Any", 5, 3, 6));
		classic.add(new Spell("Feral Spirit", " Rare", " Spell", " ", "  Shaman", 3, " ", "  "));
		classic.add(new Minion("Flame Imp", " Common", " Minion", " Demon", "  Warlock", 1, 3, 2));
		classic.add(new Spell("Flare", " Rare", " Spell", " ", "  Hunter", 2, " ", "  "));
		classic.add(new Minion("Flesheating Ghoul", " Common", " Minion", " General", "  Any", 3, 2, 3));
		classic.add(new Spell("Force of Nature", " Epic", " Spell", " ", "  Druid", 5, " ", "  "));
		classic.add(new Spell("Forked Lightning", " Common", " Spell", " ", "  Shaman", 1, " ", "  "));
		classic.add(new Spell("Freezing Trap", " Common", " Spell", " ", "  Hunter", 2, " ", "  "));
		classic.add(new Minion("Frost Elemental", " Common", " Minion", " Elemental", "  Any", 6, 5, 5));
		classic.add(new Minion("Frothing Berserker", " Rare", " Minion", " General", "  Warrior", 3, 2, 4));
		classic.add(new Minion("Gadgetzan Auctioneer", " Rare", " Minion", " General", "  Any", 6, 4, 4));
		classic.add(new Spell("Gift of the Wild", " Common", " Spell", " ", "  Druid", 8, " ", "  "));
		classic.add(new Minion("Gladiator's Longbow", " Epic", " Weapon", " ", "  Hunter", 7, 5, 2));
		classic.add(new Minion("Gorehowl", " Epic", " Weapon", " ", "  Warrior", 7, 7, 1));
		classic.add(new Minion("Grommash Hellscream", " Legendary", " Minion", " General", "  Warrior", 8, 4, 9));
		classic.add(new Minion("Gruul", " Legendary", " Minion", " General", "  Any", 8, 7, 7));
		classic.add(new Minion("Harrison Jones", " Legendary", " Minion", " General", "  Any", 5, 5, 4));
		classic.add(new Minion("Harvest Golem", " Common", " Minion", " Mech", "  Any", 3, 2, 3));
		classic.add(new Spell("Headcrack", " Rare", " Spell", " ", "  Rogue", 3, " ", "  "));
		classic.add(new Minion("High Inquisitor Whitemane", " Legendary", " Minion", " General", "  Any", 7, 6, 8));
		classic.add(new Minion("Hogger", " Legendary", " Minion", " General", "  Any", 6, 4, 4));
		classic.add(new Spell("Holy Fire", " Rare", " Spell", " ", "  Priest", 6, " ", "  "));
		classic.add(new Spell("Holy Wrath", " Rare", " Spell", " ", "  Paladin", 5, " ", "  "));
		classic.add(new Minion("Hungry Crab", " Epic", " Minion", " Beast", "  Any", 1, 1, 2));
		classic.add(new Spell("Ice Barrier", " Common", " Spell", " ", "  Mage", 3, " ", "  "));
		classic.add(new Spell("Icicle", " Epic", " Spell", " ", "  Mage", 2, " ", "  "));
		classic.add(new Minion("Illidan Stormrage", " Legendary", " Minion", " Demon", "  Any", 6, 7, 5));
		classic.add(new Minion("Imp Master", " Rare", " Minion", " General", "  Any", 3, 1, 5));
		classic.add(new Minion("Injured Blademaster", " Rare", " Minion", " General", "  Any", 3, 4, 7));
		classic.add(new Spell("Inner Fire", " Common", " Spell", " ", "  Priest", 1, " ", "  "));
		classic.add(new Spell("Inner Rage", " Common", " Spell", " ", "  Warrior", 0, " ", "  "));
		classic.add(new Minion("Ironbeak Owl", " Common", " Minion", " Beast", "  Any", 3, 2, 1));
		classic.add(new Minion("Jungle Panther", " Common", " Minion", " Beast", "  Any", 3, 4, 2));
		classic.add(new Minion("Keeper of the Grove", " Rare", " Minion", " General", "  Druid", 4, 2, 2));
		classic.add(new Minion("Kidnapper", " Epic", " Minion", " General", "  Rogue", 6, 5, 3));
		classic.add(new Minion("King Krush", " Legendary", " Minion", " Beast", "  Hunter", 9, 8, 8));
		classic.add(new Minion("King Mukla", " Legendary", " Minion", " Beast", "  Any", 3, 5, 5));
		classic.add(new Minion("Kirin Tor Mage", " Rare", " Minion", " General", "  Mage", 3, 4, 3));
		classic.add(new Minion("Knife Juggler", " Rare", " Minion", " General", "  Any", 2, 2, 2));
		classic.add(new Spell("Lava Burst", " Rare", " Spell", " ", "  Shaman", 3, " ", "  "));
		classic.add(new Spell("Lay on Hands", " Epic", " Spell", " ", "  Paladin", 8, " ", "  "));
		classic.add(new Minion("Leeroy Jenkins", " Legendary", " Minion", " General", "  Any", 5, 6, 2));
		classic.add(new Minion("Leper Gnome", " Common", " Minion", " General", "  Any", 1, 1, 1));
		classic.add(new Spell("Lightning Bolt", " Common", " Spell", " ", "  Shaman", 1, " ", "  "));
		classic.add(new Spell("Lightning Storm", " Rare", " Spell", " ", "  Shaman", 3, " ", "  "));
		classic.add(new Minion("Lightspawn", " Common", " Minion", " Elemental", "  Priest", 4, 0, 5));
		classic.add(new Minion("Lightwarden", " Rare", " Minion", " General", "  Any", 1, 1, 2));
		classic.add(new Minion("Lightwell", " Rare", " Minion", " General", "  Priest", 2, 0, 5));
		classic.add(new Minion("Loot Hoarder", " Common", " Minion", " General", "  Any", 2, 2, 1));
		classic.add(new Minion("Lord Jaraxxus", " Legendary", " Minion", " Demon", "  Warlock", 9, 3, 15));
		classic.add(new Minion("Lorewalker Cho", " Legendary", " Minion", " General", "  Any", 2, 0, 4));
		classic.add(new Minion("Mad Bomber", " Common", " Minion", " General", "  Any", 2, 3, 2));
		classic.add(new Minion("Malygos", " Legendary", " Minion", " Dragon", "  Any", 9, 4, 12));
		classic.add(new Minion("Mana Addict", " Rare", " Minion", " General", "  Any", 2, 1, 3));
		classic.add(new Minion("Mana Tide Totem", " Rare", " Minion", " Totem", "  Shaman", 3, 0, 3));
		classic.add(new Minion("Mana Wraith", " Rare", " Minion", " General", "  Any", 2, 2, 2));
		classic.add(new Minion("Mana Wyrm", " Common", " Minion", " General", "  Mage", 2, 1, 3));
		classic.add(new Spell("Mark of Nature", " Common", " Spell", " ", "  Druid", 3, " ", "  "));
		classic.add(new Spell("Mass Dispel", " Rare", " Spell", " ", "  Priest", 4, " ", "  "));
		classic.add(new Minion("Master of Disguise", " Rare", " Minion", " General", "  Rogue", 4, 4, 4));
		classic.add(new Minion("Master Swordsmith", " Rare", " Minion", " General", "  Any", 2, 1, 3));
		classic.add(new Minion("Millhouse Manastorm", " Legendary", " Minion", " General", "  Any", 2, 4, 4));
		classic.add(new Minion("Mind Control Tech", " Rare", " Minion", " General", "  Any", 3, 3, 3));
		classic.add(new Spell("Mindgames", " Epic", " Spell", " ", "  Priest", 4, " ", "  "));
		classic.add(new Spell("Mirror Entity", " Common", " Spell", " ", "  Mage", 3, " ", "  "));
		classic.add(new Spell("Misdirection", " Rare", " Spell", " ", "  Hunter", 2, " ", "  "));
		classic.add(new Minion("Mogu'shan Warden", " Common", " Minion", " General", "  Any", 4, 1, 7));
		classic.add(new Spell("Mortal Strike", " Rare", " Spell", " ", "  Warrior", 4, " ", "  "));
		classic.add(new Minion("Mountain Giant", " Epic", " Minion", " Elemental", "  Any", 12, 8, 8));
		classic.add(new Minion("Murloc Tidecaller", " Rare", " Minion", " Murloc", "  Any", 1, 1, 2));
		classic.add(new Minion("Murloc Warleader", " Epic", " Minion", " Murloc", "  Any", 3, 3, 3));
		classic.add(new Minion("Nat Pagle", " Legendary", " Minion", " General", "  Any", 2, 0, 4));
		classic.add(new Spell("Noble Sacrifice", " Common", " Spell", " ", "  Paladin", 1, " ", "  "));
		classic.add(new Spell("Nourish", " Rare", " Spell", " ", "  Druid", 6, " ", "  "));
		classic.add(new Minion("Nozdormu", " Legendary", " Minion", " Dragon", "  Any", 9, 8, 8));
		classic.add(new Minion("Onyxia", " Legendary", " Minion", " Dragon", "  Any", 9, 8, 8));
		classic.add(new Minion("Patient Assassin", " Epic", " Minion", " General", "  Rogue", 2, 1, 1));
		classic.add(new Minion("Perdition's Blade", " Rare", " Weapon", " ", "  Rogue", 3, 2, 2));
		classic.add(new Spell("Pilfer", " Common", " Spell", " ", "  Rogue", 1, " ", "  "));
		classic.add(new Minion("Pint-Sized Summoner", " Rare", " Minion", " General", "  Any", 2, 2, 2));
		classic.add(new Minion("Pit Lord", " Epic", " Minion", " Demon", "  Warlock", 4, 5, 6));
		classic.add(new Spell("Power of the Wild", " Common", " Spell", " ", "  Druid", 2, " ", "  "));
		classic.add(new Spell("Preparation", " Epic", " Spell", " ", "  Rogue", 0, " ", "  "));
		classic.add(new Minion("Priestess of Elune", " Common", " Minion", " General", "  Any", 6, 5, 4));
		classic.add(new Minion("Prophet Velen", " Legendary", " Minion", " General", "  Priest", 7, 7, 7));
		classic.add(new Spell("Pyroblast", " Epic", " Spell", " ", "  Mage", 10, " ", "  "));
		classic.add(new Minion("Questing Adventurer", " Rare", " Minion", " General", "  Any", 3, 2, 2));
		classic.add(new Minion("Raging Worgen", " Common", " Minion", " General", "  Any", 3, 3, 3));
		classic.add(new Spell("Rampage", " Common", " Spell", " ", "  Warrior", 2, " ", "  "));
		classic.add(new Minion("Ravenholdt Assassin", " Rare", " Minion", " General", "  Any", 7, 7, 5));
		classic.add(new Spell("Redemption", " Common", " Spell", " ", "  Paladin", 1, " ", "  "));
		classic.add(new Spell("Repentance", " Common", " Spell", " ", "  Paladin", 1, " ", "  "));
		classic.add(new Spell("Righteousness", " Rare", " Spell", " ", "  Paladin", 5, " ", "  "));
		classic.add(new Spell("Savagery", " Rare", " Spell", " ", "  Druid", 1, " ", "  "));
		classic.add(new Minion("Savannah Highmane", " Rare", " Minion", " Beast", "  Hunter", 6, 6, 5));
		classic.add(new Minion("Scarlet Crusader", " Common", " Minion", " General", "  Any", 3, 3, 1));
		classic.add(new Minion("Scavenging Hyena", " Common", " Minion", " Beast", "  Hunter", 2, 2, 2));
		classic.add(new Minion("Sea Giant", " Epic", " Minion", " General", "  Any", 10, 8, 8));
		classic.add(new Minion("Secretkeeper", " Rare", " Minion", " General", "  Any", 1, 1, 2));
		classic.add(new Spell("Sense Demons", " Common", " Spell", " ", "  Warlock", 3, " ", "  "));
		classic.add(new Spell("Shadow Madness", " Rare", " Spell", " ", "  Priest", 4, " ", "  "));
		classic.add(new Spell("Shadowflame", " Rare", " Spell", " ", "  Warlock", 4, " ", "  "));
		classic.add(new Spell("Shadowform", " Epic", " Spell", " ", "  Priest", 3, " ", "  "));
		classic.add(new Spell("Shadowstep", " Common", " Spell", " ", "  Rogue", 0, " ", "  "));
		classic.add(new Spell("Shield Slam", " Epic", " Spell", " ", "  Warrior", 1, " ", "  "));
		classic.add(new Minion("Shieldbearer", " Common", " Minion", " General", "  Any", 1, 0, 4));
		classic.add(new Minion("SI:7 Agent", " Rare", " Minion", " General", "  Rogue", 3, 3, 3));
		classic.add(new Minion("SI:7 Infiltrator", " Rare", " Minion", " General", "  Any", 4, 5, 4));
		classic.add(new Minion("Siegebreaker", " Rare", " Minion", " Demon", "  Warlock", 7, 5, 8));
		classic.add(new Spell("Silence", " Common", " Spell", " ", "  Priest", 0, " ", "  "));
		classic.add(new Minion("Silver Hand Knight", " Common", " Minion", " General", "  Any", 5, 4, 4));
		classic.add(new Minion("Silvermoon Guardian", " Common", " Minion", " General", "  Any", 4, 3, 3));
		classic.add(new Spell("Siphon Soul", " Rare", " Spell", " ", "  Warlock", 6, " ", "  "));
		classic.add(new Spell("Slam", " Common", " Spell", " ", "  Warrior", 2, " ", "  "));
		classic.add(new Spell("Snake Trap", " Epic", " Spell", " ", "  Hunter", 2, " ", "  "));
		classic.add(new Spell("Snipe", " Common", " Spell", " ", "  Hunter", 2, " ", "  "));
		classic.add(new Minion("Sorcerer's Apprentice", " Common", " Minion", " General", "  Mage", 2, 3, 2));
		classic.add(new Spell("Soul of the Forest", " Common", " Spell", " ", "  Druid", 4, " ", "  "));
		classic.add(new Minion("Southsea Captain", " Epic", " Minion", " Pirate", "  Any", 3, 3, 3));
		classic.add(new Minion("Southsea Deckhand", " Common", " Minion", " Pirate", "  Any", 1, 2, 1));
		classic.add(new Spell("Spellbender", " Epic", " Spell", " ", "  Mage", 3, " ", "  "));
		classic.add(new Minion("Spellbreaker", " Common", " Minion", " General", "  Any", 4, 4, 3));
		classic.add(new Minion("Spiteful Smith", " Common", " Minion", " General", "  Any", 5, 4, 6));
		classic.add(new Minion("Stampeding Kodo", " Rare", " Minion", " Beast", "  Any", 5, 3, 5));
		classic.add(new Spell("Starfall", " Rare", " Spell", " ", "  Druid", 5, " ", "  "));
		classic.add(new Minion("Stormforged Axe", " Common", " Weapon", " ", "  Shaman", 2, 2, 3));
		classic.add(new Minion("Stranglethorn Tiger", " Common", " Minion", " Beast", "  Any", 5, 5, 5));
		classic.add(new Minion("Summoning Portal", " Common", " Minion", " General", "  Warlock", 4, 0, 4));
		classic.add(new Minion("Sunfury Protector", " Rare", " Minion", " General", "  Any", 2, 2, 3));
		classic.add(new Minion("Sunwalker", " Rare", " Minion", " General", "  Any", 6, 4, 5));
		classic.add(new Minion("Sword of Justice", " Epic", " Weapon", " ", "  Paladin", 3, 1, 5));
		classic.add(new Minion("Tauren Warrior", " Common", " Minion", " General", "  Any", 3, 2, 3));
		classic.add(new Minion("Temple Enforcer", " Common", " Minion", " General", "  Priest", 6, 6, 6));
		classic.add(new Minion("The Beast", " Legendary", " Minion", " Beast", "  Any", 6, 9, 7));
		classic.add(new Minion("The Black Knight", " Legendary", " Minion", " General", "  Any", 6, 4, 5));
		classic.add(new Spell("Thoughtsteal", " Common", " Spell", " ", "  Priest", 3, " ", "  "));
		classic.add(new Minion("Thrallmar Farseer", " Common", " Minion", " General", "  Any", 3, 2, 3));
		classic.add(new Minion("Tinkmaster Overspark", " Legendary", " Minion", " General", "  Any", 3, 3, 3));
		classic.add(new Minion("Tirion Fordring", " Legendary", " Minion", " General", "  Paladin", 8, 6, 6));
		classic.add(new Spell("Tome of Intellect", " Common", " Spell", " ", "  Mage", 1, " ", "  "));
		classic.add(new Minion("Twilight Drake", " Rare", " Minion", " Dragon", "  Any", 4, 4, 1));
		classic.add(new Spell("Twisting Nether", " Epic", " Spell", " ", "  Warlock", 8, " ", "  "));
		classic.add(new Minion("Unbound Elemental", " Common", " Minion", " Elemental", "  Shaman", 3, 2, 4));
		classic.add(new Spell("Unleash the Hounds", " Common", " Spell", " ", "  Hunter", 3, " ", "  "));
		classic.add(new Spell("Upgrade!", " Rare", " Spell", " ", "  Warrior", 1, " ", "  "));
		classic.add(new Spell("Vaporize", " Rare", " Spell", " ", "  Mage", 3, " ", "  "));
		classic.add(new Minion("Venture Co. Mercenary", " Common", " Minion", " General", "  Any", 5, 7, 6));
		classic.add(new Minion("Violet Teacher", " Rare", " Minion", " General", "  Any", 4, 3, 5));
		classic.add(new Minion("Void Terror", " Rare", " Minion", " Demon", "  Warlock", 3, 3, 3));
		classic.add(new Minion("Wild Pyromancer", " Rare", " Minion", " General", "  Any", 2, 3, 2));
		classic.add(new Minion("Windfury Harpy", " Common", " Minion", " General", "  Any", 6, 4, 5));
		classic.add(new Minion("Wisp", " Common", " Minion", " General", "  Any", 0, 1, 1));
		classic.add(new Minion("Worgen Infiltrator", " Common", " Minion", " General", "  Any", 1, 2, 1));
		classic.add(new Spell("Wrath", " Common", " Spell", " ", "  Druid", 2, " ", "  "));
		classic.add(new Minion("Young Dragonhawk", " Common", " Minion", " Beast", "  Any", 1, 1, 1));
		classic.add(new Minion("Young Priestess", " Rare", " Minion", " General", "  Any", 1, 2, 1));
		classic.add(new Minion("Youthful Brewmaster", " Common", " Minion", " General", "  Any", 2, 3, 2));
		classic.add(new Minion("Ysera", " Legendary", " Minion", " Dragon", "  Any", 9, 4, 12));
		return classic;
	}

	public static void main(String[] args) {

	}
}