package cardSets;

import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetMSoG {

	public ArrayList<Card> MSoGList() {
		ArrayList<Card> MSoG = new ArrayList<Card>();
		MSoG.add(new Minion("Abyssal Enforcer"," Common"," Minion"," Demon","  Warlock", 7 , 6 , 6    ));
		MSoG.add(new Minion("Alley Armorsmith"," Rare"," Minion"," General","  Warrior", 5 , 2 , 7    ));
		MSoG.add(new Minion("Alleycat"," Common"," Minion"," Beast","  Hunter", 1 , 1 , 1    ));
		MSoG.add(new Minion("Ancient of Blossoms"," Common"," Minion"," General","  Any", 6 , 3 , 8    ));
		MSoG.add(new Minion("Auctionmaster Beardo"," Legendary"," Minion"," General","  Any", 3 , 3 , 4    ));
		MSoG.add(new Minion("Aya Blackpaw"," Legendary"," Minion"," General"," ", 6 , 5 , 3    ));
		MSoG.add(new Minion("Backroom Bouncer"," Rare"," Minion"," General","  Any", 4 , 4 , 4    ));
		MSoG.add(new Minion("Backstreet Leper"," Common"," Minion"," General","  Any", 3 , 3 , 1    ));
		MSoG.add(new Minion("Big-Time Racketeer"," Common"," Minion"," General","  Any", 6 , 1 , 1    ));
		MSoG.add(new Spell("Blastcrystal Potion"," Common"," Spell"," ","  Warlock",4," ","  "));
		MSoG.add(new Spell("Bloodfury Potion"," Rare"," Spell"," ","  Warlock",3," ","  "));
		MSoG.add(new Minion("Blowgill Sniper"," Common"," Minion"," Murloc","  Any", 2 , 2 , 1    ));
		MSoG.add(new Minion("Blubber Baron"," Epic"," Minion"," General","  Any", 3 , 1 , 1    ));
		MSoG.add(new Minion("Bomb Squad"," Rare"," Minion"," General","  Any", 5 , 2 , 2    ));
		MSoG.add(new Minion("Brass Knuckles"," Epic"," Weapon"," ","  Warrior", 4 , 2 , 3    ));
		MSoG.add(new Minion("Burgly Bully"," Epic"," Minion"," General","  Any", 5 , 4 , 6    ));
		MSoG.add(new Spell("Call in the Finishers"," Common"," Spell"," ","  Shaman",4," ","  "));
		MSoG.add(new Minion("Celestial Dreamer"," Rare"," Minion"," General","  Druid", 3 , 3 , 3    ));
		MSoG.add(new Spell("Counterfeit Coin"," Rare"," Spell"," ","  Rogue",0," ","  "));
		MSoG.add(new Minion("Cryomancer"," Common"," Minion"," General","  Mage", 5 , 5 , 5    ));
		MSoG.add(new Minion("Crystalweaver"," Common"," Minion"," General","  Warlock", 4 , 5 , 4    ));
		MSoG.add(new Minion("Daring Reporter"," Common"," Minion"," General","  Any", 4 , 3 , 3    ));
		MSoG.add(new Minion("Defias Cleaner"," Epic"," Minion"," General","  Any", 6 , 5 , 7    ));
		MSoG.add(new Spell("Devolve"," Rare"," Spell"," ","  Shaman",2," ","  "));
		MSoG.add(new Minion("Dirty Rat"," Epic"," Minion"," General","  Any", 2 , 2 , 6    ));
		MSoG.add(new Minion("Dispatch Kodo"," Rare"," Minion"," Beast","  Hunter", 4 , 2 , 4    ));
		MSoG.add(new Minion("Don Han'Cho"," Legendary"," Minion"," General"," ", 7 , 5 , 6    ));
		MSoG.add(new Minion("Doppelgangster"," Rare"," Minion"," General","  Any", 5 , 2 , 2    ));
		MSoG.add(new Spell("Dragonfire Potion"," Epic"," Spell"," ","  Priest",6," ","  "));
		MSoG.add(new Minion("Drakonid Operative"," Rare"," Minion"," Dragon","  Priest", 5 , 5 , 6    ));
		MSoG.add(new Minion("Fel Orc Soulfiend"," Epic"," Minion"," General","  Any", 3 , 3 , 7    ));
		MSoG.add(new Spell("Felfire Potion"," Rare"," Spell"," ","  Warlock",6," ","  "));
		MSoG.add(new Minion("Fight Promoter"," Epic"," Minion"," General","  Any", 6 , 4 , 4    ));
		MSoG.add(new Spell("Finders Keepers"," Epic"," Spell"," ","  Shaman",1," ","  "));
		MSoG.add(new Minion("Finja, the Flying Star"," Legendary"," Minion"," Murloc","  Any", 5 , 2 , 4    ));
		MSoG.add(new Spell("Freezing Potion"," Common"," Spell"," ","  Mage",0," ","  "));
		MSoG.add(new Minion("Friendly Bartender"," Common"," Minion"," General","  Any", 2 , 2 , 3    ));
		MSoG.add(new Minion("Gadgetzan Ferryman"," Rare"," Minion"," General","  Rogue", 2 , 2 , 3    ));
		MSoG.add(new Minion("Gadgetzan Socialite"," Common"," Minion"," General","  Any", 2 , 2 , 2    ));
		MSoG.add(new Minion("Genzo, the Shark"," Legendary"," Minion"," General","  Any", 4 , 5 , 4    ));
		MSoG.add(new Spell("Getaway Kodo"," Rare"," Spell"," ","  Paladin",1," ","  "));
		MSoG.add(new Spell("Greater Arcane Missiles"," Epic"," Spell"," ","  Mage",7," ","  "));
		MSoG.add(new Spell("Greater Healing Potion"," Rare"," Spell"," ","  Priest",4," ","  "));
		MSoG.add(new Minion("Grimestreet Enforcer"," Rare"," Minion"," General","  Paladin", 5 , 4 , 4    ));
		MSoG.add(new Minion("Grimestreet Informant"," Rare"," Minion"," General"," ", 2 , 1 , 1    ));
		MSoG.add(new Minion("Grimestreet Outfitter"," Common"," Minion"," General","  Paladin", 2 , 1 , 1    ));
		MSoG.add(new Minion("Grimestreet Pawnbroker"," Rare"," Minion"," General","  Warrior", 3 , 3 , 3    ));
		MSoG.add(new Minion("Grimestreet Protector"," Rare"," Minion"," General","  Paladin", 7 , 6 , 6    ));
		MSoG.add(new Minion("Grimestreet Smuggler"," Common"," Minion"," General"," ", 3 , 2 , 4    ));
		MSoG.add(new Minion("Grimscale Chum"," Common"," Minion"," Murloc","  Paladin", 1 , 2 , 1    ));
		MSoG.add(new Minion("Grimy Gadgeteer"," Common"," Minion"," General","  Warrior", 4 , 4 , 3    ));
		MSoG.add(new Minion("Grook Fu Master"," Common"," Minion"," General","  Any", 5 , 3 , 5    ));
		MSoG.add(new Spell("Hidden Cache"," Rare"," Spell"," ","  Hunter",2," ","  "));
		MSoG.add(new Minion("Hired Gun"," Common"," Minion"," General","  Any", 3 , 4 , 3    ));
		MSoG.add(new Minion("Hobart Grapplehammer"," Legendary"," Minion"," General","  Warrior", 2 , 2 , 2    ));
		MSoG.add(new Minion("Hozen Healer"," Common"," Minion"," General","  Any", 4 , 2 , 6    ));
		MSoG.add(new Spell("I Know a Guy"," Common"," Spell"," ","  Warrior",1," ","  "));
		MSoG.add(new Minion("Inkmaster Solia"," Legendary"," Minion"," General","  Mage", 7 , 5 , 5    ));
		MSoG.add(new Minion("Jade Behemoth"," Common"," Minion"," General","  Druid", 6 , 3 , 6    ));
		MSoG.add(new Spell("Jade Blossom"," Common"," Spell"," ","  Druid",3," ","  "));
		MSoG.add(new Minion("Jade Chieftain"," Common"," Minion"," General","  Shaman", 7 , 5 , 5    ));
		MSoG.add(new Minion("Jade Claws"," Rare"," Weapon"," ","  Shaman", 2 , 2 , 2    ));
		MSoG.add(new Spell("Jade Idol"," Rare"," Spell"," ","  Druid",1," ","  "));
		MSoG.add(new Spell("Jade Lightning"," Common"," Spell"," ","  Shaman",4," ","  "));
		MSoG.add(new Spell("Jade Shuriken"," Common"," Spell"," ","  Rogue",2," ","  "));
		MSoG.add(new Minion("Jade Spirit"," Common"," Minion"," Elemental"," ", 4 , 2 , 3    ));
		MSoG.add(new Minion("Jade Swarmer"," Common"," Minion"," General","  Rogue", 2 , 1 , 1    ));
		MSoG.add(new Minion("Jinyu Waterspeaker"," Rare"," Minion"," General","  Shaman", 4 , 3 , 6    ));
		MSoG.add(new Minion("Kabal Chemist"," Common"," Minion"," General"," ", 4 , 3 , 3    ));
		MSoG.add(new Minion("Kabal Courier"," Rare"," Minion"," General"," ", 3 , 2 , 2    ));
		MSoG.add(new Minion("Kabal Crystal Runner"," Rare"," Minion"," General","  Mage", 6 , 5 , 5    ));
		MSoG.add(new Minion("Kabal Lackey"," Common"," Minion"," General","  Mage", 1 , 2 , 1    ));
		MSoG.add(new Minion("Kabal Songstealer"," Common"," Minion"," General","  Priest", 5 , 5 , 5    ));
		MSoG.add(new Minion("Kabal Talonpriest"," Common"," Minion"," General","  Priest", 3 , 3 , 4    ));
		MSoG.add(new Minion("Kabal Trafficker"," Epic"," Minion"," General","  Warlock", 6 , 6 , 6    ));
		MSoG.add(new Minion("Kazakus"," Legendary"," Minion"," General"," ", 4 , 3 , 3    ));
		MSoG.add(new Minion("Knuckles"," Legendary"," Minion"," Beast","  Hunter", 5 , 3 , 7    ));
		MSoG.add(new Minion("Kooky Chemist"," Common"," Minion"," General","  Any", 4 , 4 , 4    ));
		MSoG.add(new Minion("Krul the Unshackled"," Legendary"," Minion"," Demon","  Warlock", 9 , 7 , 9    ));
		MSoG.add(new Minion("Kun the Forgotten King"," Legendary"," Minion"," General","  Druid", 10 , 7 , 7    ));
		MSoG.add(new Minion("Leatherclad Hogleader"," Epic"," Minion"," General","  Any", 6 , 6 , 6    ));
		MSoG.add(new Minion("Lotus Agents"," Rare"," Minion"," General"," ", 5 , 5 , 3    ));
		MSoG.add(new Minion("Lotus Assassin"," Epic"," Minion"," General","  Rogue", 5 , 5 , 5    ));
		MSoG.add(new Minion("Lotus Illusionist"," Epic"," Minion"," General","  Shaman", 4 , 3 , 5    ));
		MSoG.add(new Minion("Luckydo Buccaneer"," Epic"," Minion"," Pirate","  Rogue", 6 , 5 , 5    ));
		MSoG.add(new Spell("Lunar Visions"," Epic"," Spell"," ","  Druid",5," ","  "));
 		MSoG.add(new Minion("Madam Goya"," Legendary"," Minion"," General","  Any", 6 , 4 , 3    ));
		MSoG.add(new Minion("Mana Geode"," Epic"," Minion"," Elemental","  Priest", 2 , 2 , 3    ));
		MSoG.add(new Minion("Manic Soulcaster"," Epic"," Minion"," General","  Mage", 3 , 3 , 4    ));
		MSoG.add(new Spell("Mark of the Lotus"," Common"," Spell"," ","  Druid",1," ","  "));
		MSoG.add(new Minion("Mayor Noggenfogger"," Legendary"," Minion"," General","  Any", 9 , 5 , 4    ));
		MSoG.add(new Minion("Meanstreet Marshal"," Epic"," Minion"," General","  Paladin", 1 , 1 , 2    ));
		MSoG.add(new Minion("Mistress of Mixtures"," Common"," Minion"," General","  Any", 1 , 2 , 2    ));
		MSoG.add(new Minion("Naga Corsair"," Common"," Minion"," Pirate","  Any", 4 , 5 , 4    ));
		MSoG.add(new Minion("Patches the Pirate"," Legendary"," Minion"," Pirate","  Any", 1 , 1 , 1    ));
		MSoG.add(new Spell("Pilfered Power"," Epic"," Spell"," ","  Druid",3," ","  "));
		MSoG.add(new Spell("Pint-Size Potion"," Rare"," Spell"," ","  Priest",1," ","  "));
		MSoG.add(new Minion("Piranha Launcher"," Epic"," Weapon"," ","  Hunter", 5 , 2 , 4    ));
		MSoG.add(new Spell("Potion of Madness"," Common"," Spell"," ","  Priest",1," ","  "));
		MSoG.add(new Spell("Potion of Polymorph"," Rare"," Spell"," ","  Mage",3," ","  "));
		MSoG.add(new Minion("Public Defender"," Common"," Minion"," General","  Warrior", 2 , 0 , 7    ));
		MSoG.add(new Minion("Rat Pack"," Epic"," Minion"," Beast","  Hunter", 3 , 2 , 2    ));
		MSoG.add(new Minion("Raza the Chained"," Legendary"," Minion"," General","  Priest", 5 , 5 , 5    ));
		MSoG.add(new Minion("Red Mana Wyrm"," Common"," Minion"," General","  Any", 5 , 2 , 6    ));
		MSoG.add(new Minion("Seadevil Stinger"," Rare"," Minion"," Murloc","  Warlock", 4 , 4 , 2    ));
		MSoG.add(new Minion("Second-Rate Bruiser"," Rare"," Minion"," General","  Any", 5 , 4 , 5    ));
		MSoG.add(new Minion("Sergeant Sally"," Legendary"," Minion"," General","  Any", 3 , 1 , 1    ));
		MSoG.add(new Minion("Shadow Rager"," Common"," Minion"," General","  Rogue", 3 , 5 , 1    ));
		MSoG.add(new Minion("Shadow Sensei"," Rare"," Minion"," General","  Rogue", 4 , 4 , 4    ));
		MSoG.add(new Minion("Shaku, the Collector"," Legendary"," Minion"," General","  Rogue", 3 , 2 , 3    ));
		MSoG.add(new Minion("Shaky Zipgunner"," Common"," Minion"," General","  Hunter", 3 , 3 , 3    ));
		MSoG.add(new Spell("Sleep with the Fishes"," Epic"," Spell"," ","  Warrior",2," ","  "));
		MSoG.add(new Minion("Small-Time Buccaneer"," Rare"," Minion"," Pirate","  Any", 1 , 1 , 1    ));
		MSoG.add(new Spell("Small-Time Recruits"," Epic"," Spell"," ","  Paladin",3," ","  "));
		MSoG.add(new Spell("Smuggler's Crate"," Common"," Spell"," ","  Hunter",1," ","  "));
		MSoG.add(new Spell("Smuggler's Run"," Common"," Spell"," ","  Paladin",1," ","  "));
		MSoG.add(new Minion("Spiked Hogrider"," Rare"," Minion"," General","  Any", 5 , 5 , 5    ));
		MSoG.add(new Spell("Stolen Goods"," Rare"," Spell"," ","  Warrior",2," ","  "));
		MSoG.add(new Minion("Street Trickster"," Common"," Minion"," Demon","  Any", 3 , 0 , 7    ));
		MSoG.add(new Minion("Streetwise Investigator"," Common"," Minion"," General","  Any", 5 , 4 , 6    ));
		MSoG.add(new Minion("Tanaris Hogchopper"," Common"," Minion"," General","  Any", 4 , 4 , 4    ));
		MSoG.add(new Minion("Toxic Sewer Ooze"," Common"," Minion"," General","  Any", 3 , 4 , 3    ));
		MSoG.add(new Minion("Trogg Beastrager"," Rare"," Minion"," General","  Hunter", 2 , 3 , 2    ));
		MSoG.add(new Minion("Unlicensed Apothecary"," Epic"," Minion"," Demon","  Warlock", 3 , 5 , 5    ));
		MSoG.add(new Minion("Virmen Sensei"," Rare"," Minion"," General","  Druid", 5 , 4 , 5    ));
		MSoG.add(new Spell("Volcanic Potion"," Rare"," Spell"," ","  Mage",3," ","  "));
		MSoG.add(new Minion("Weasel Tunneler"," Epic"," Minion"," Beast","  Any", 1 , 1 , 1    ));
		MSoG.add(new Minion("White Eyes"," Legendary"," Minion"," General","  Shaman", 5 , 5 , 5    ));
		MSoG.add(new Minion("Wickerflame Burnbristle"," Legendary"," Minion"," General","  Paladin", 3 , 2 , 2    ));
		MSoG.add(new Minion("Wind-up Burglebot"," Epic"," Minion"," Mech","  Any", 6 , 5 , 5    ));
		MSoG.add(new Minion("Worgen Greaser"," Common"," Minion"," General","  Any", 4 , 6 , 3    ));
		MSoG.add(new Minion("Wrathion"," Legendary"," Minion"," General","  Any", 6 , 4 , 5    ));
 		return MSoG;
	}

}
