package cardSets;

import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetKotFT {
	public ArrayList<Card> KotFTList() {
		ArrayList<Card> KotFT= new ArrayList<Card>();
		KotFT.add(new Minion("Abominable Bowman"," Epic"," Minion"," General","  Hunter", 7 , 6 , 7    ));
		KotFT.add(new Minion("Acherus Veteran"," Common"," Minion"," General","  Any", 1 , 2 , 1    ));
		KotFT.add(new Minion("Acolyte of Agony"," Common"," Minion"," General","  Priest", 3 , 3 , 3    ));
		KotFT.add(new Minion("Animated Berserker"," Common"," Minion"," General","  Warrior", 1 , 1 , 3    ));
		KotFT.add(new Minion("Archbishop Benedictus"," Legendary"," Minion"," General","  Priest", 7 , 4 , 6    ));
		KotFT.add(new Minion("Arfus"," Legendary"," Minion"," Beast","  Any", 4 , 2 , 2    ));
		KotFT.add(new Minion("Arrogant Crusader"," Rare"," Minion"," General","  Paladin", 4 , 5 , 2    ));
		KotFT.add(new Spell("Avalanche"," Rare"," Spell"," ","  Shaman",4," ","  "));
		KotFT.add(new Minion("Bearshark"," Common"," Minion"," Beast","  Hunter", 3 , 4 , 3    ));
		KotFT.add(new Minion("Blackguard"," Epic"," Minion"," General","  Paladin", 6 , 3 , 9    ));
		KotFT.add(new Minion("Blood Razor"," Common"," Weapon"," ","  Warrior", 4 , 2 , 2    ));
		KotFT.add(new Minion("Blood-Queen Lana'thel"," Legendary"," Minion"," General","  Warlock", 5 , 1 , 6    ));
		KotFT.add(new Minion("Bloodworm"," Common"," Minion"," Beast","  Any", 5 , 4 , 4    ));
		KotFT.add(new Minion("Bolvar, Fireblood"," Legendary"," Minion"," General","  Paladin", 5 , 1 , 7    ));
		KotFT.add(new Minion("Bone Baron"," Common"," Minion"," General","  Rogue", 5 , 5 , 5    ));
		KotFT.add(new Minion("Bone Drake"," Rare"," Minion"," Dragon","  Any", 6 , 6 , 5    ));
		KotFT.add(new Minion("Bonemare"," Common"," Minion"," General","  Any", 8 , 5 , 5    ));
		KotFT.add(new Spell("Breath of Sindragosa"," Common"," Spell"," ","  Mage",1," ","  "));
		KotFT.add(new Spell("Bring It On!"," Epic"," Spell"," ","  Warrior",2," ","  "));
		KotFT.add(new Minion("Brrrloc"," Common"," Minion"," Murloc","  Shaman", 2 , 2 , 2    ));
		KotFT.add(new Minion("Chillblade Champion"," Common"," Minion"," General","  Paladin", 4 , 3 , 2    ));
		KotFT.add(new Minion("Cobalt Scalebane"," Common"," Minion"," Dragon","  Any", 5 , 5 , 5    ));
		KotFT.add(new Minion("Coldwraith"," Common"," Minion"," General","  Mage", 3 , 3 , 4    ));
		KotFT.add(new Minion("Corpse Raiser"," Rare"," Minion"," General","  Any", 5 , 3 , 3    ));
		KotFT.add(new Minion("Corpse Widow"," Rare"," Minion"," Beast","  Hunter", 5 , 4 , 6    ));
		KotFT.add(new Minion("Corpsetaker"," Epic"," Minion"," General","  Any", 4 , 3 , 3    ));
		KotFT.add(new Spell("Cryostasis"," Epic"," Spell"," ","  Shaman",2," ","  "));
		KotFT.add(new Minion("Crypt Lord"," Common"," Minion"," General","  Druid", 3 , 1 , 6    ));
		KotFT.add(new Spell("Dark Conviction"," Common"," Spell"," ","  Paladin",2," ","  "));
		KotFT.add(new Spell("Dead Man's Hand"," Epic"," Spell"," ","  Warrior",2," ","  "));
		KotFT.add(new Minion("Deadscale Knight"," Common"," Minion"," Murloc","  Any", 1 , 1 , 1    ));
		KotFT.add(new Minion("Death Revenant"," Rare"," Minion"," General","  Warrior", 5 , 3 , 3    ));
		KotFT.add(new Minion("Deathaxe Punisher"," Epic"," Minion"," General","  Any", 4 , 3 , 3    ));
		KotFT.add(new Minion("Deathspeaker"," Common"," Minion"," General","  Any", 3 , 2 , 4    ));
		KotFT.add(new Spell("Defile"," Rare"," Spell"," ","  Warlock",2," ","  "));
		KotFT.add(new Spell("Desperate Stand"," Rare"," Spell"," ","  Paladin",2," ","  "));
		KotFT.add(new Minion("Despicable Dreadlord"," Rare"," Minion"," Demon","  Warlock", 5 , 4 , 5    ));
		KotFT.add(new Spell("Devour Mind"," Rare"," Spell"," ","  Priest",5," ","  "));
		KotFT.add(new Minion("Doomed Apprentice"," Rare"," Minion"," General","  Mage", 3 , 3 , 2    ));
		KotFT.add(new Spell("Doomerang"," Epic"," Spell"," ","  Rogue",1," ","  "));
		KotFT.add(new Spell("Drain Soul"," Common"," Spell"," ","  Warlock",2," ","  "));
		KotFT.add(new Minion("Drakkari Defender"," Common"," Minion"," General","  Shaman", 3 , 2 , 8    ));
		KotFT.add(new Minion("Drakkari Enchanter"," Epic"," Minion"," General","  Any", 3 , 1 , 5    ));
		KotFT.add(new Minion("Druid of the Swarm"," Rare"," Minion"," General","  Druid", 2 , 1 , 2    ));
		KotFT.add(new Spell("Embrace Darkness"," Epic"," Spell"," ","  Priest",6," ","  "));
		KotFT.add(new Spell("Eternal Servitude"," Rare"," Spell"," ","  Priest",4," ","  "));
		KotFT.add(new Minion("Exploding Bloatbat"," Rare"," Minion"," Beast","  Hunter", 4 , 2 , 1    ));
		KotFT.add(new Minion("Fallen Sun Cleric"," Common"," Minion"," General","  Any", 2 , 2 , 1    ));
		KotFT.add(new Minion("Fatespinner"," Epic"," Minion"," General","  Druid", 5 , 5 , 3    ));
		KotFT.add(new Spell("Forge of Souls"," Common"," Spell"," ","  Warrior",2," ","  "));
		KotFT.add(new Spell("Frozen Clone"," Common"," Spell"," ","  Mage",3," ","  "));
		KotFT.add(new Minion("Furnacefire Colossus"," Epic"," Minion"," General","  Any", 6 , 6 , 6    ));
		KotFT.add(new Minion("Ghastly Conjurer"," Rare"," Minion"," General","  Mage", 4 , 2 , 6    ));
		KotFT.add(new Spell("Glacial Mysteries"," Epic"," Spell"," ","  Mage",8," ","  "));
		KotFT.add(new Spell("Gnash"," Common"," Spell"," ","  Druid",3," ","  "));
		KotFT.add(new Minion("Gnomeferatu"," Epic"," Minion"," General","  Warlock", 2 , 2 , 3    ));
		KotFT.add(new Minion("Grave Shambler"," Common"," Minion"," Elemental","  Any", 4 , 4 , 4    ));
		KotFT.add(new Minion("Grim Necromancer"," Common"," Minion"," General","  Any", 4 , 2 , 4    ));
		KotFT.add(new Minion("Hadronox"," Legendary"," Minion"," Beast","  Druid", 9 , 3 , 7    ));
		KotFT.add(new Minion("Happy Ghoul"," Rare"," Minion"," General","  Any", 3 , 3 , 3    ));
		KotFT.add(new Minion("Howlfiend"," Common"," Minion"," Demon","  Warlock", 3 , 3 , 6    ));
		KotFT.add(new Minion("Howling Commander"," Rare"," Minion"," General","  Paladin", 3 , 2 , 2    ));
		KotFT.add(new Minion("Hyldnir Frostrider"," Common"," Minion"," General","  Any", 3 , 4 , 4    ));
		KotFT.add(new Minion("Ice Breaker"," Rare"," Weapon"," ","  Shaman", 3 , 1 , 3    ));
		KotFT.add(new Spell("Ice Fishing"," Common"," Spell"," ","  Shaman",2," ","  "));
		KotFT.add(new Minion("Ice Walker"," Rare"," Minion"," Elemental","  Mage", 2 , 1 , 3    ));
		KotFT.add(new Minion("Keening Banshee"," Rare"," Minion"," General","  Any", 4 , 5 , 5    ));
		KotFT.add(new Spell("Leeching Poison"," Common"," Spell"," ","  Rogue",1," ","  "));
		KotFT.add(new Minion("Light's Sorrow"," Epic"," Weapon"," ","  Paladin", 4 , 1 , 4    ));
		KotFT.add(new Minion("Lilian Voss"," Legendary"," Minion"," General","  Rogue", 4 , 4 , 5    ));
		KotFT.add(new Minion("Meat Wagon"," Epic"," Minion"," Mech","  Any", 4 , 1 , 4    ));
		KotFT.add(new Minion("Mindbreaker"," Rare"," Minion"," General","  Any", 3 , 2 , 5    ));
		KotFT.add(new Minion("Moorabi"," Legendary"," Minion"," General","  Shaman", 6 , 4 , 4    ));
		KotFT.add(new Minion("Mountainfire Armor"," Rare"," Minion"," General","  Warrior", 3 , 4 , 3    ));
		KotFT.add(new Minion("Necrotic Geist"," Common"," Minion"," General","  Any", 6 , 5 , 3    ));
		KotFT.add(new Minion("Nerubian Unraveler"," Epic"," Minion"," General","  Any", 6 , 5 , 5    ));
		KotFT.add(new Minion("Night Howler"," Common"," Minion"," General","  Any", 4 , 3 , 4    ));
		KotFT.add(new Minion("Obsidian Statue"," Epic"," Minion"," General","  Priest", 9 , 4 , 8    ));
		KotFT.add(new Minion("Phantom Freebooter"," Rare"," Minion"," Pirate","  Any", 4 , 3 , 3    ));
		KotFT.add(new Minion("Plague Scientist"," Common"," Minion"," General","  Rogue", 3 , 2 , 3    ));
		KotFT.add(new Spell("Play Dead"," Common"," Spell"," ","  Hunter",1," ","  "));
		KotFT.add(new Minion("Prince Keleseth"," Legendary"," Minion"," General","  Any", 2 , 2 , 2    ));
		KotFT.add(new Minion("Prince Taldaram"," Legendary"," Minion"," General","  Any", 3 , 3 , 3    ));
		KotFT.add(new Minion("Prince Valanar"," Legendary"," Minion"," General","  Any", 4 , 4 , 4    ));
		KotFT.add(new Minion("Professor Putricide"," Legendary"," Minion"," General","  Hunter", 4 , 5 , 4    ));
		KotFT.add(new Minion("Rattling Rascal"," Epic"," Minion"," General","  Any", 4 , 2 , 2    ));
		KotFT.add(new Minion("Righteous Protector"," Common"," Minion"," General","  Paladin", 1 , 1 , 1    ));
		KotFT.add(new Spell("Roll the Bones"," Rare"," Spell"," ","  Rogue",2," ","  "));
		KotFT.add(new Minion("Rotface"," Legendary"," Minion"," General","  Warrior", 8 , 4 , 6    ));
		KotFT.add(new Minion("Runeforge Haunter"," Rare"," Minion"," General","  Rogue", 4 , 5 , 3    ));
		KotFT.add(new Minion("Sanguine Reveler"," Common"," Minion"," General","  Warlock", 1 , 1 , 1    ));
		KotFT.add(new Minion("Saronite Chain Gang"," Rare"," Minion"," General","  Any", 4 , 2 , 3    ));
		KotFT.add(new Minion("Shadow Ascendant"," Common"," Minion"," General","  Priest", 2 , 2 , 2    ));
		KotFT.add(new Spell("Shadow Essence"," Rare"," Spell"," ","  Priest",6," ","  "));
		KotFT.add(new Minion("Shadowblade"," Rare"," Weapon"," ","  Rogue", 3 , 3 , 2    ));
		KotFT.add(new Minion("Shallow Gravedigger"," Rare"," Minion"," General","  Any", 3 , 3 , 1    ));
		KotFT.add(new Spell("Simulacrum"," Epic"," Spell"," ","  Mage",3," ","  "));
		KotFT.add(new Minion("Sindragosa"," Legendary"," Minion"," Dragon","  Mage", 8 , 8 , 8    ));
		KotFT.add(new Minion("Skelemancer"," Common"," Minion"," General","  Any", 5 , 2 , 2    ));
		KotFT.add(new Minion("Skulking Geist"," Epic"," Minion"," General","  Any", 6 , 4 , 6    ));
		KotFT.add(new Minion("Snowflipper Penguin"," Common"," Minion"," Beast","  Any", 0 , 1 , 1    ));
		KotFT.add(new Minion("Snowfury Giant"," Epic"," Minion"," Elemental","  Shaman", 11 , 8 , 8    ));
		KotFT.add(new Minion("Spectral Pillager"," Epic"," Minion"," General","  Rogue", 6 , 5 , 5    ));
		KotFT.add(new Minion("Spellweaver"," Common"," Minion"," General","  Any", 6 , 4 , 4    ));
		KotFT.add(new Spell("Spirit Lash"," Common"," Spell"," ","  Priest",2," ","  "));
		KotFT.add(new Spell("Spreading Plague"," Rare"," Spell"," ","  Druid",6," ","  "));
		KotFT.add(new Minion("Stitched Tracker"," Common"," Minion"," General","  Hunter", 3 , 2 , 2    ));
		KotFT.add(new Minion("Strongshell Scavenger"," Rare"," Minion"," General","  Druid", 4 , 2 , 3    ));
		KotFT.add(new Minion("Sunborne Val'kyr"," Common"," Minion"," General","  Any", 5 , 5 , 4    ));
		KotFT.add(new Minion("Tainted Zealot"," Common"," Minion"," General","  Any", 2 , 1 , 1    ));
		KotFT.add(new Minion("The Lich King"," Legendary"," Minion"," General","  Any", 8 , 8 , 8    ));
		KotFT.add(new Minion("Ticking Abomination"," Rare"," Minion"," General","  Any", 4 , 5 , 6    ));
		KotFT.add(new Minion("Tomb Lurker"," Epic"," Minion"," General","  Any", 5 , 5 , 3    ));
		KotFT.add(new Spell("Toxic Arrow"," Epic"," Spell"," ","  Hunter",2," ","  "));
		KotFT.add(new Spell("Treachery"," Epic"," Spell"," ","  Warlock",3," ","  "));
		KotFT.add(new Minion("Tuskarr Fisherman"," Common"," Minion"," General","  Any", 2 , 2 , 3    ));
		KotFT.add(new Spell("Ultimate Infestation"," Epic"," Spell"," ","  Druid",10," ","  "));
		KotFT.add(new Spell("Unwilling Sacrifice"," Rare"," Spell"," ","  Warlock",3," ","  "));
		KotFT.add(new Minion("Val'kyr Soulclaimer"," Rare"," Minion"," General","  Warrior", 3 , 1 , 4    ));
		KotFT.add(new Minion("Venomancer"," Common"," Minion"," General","  Any", 5 , 2 , 5    ));
		KotFT.add(new Spell("Venomstrike Trap"," Rare"," Spell"," ","  Hunter",2," ","  "));
		KotFT.add(new Minion("Voodoo Hexxer"," Rare"," Minion"," General","  Shaman", 5 , 2 , 7    ));
		KotFT.add(new Minion("Vryghoul"," Common"," Minion"," General","  Any", 3 , 3 , 1    ));
		KotFT.add(new Spell("Webweave"," Common"," Spell"," ","  Druid",5," ","  "));
		KotFT.add(new Minion("Wicked Skeleton"," Common"," Minion"," General","  Any", 4 , 1 , 1    ));
		KotFT.add(new Minion("Wretched Tiller"," Common"," Minion"," General","  Any", 1 , 1 , 1    ));
 		return KotFT;
		
	}
}

