package cardSets;
import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetGT {

 
	public static void main(String[] args) {

	}
	public ArrayList<Card> GrandTournamentList() {
		ArrayList<Card> grandTourn = new ArrayList<Card>();
		grandTourn.add(new Minion("Acidmaw"," Legendary"," Minion"," Beast","  Hunter", 7 , 4 , 2    ));
		grandTourn.add(new Minion("Alexstrasza's Champion"," Rare"," Minion"," General","  Warrior", 2 , 2 , 3    ));
		grandTourn.add(new Spell("Ancestral Knowledge"," Common"," Spell"," ","  Shaman",2," ","  "));
		grandTourn.add(new Minion("Anub'arak"," Legendary"," Minion"," General","  Rogue", 9 , 8 , 4    ));
		grandTourn.add(new Spell("Arcane Blast"," Epic"," Spell"," ","  Mage",1," ","  "));
		grandTourn.add(new Minion("Argent Horserider"," Common"," Minion"," General","  Any", 3 , 2 , 1    ));
		grandTourn.add(new Minion("Argent Lance"," Rare"," Weapon"," ","  Paladin", 2 , 2 , 2    ));
		grandTourn.add(new Minion("Argent Watchman"," Rare"," Minion"," General","  Any", 2 , 2 , 4    ));
		grandTourn.add(new Minion("Armored Warhorse"," Rare"," Minion"," Beast","  Any", 4 , 5 , 3    ));
		grandTourn.add(new Spell("Astral Communion"," Epic"," Spell"," ","  Druid",4," ","  "));
		grandTourn.add(new Minion("Aviana"," Legendary"," Minion"," General","  Druid", 10 , 5 , 5    ));
		grandTourn.add(new Spell("Ball of Spiders"," Rare"," Spell"," ","  Hunter",6," ","  "));
		grandTourn.add(new Spell("Bash"," Common"," Spell"," ","  Warrior",3," ","  "));
		grandTourn.add(new Spell("Bear Trap"," Common"," Spell"," ","  Hunter",2," ","  "));
		grandTourn.add(new Spell("Beneath the Grounds"," Epic"," Spell"," ","  Rogue",3," ","  "));
		grandTourn.add(new Minion("Bolf Ramshield"," Legendary"," Minion"," General","  Any", 6 , 3 , 9    ));
		grandTourn.add(new Spell("Bolster"," Common"," Spell"," ","  Warrior",2," ","  "));
		grandTourn.add(new Minion("Boneguard Lieutenant"," Common"," Minion"," General","  Any", 2 , 3 , 2    ));
		grandTourn.add(new Minion("Brave Archer"," Common"," Minion"," General","  Hunter", 1 , 2 , 1    ));
		grandTourn.add(new Minion("Buccaneer"," Common"," Minion"," Pirate","  Rogue", 1 , 2 , 1    ));
		grandTourn.add(new Spell("Burgle"," Rare"," Spell"," ","  Rogue",3," ","  "));
		grandTourn.add(new Minion("Captured Jormungar"," Common"," Minion"," Beast","  Any", 7 , 5 , 9    ));
		grandTourn.add(new Minion("Charged Hammer"," Epic"," Weapon"," ","  Shaman", 4 , 2 , 4    ));
		grandTourn.add(new Minion("Chillmaw"," Legendary"," Minion"," Dragon","  Any", 7 , 6 , 6    ));
		grandTourn.add(new Minion("Clockwork Knight"," Common"," Minion"," Mech","  Any", 5 , 5 , 5    ));
		grandTourn.add(new Minion("Coldarra Drake"," Epic"," Minion"," Dragon","  Mage", 6 , 6 , 6    ));
		grandTourn.add(new Minion("Coliseum Manager"," Rare"," Minion"," General","  Any", 3 , 2 , 5    ));
		grandTourn.add(new Spell("Competitive Spirit"," Rare"," Spell"," ","  Paladin",1," ","  "));
		grandTourn.add(new Minion("Confessor Paletress"," Legendary"," Minion"," General","  Priest", 7 , 5 , 4    ));
		grandTourn.add(new Spell("Confuse"," Epic"," Spell"," ","  Priest",2," ","  "));
		grandTourn.add(new Spell("Convert"," Rare"," Spell"," ","  Priest",2," ","  "));
		grandTourn.add(new Minion("Crowd Favorite"," Epic"," Minion"," General","  Any", 4 , 4 , 4    ));
		grandTourn.add(new Minion("Cutpurse"," Rare"," Minion"," General","  Rogue", 2 , 2 , 2    ));
		grandTourn.add(new Minion("Dalaran Aspirant"," Common"," Minion"," General","  Mage", 4 , 3 , 5    ));
		grandTourn.add(new Spell("Dark Bargain"," Epic"," Spell"," ","  Warlock",6," ","  "));
		grandTourn.add(new Minion("Darnassus Aspirant"," Rare"," Minion"," General","  Druid", 2 , 2 , 3    ));
		grandTourn.add(new Spell("Demonfuse"," Common"," Spell"," ","  Warlock",2," ","  "));
		grandTourn.add(new Minion("Draenei Totemcarver"," Rare"," Minion"," General","  Shaman", 4 , 4 , 4    ));
		grandTourn.add(new Minion("Dragonhawk Rider"," Common"," Minion"," General","  Any", 3 , 3 , 3    ));
		grandTourn.add(new Minion("Dreadscale"," Legendary"," Minion"," Beast","  Hunter", 3 , 4 , 2    ));
		grandTourn.add(new Minion("Dreadsteed"," Epic"," Minion"," Demon","  Warlock", 4 , 1 , 1    ));
		grandTourn.add(new Minion("Druid of the Saber"," Common"," Minion"," General","  Druid", 2 , 2 , 1    ));
		grandTourn.add(new Minion("Eadric the Pure"," Legendary"," Minion"," General","  Paladin", 7 , 3 , 7    ));
		grandTourn.add(new Spell("Effigy"," Rare"," Spell"," ","  Mage",3," ","  "));
		grandTourn.add(new Spell("Elemental Destruction"," Epic"," Spell"," ","  Shaman",3," ","  "));
		grandTourn.add(new Spell("Enter the Coliseum"," Epic"," Spell"," ","  Paladin",6," ","  "));
		grandTourn.add(new Minion("Evil Heckler"," Common"," Minion"," General","  Any", 4 , 5 , 4    ));
		grandTourn.add(new Minion("Eydis Darkbane"," Legendary"," Minion"," General","  Any", 3 , 3 , 4    ));
		grandTourn.add(new Minion("Fallen Hero"," Rare"," Minion"," General","  Mage", 2 , 3 , 2    ));
		grandTourn.add(new Minion("Fearsome Doomguard"," Common"," Minion"," Demon","  Warlock", 7 , 6 , 8    ));
		grandTourn.add(new Minion("Fencing Coach"," Rare"," Minion"," General","  Any", 3 , 2 , 2    ));
		grandTourn.add(new Spell("Fist of Jaraxxus"," Rare"," Spell"," ","  Warlock",4," ","  "));
		grandTourn.add(new Minion("Fjola Lightbane"," Legendary"," Minion"," General","  Any", 3 , 3 , 4    ));
		grandTourn.add(new Minion("Flame Juggler"," Common"," Minion"," General","  Any", 2 , 2 , 3    ));
		grandTourn.add(new Spell("Flame Lance"," Common"," Spell"," ","  Mage",5," ","  "));
		grandTourn.add(new Spell("Flash Heal"," Common"," Spell"," ","  Priest",1," ","  "));
		grandTourn.add(new Minion("Frigid Snobold"," Common"," Minion"," General","  Any", 4 , 2 , 6    ));
		grandTourn.add(new Minion("Frost Giant"," Epic"," Minion"," General","  Any", 10 , 8 , 8    ));
		grandTourn.add(new Minion("Gadgetzan Jouster"," Common"," Minion"," General","  Any", 1 , 1 , 2    ));
		grandTourn.add(new Minion("Garrison Commander"," Epic"," Minion"," General","  Any", 2 , 2 , 3    ));
		grandTourn.add(new Minion("Gormok the Impaler"," Legendary"," Minion"," General","  Any", 4 , 4 , 4    ));
		grandTourn.add(new Minion("Grand Crusader"," Epic"," Minion"," General","  Any", 6 , 5 , 5    ));
		grandTourn.add(new Spell("Healing Wave"," Rare"," Spell"," ","  Shaman",3," ","  "));
		grandTourn.add(new Minion("Holy Champion"," Common"," Minion"," General","  Priest", 4 , 3 , 5    ));
		grandTourn.add(new Minion("Ice Rager"," Common"," Minion"," Elemental","  Any", 3 , 5 , 2    ));
		grandTourn.add(new Minion("Icehowl"," Legendary"," Minion"," General","  Any", 9 , 10 , 10    ));
		grandTourn.add(new Minion("Injured Kvaldir"," Rare"," Minion"," General","  Any", 1 , 2 , 4    ));
		grandTourn.add(new Minion("Justicar Trueheart"," Legendary"," Minion"," General","  Any", 6 , 6 , 3    ));
		grandTourn.add(new Minion("King's Defender"," Rare"," Weapon"," ","  Warrior", 3 , 3 , 2    ));
		grandTourn.add(new Minion("King's Elekk"," Common"," Minion"," Beast","  Hunter", 2 , 3 , 2    ));
		grandTourn.add(new Minion("Knight of the Wild"," Rare"," Minion"," General","  Druid", 7 , 6 , 6    ));
		grandTourn.add(new Minion("Kodorider"," Epic"," Minion"," General","  Any", 6 , 3 , 5    ));
		grandTourn.add(new Minion("Kvaldir Raider"," Common"," Minion"," General","  Any", 5 , 4 , 4    ));
		grandTourn.add(new Minion("Lance Carrier"," Common"," Minion"," General","  Any", 2 , 1 , 2    ));
		grandTourn.add(new Minion("Light's Champion"," Rare"," Minion"," General","  Any", 3 , 4 , 3    ));
		grandTourn.add(new Spell("Living Roots"," Common"," Spell"," ","  Druid",1," ","  "));
		grandTourn.add(new Spell("Lock and Load"," Epic"," Spell"," ","  Hunter",2," ","  "));
		grandTourn.add(new Minion("Lowly Squire"," Common"," Minion"," General","  Any", 1 , 1 , 2    ));
		grandTourn.add(new Minion("Magnataur Alpha"," Epic"," Minion"," General","  Warrior", 4 , 5 , 3    ));
		grandTourn.add(new Minion("Maiden of the Lake"," Common"," Minion"," General","  Any", 4 , 2 , 6    ));
		grandTourn.add(new Minion("Master Jouster"," Rare"," Minion"," General","  Any", 6 , 5 , 6    ));
		grandTourn.add(new Minion("Master of Ceremonies"," Epic"," Minion"," General","  Any", 3 , 4 , 2    ));
		grandTourn.add(new Minion("Mogor's Champion"," Rare"," Minion"," General","  Any", 6 , 8 , 5    ));
		grandTourn.add(new Minion("Mukla's Champion"," Common"," Minion"," Beast","  Any", 5 , 4 , 3    ));
		grandTourn.add(new Spell("Mulch"," Epic"," Spell"," ","  Druid",3," ","  "));
		grandTourn.add(new Minion("Murloc Knight"," Common"," Minion"," Murloc","  Paladin", 4 , 3 , 4    ));
		grandTourn.add(new Minion("Mysterious Challenger"," Epic"," Minion"," General","  Paladin", 6 , 6 , 6    ));
		grandTourn.add(new Minion("Nexus-Champion Saraad"," Legendary"," Minion"," General","  Any", 5 , 4 , 5    ));
		grandTourn.add(new Minion("North Sea Kraken"," Common"," Minion"," Beast","  Any", 9 , 9 , 7    ));
		grandTourn.add(new Minion("Orgrimmar Aspirant"," Common"," Minion"," General","  Warrior", 3 , 3 , 3    ));
		grandTourn.add(new Minion("Pit Fighter"," Common"," Minion"," General","  Any", 5 , 5 , 6    ));
		grandTourn.add(new Minion("Poisoned Blade"," Epic"," Weapon"," ","  Rogue", 4 , 1 , 3    ));
		grandTourn.add(new Spell("Polymorph: Boar"," Rare"," Spell"," ","  Mage",3," ","  "));
		grandTourn.add(new Spell("Power Word: Glory"," Common"," Spell"," ","  Priest",1," ","  "));
		grandTourn.add(new Spell("Powershot"," Rare"," Spell"," ","  Hunter",3," ","  "));
		grandTourn.add(new Minion("Ram Wrangler"," Rare"," Minion"," General","  Hunter", 5 , 3 , 3    ));
		grandTourn.add(new Minion("Recruiter"," Epic"," Minion"," General","  Any", 5 , 5 , 4    ));
		grandTourn.add(new Minion("Refreshment Vendor"," Common"," Minion"," General","  Any", 4 , 3 , 5    ));
		grandTourn.add(new Minion("Rhonin"," Legendary"," Minion"," General","  Mage", 8 , 7 , 7    ));
		grandTourn.add(new Minion("Saboteur"," Rare"," Minion"," General","  Any", 3 , 4 , 3    ));
		grandTourn.add(new Minion("Savage Combatant"," Rare"," Minion"," Beast","  Druid", 4 , 5 , 4    ));
		grandTourn.add(new Minion("Sea Reaver"," Epic"," Minion"," General","  Warrior", 6 , 6 , 7    ));
		grandTourn.add(new Spell("Seal of Champions"," Common"," Spell"," ","  Paladin",3," ","  "));
		grandTourn.add(new Minion("Shado-Pan Rider"," Common"," Minion"," General","  Rogue", 5 , 3 , 7    ));
		grandTourn.add(new Minion("Shadowfiend"," Epic"," Minion"," General","  Priest", 3 , 3 , 3    ));
		grandTourn.add(new Minion("Shady Dealer"," Rare"," Minion"," General","  Rogue", 3 , 4 , 3    ));
		grandTourn.add(new Minion("Sideshow Spelleater"," Epic"," Minion"," General","  Any", 6 , 6 , 5    ));
		grandTourn.add(new Minion("Silent Knight"," Common"," Minion"," General","  Any", 3 , 2 , 2    ));
		grandTourn.add(new Minion("Silver Hand Regent"," Common"," Minion"," General","  Any", 3 , 3 , 3    ));
		grandTourn.add(new Minion("Skycap'n Kragg"," Legendary"," Minion"," Pirate","  Any", 7 , 4 , 6    ));
		grandTourn.add(new Minion("Sparring Partner"," Rare"," Minion"," General","  Warrior", 2 , 3 , 2    ));
		grandTourn.add(new Minion("Spawn of Shadows"," Rare"," Minion"," General","  Priest", 4 , 5 , 4    ));
		grandTourn.add(new Minion("Spellslinger"," Common"," Minion"," General","  Mage", 3 , 3 , 4    ));
		grandTourn.add(new Minion("Stablemaster"," Epic"," Minion"," General","  Hunter", 3 , 4 , 2    ));
		grandTourn.add(new Minion("The Mistcaller"," Legendary"," Minion"," General","  Shaman", 6 , 4 , 4    ));
		grandTourn.add(new Minion("The Skeleton Knight"," Legendary"," Minion"," General","  Any", 6 , 7 , 4    ));
		grandTourn.add(new Minion("Thunder Bluff Valiant"," Rare"," Minion"," General","  Shaman", 5 , 3 , 6    ));
		grandTourn.add(new Minion("Tiny Knight of Evil"," Rare"," Minion"," Demon","  Warlock", 2 , 3 , 2    ));
		grandTourn.add(new Minion("Totem Golem"," Common"," Minion"," Totem","  Shaman", 2 , 3 , 4    ));
		grandTourn.add(new Minion("Tournament Attendee"," Common"," Minion"," General","  Any", 1 , 2 , 1    ));
		grandTourn.add(new Minion("Tournament Medic"," Common"," Minion"," General","  Any", 4 , 1 , 8    ));
		grandTourn.add(new Minion("Tuskarr Jouster"," Rare"," Minion"," General","  Paladin", 5 , 5 , 5    ));
		grandTourn.add(new Minion("Tuskarr Totemic"," Common"," Minion"," General","  Shaman", 3 , 3 , 2    ));
		grandTourn.add(new Minion("Twilight Guardian"," Epic"," Minion"," Dragon","  Any", 4 , 2 , 6    ));
		grandTourn.add(new Minion("Undercity Valiant"," Common"," Minion"," General","  Rogue", 2 , 3 , 2    ));
		grandTourn.add(new Minion("Varian Wrynn"," Legendary"," Minion"," General","  Warrior", 10 , 7 , 7    ));
		grandTourn.add(new Minion("Void Crusher"," Rare"," Minion"," Demon","  Warlock", 6 , 5 , 4    ));
		grandTourn.add(new Minion("Warhorse Trainer"," Common"," Minion"," General","  Paladin", 3 , 2 , 4    ));
		grandTourn.add(new Minion("Wildwalker"," Common"," Minion"," General","  Druid", 4 , 4 , 4    ));
		grandTourn.add(new Minion("Wilfred Fizzlebang"," Legendary"," Minion"," General","  Warlock", 6 , 4 , 4    ));
		grandTourn.add(new Minion("Wrathguard"," Common"," Minion"," Demon","  Warlock", 2 , 4 , 3    ));
		grandTourn.add(new Minion("Wyrmrest Agent"," Rare"," Minion"," General","  Priest", 2 , 1 , 4    ));

		return grandTourn; 
	}
}
