package cardSets;

import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetRoS {

	public ArrayList<Card> RoSList() {
		ArrayList<Card> RoS= new ArrayList<Card>();
		RoS.add(new Minion("Arcane Servant"," Common"," Minion"," Elemental","  Any", 2 , 2 , 3    ));
		RoS.add(new Minion("Burly Shovelfist"," Common"," Minion"," General","  Any", 9 , 9 , 9    ));
		RoS.add(new Minion("Dalaran Crusader"," Common"," Minion"," General","  Any", 5 , 5 , 4    ));
		RoS.add(new Minion("Dalaran Librarian"," Common"," Minion"," General","  Any", 2 , 2 , 3    ));
		RoS.add(new Minion("Eccentric Scribe"," Common"," Minion"," General","  Any", 6 , 6 , 4    ));
		RoS.add(new Minion("EVIL Cable Rat"," Common"," Minion"," Beast","  Any", 2 , 1 , 1    ));
		RoS.add(new Minion("Faceless Rager"," Common"," Minion"," General","  Any", 3 , 5 , 1    ));
		RoS.add(new Minion("Flight Master"," Common"," Minion"," General","  Any", 3 , 3 , 4    ));
		RoS.add(new Minion("Hench-Clan Hogsteed"," Common"," Minion"," Beast","  Any", 2 , 2 , 1    ));
		RoS.add(new Minion("Hench-Clan Sneak"," Common"," Minion"," General","  Any", 3 , 3 , 3    ));
		RoS.add(new Minion("Heroic Innkeeper"," Common"," Minion"," General","  Any", 8 , 4 , 4    ));
		RoS.add(new Minion("Mana Reservoir"," Common"," Minion"," Elemental","  Any", 2 , 0 , 6    ));
		RoS.add(new Minion("Potion Vendor"," Common"," Minion"," General","  Any", 1 , 1 , 1    ));
		RoS.add(new Minion("Proud Defender"," Common"," Minion"," General","  Any", 4 , 2 , 6    ));
		RoS.add(new Minion("Safeguard"," Common"," Minion"," Mech","  Any", 6 , 4 , 5    ));
		RoS.add(new Minion("Soldier of Fortune"," Common"," Minion"," Elemental","  Any", 4 , 5 , 6    ));
		RoS.add(new Minion("Spellbook Binder"," Common"," Minion"," General","  Any", 2 , 3 , 2    ));
		RoS.add(new Minion("Sunreaver Spy"," Common"," Minion"," General","  Any", 2 , 2 , 3    ));
		RoS.add(new Minion("Toxfin"," Common"," Minion"," Murloc","  Any", 1 , 1 , 2    ));
		RoS.add(new Minion("Traveling Healer"," Common"," Minion"," General","  Any", 4 , 3 , 2    ));
		RoS.add(new Minion("Violet Spellsword"," Common"," Minion"," General","  Any", 4 , 1 , 6    ));
		RoS.add(new Minion("Violet Warden"," Common"," Minion"," General","  Any", 6 , 4 , 7    ));
		RoS.add(new Minion("Acornbearer"," Common"," Minion"," General","  Druid", 1 , 2 , 1    ));
		RoS.add(new Spell("Blessing of the Ancients"," Common"," Spell"," ","  Druid",1," ","  "));
		RoS.add(new Spell("Crystal Power"," Common"," Spell"," ","  Druid",1," ","  "));
		RoS.add(new Spell("Marked Shot"," Common"," Spell"," ","  Hunter",4," ","  "));
		RoS.add(new Spell("Rapid Fire"," Common"," Spell"," ","  Hunter",1," ","  "));
		RoS.add(new Minion("Ursatron"," Common"," Minion"," Mech","  Hunter", 3 , 3 , 3    ));
		RoS.add(new Minion("Magic Dart Frog"," Common"," Minion"," Beast","  Mage", 2 , 1 , 3    ));
		RoS.add(new Minion("Messenger Raven"," Common"," Minion"," Beast","  Mage", 3 , 3 , 2    ));
		RoS.add(new Spell("Ray of Frost"," Common"," Spell"," ","  Mage",1," ","  "));
		RoS.add(new Minion("Bronze Herald"," Common"," Minion"," Dragon","  Paladin", 3 , 3 , 2    ));
		RoS.add(new Spell("Lightforged Blessing"," Common"," Spell"," ","  Paladin",2," ","  "));
		RoS.add(new Spell("Never Surrender!"," Common"," Spell"," ","  Paladin",1," ","  "));
		RoS.add(new Minion("EVIL Conscripter"," Common"," Minion"," General","  Priest", 2 , 2 , 2    ));
		RoS.add(new Minion("Hench-Clan Shadequill"," Common"," Minion"," General","  Priest", 4 , 4 , 7    ));
		RoS.add(new Spell("Unsleeping Soul"," Common"," Spell"," ","  Priest",4," ","  "));
		RoS.add(new Spell("Daring Escape"," Common"," Spell"," ","  Rogue",1," ","  "));
		RoS.add(new Minion("EVIL Miscreant"," Common"," Minion"," General","  Rogue", 3 , 1 , 4    ));
		RoS.add(new Minion("Hench-Clan Burglar"," Common"," Minion"," Pirate","  Rogue", 4 , 4 , 3    ));
		RoS.add(new Spell("Mutate"," Common"," Spell"," ","  Shaman",0," ","  "));
		RoS.add(new Spell("Soul of the Murloc"," Common"," Spell"," ","  Shaman",2," ","  "));
		RoS.add(new Minion("Walking Fountain"," Common"," Minion"," Elemental","  Shaman", 8 , 4 , 8    ));
		RoS.add(new Minion("Aranasi Broodmother"," Common"," Minion"," Demon","  Warlock", 6 , 4 , 6    ));
		RoS.add(new Minion("EVIL Genius"," Common"," Minion"," General","  Warlock", 2 , 2 , 2    ));
		RoS.add(new Spell("Rafaam's Scheme"," Common"," Spell"," ","  Warlock",3," ","  "));
		RoS.add(new Spell("Dr. Boom's Scheme"," Common"," Spell"," ","  Warrior",4," ","  "));
		RoS.add(new Spell("Improve Morale"," Common"," Spell"," ","  Warrior",1," ","  "));
		RoS.add(new Minion("Vicious Scraphound"," Common"," Minion"," Mech","  Warrior", 2 , 2 , 3    ));
		RoS.add(new Minion("Arcane Watcher"," Rare"," Minion"," General","  Any", 3 , 5 , 6    ));
		RoS.add(new Minion("Exotic Mountseller"," Rare"," Minion"," General","  Any", 7 , 5 , 8    ));
		RoS.add(new Minion("Hecklebot"," Rare"," Minion"," Mech","  Any", 4 , 3 , 8    ));
		RoS.add(new Minion("Mad Summoner"," Rare"," Minion"," Demon","  Any", 6 , 4 , 4    ));
		RoS.add(new Minion("Portal Keeper"," Rare"," Minion"," Demon","  Any", 4 , 5 , 2    ));
		RoS.add(new Minion("Recurring Villain"," Rare"," Minion"," General","  Any", 5 , 3 , 6    ));
		RoS.add(new Minion("Spellward Jeweler"," Rare"," Minion"," General","  Any", 3 , 3 , 4    ));
		RoS.add(new Minion("Sunreaver Warmage"," Rare"," Minion"," General","  Any", 5 , 4 , 4    ));
		RoS.add(new Minion("Tunnel Blaster"," Rare"," Minion"," General","  Any", 7 , 3 , 7    ));
		RoS.add(new Minion("Underbelly Ooze"," Rare"," Minion"," General","  Any", 7 , 3 , 5    ));
		RoS.add(new Spell("Dreamway Guardians"," Rare"," Spell"," ","  Druid",2," ","  "));
		RoS.add(new Minion("Lifeweaver"," Rare"," Minion"," General","  Druid", 3 , 2 , 5    ));
		RoS.add(new Spell("The Forest's Aid"," Rare"," Spell"," ","  Druid",8," ","  "));
		RoS.add(new Spell("Hunting Party"," Rare"," Spell"," ","  Hunter",5," ","  "));
		RoS.add(new Minion("Shimmerfly"," Rare"," Minion"," Beast","  Hunter", 1 , 1 , 1    ));
		RoS.add(new Spell("Unleash the Beast"," Rare"," Spell"," ","  Hunter",6," ","  "));
		RoS.add(new Spell("Conjurer's Calling"," Rare"," Spell"," ","  Mage",4," ","  "));
		RoS.add(new Minion("Kirin Tor Tricaster"," Rare"," Minion"," General","  Mage", 4 , 3 , 3    ));
		RoS.add(new Spell("Magic Trick"," Rare"," Spell"," ","  Mage",1," ","  "));
		RoS.add(new Spell("Call to Adventure"," Rare"," Spell"," ","  Paladin",3," ","  "));
		RoS.add(new Spell("Desperate Measures"," Rare"," Spell"," ","  Paladin",1," ","  "));
		RoS.add(new Minion("Mysterious Blade"," Rare"," Weapon"," ","  Paladin", 2 , 2 , 2    ));
		RoS.add(new Minion("Convincing Infiltrator"," Rare"," Minion"," General","  Priest", 5 , 2 , 6    ));
		RoS.add(new Spell("Forbidden Words"," Rare"," Spell"," ","  Priest",0," ","  "));
		RoS.add(new Spell("Mass Resurrection"," Rare"," Spell"," ","  Priest",9," ","  "));
		RoS.add(new Spell("Togwaggle's Scheme"," Rare"," Spell"," ","  Rogue",1," ","  "));
		RoS.add(new Minion("Underbelly Fence"," Rare"," Minion"," General","  Rogue", 2 , 2 , 3    ));
		RoS.add(new Spell("Vendetta"," Rare"," Spell"," ","  Rogue",4," ","  "));
		RoS.add(new Spell("Hagatha's Scheme"," Rare"," Spell"," ","  Shaman",5," ","  "));
		RoS.add(new Minion("Sludge Slurper"," Rare"," Minion"," Murloc","  Shaman", 1 , 1 , 1    ));
		RoS.add(new Minion("Underbelly Angler"," Rare"," Minion"," Murloc","  Shaman", 2 , 2 , 3    ));
		RoS.add(new Minion("Eager Underling"," Rare"," Minion"," General","  Warlock", 4 , 2 , 2    ));
		RoS.add(new Spell("Impferno"," Rare"," Spell"," ","  Warlock",3," ","  "));
		RoS.add(new Spell("Plot Twist"," Rare"," Spell"," ","  Warlock",2," ","  "));
		RoS.add(new Minion("Clockwork Goblin"," Rare"," Minion"," Mech","  Warrior", 3 , 3 , 3    ));
		RoS.add(new Spell("Dimensional Ripper"," Rare"," Spell"," ","  Warrior",10," ","  "));
		RoS.add(new Spell("Sweeping Strikes"," Rare"," Spell"," ","  Warrior",2," ","  "));
		RoS.add(new Minion("Azerite Elemental"," Epic"," Minion"," Elemental","  Any", 5 , 2 , 7    ));
		RoS.add(new Minion("Batterhead"," Epic"," Minion"," General","  Any", 8 , 3 , 12    ));
		RoS.add(new Minion("Big Bad Archmage"," Epic"," Minion"," General","  Any", 10 , 6 , 6    ));
		RoS.add(new Minion("Hench-Clan Hag"," Epic"," Minion"," General","  Any", 4 , 3 , 3    ));
		RoS.add(new Minion("Magic Carpet"," Epic"," Minion"," General","  Any", 3 , 1 , 6    ));
		RoS.add(new Minion("Portal Overfiend"," Epic"," Minion"," Demon","  Any", 6 , 5 , 6    ));
		RoS.add(new Minion("Unseen Saboteur"," Epic"," Minion"," General","  Any", 6 , 5 , 6    ));
		RoS.add(new Minion("Whirlwind Tempest"," Epic"," Minion"," Elemental","  Any", 8 , 6 , 6    ));
		RoS.add(new Minion("Crystal Stag"," Epic"," Minion"," Beast","  Druid", 5 , 4 , 4    ));
		RoS.add(new Spell("Crystalsong Portal"," Epic"," Spell"," ","  Druid",2," ","  "));
		RoS.add(new Minion("Arcane Fletcher"," Epic"," Minion"," General","  Hunter", 4 , 3 , 3    ));
		RoS.add(new Spell("Nine Lives"," Epic"," Spell"," ","  Hunter",3," ","  "));
		RoS.add(new Minion("Mana Cyclone"," Epic"," Minion"," Elemental","  Mage", 2 , 2 , 2    ));
		RoS.add(new Spell("Power of Creation"," Epic"," Spell"," ","  Mage",8," ","  "));
		RoS.add(new Minion("Dragon Speaker"," Epic"," Minion"," General","  Paladin", 5 , 3 , 5    ));
		RoS.add(new Spell("Duel!"," Epic"," Spell"," ","  Paladin",5," ","  "));
		RoS.add(new Spell("Lazul's Scheme"," Epic"," Spell"," ","  Priest",0," ","  "));
		RoS.add(new Minion("Shadowy Figure"," Epic"," Minion"," General","  Priest", 2 , 2 , 2    ));
		RoS.add(new Spell("Unidentified Contract"," Epic"," Spell"," ","  Rogue",6," ","  "));
		RoS.add(new Minion("Waggle Pick"," Epic"," Weapon"," ","  Rogue", 4 , 4 , 2    ));
		RoS.add(new Minion("Muckmorpher"," Epic"," Minion"," General","  Shaman", 5 , 4 , 4    ));
		RoS.add(new Spell("Witch's Brew"," Epic"," Spell"," ","  Shaman",2," ","  "));
		RoS.add(new Spell("Darkest Hour"," Epic"," Spell"," ","  Warlock",6," ","  "));
		RoS.add(new Minion("Jumbo Imp"," Epic"," Minion"," Demon","  Warlock", 10 , 8 , 8    ));
		RoS.add(new Minion("Omega Devastator"," Epic"," Minion"," Mech","  Warrior", 4 , 4 , 5    ));
		RoS.add(new Minion("Wrenchcalibur"," Epic"," Weapon"," ","  Warrior", 4 , 3 , 2    ));
		RoS.add(new Minion("Archivist Elysiana"," Legendary"," Minion"," General","  Any", 9 , 7 , 7    ));
		RoS.add(new Minion("Archmage Vargoth"," Legendary"," Minion"," General","  Any", 4 , 2 , 6    ));
		RoS.add(new Minion("Barista Lynchen"," Legendary"," Minion"," General","  Any", 5 , 4 , 5    ));
		RoS.add(new Minion("Chef Nomi"," Legendary"," Minion"," General","  Any", 7 , 6 , 6    ));
		RoS.add(new Minion("Jepetto Joybuzz"," Legendary"," Minion"," General","  Any", 8 , 6 , 6    ));
		RoS.add(new Minion("Zayle, Shadow Cloak"," Legendary"," Minion"," General","  Any", 2 , 3 , 2    ));
		RoS.add(new Minion("Keeper Stalladris"," Legendary"," Minion"," General","  Druid", 2 , 2 , 3    ));
		RoS.add(new Minion("Lucentbark"," Legendary"," Minion"," General","  Druid", 8 , 4 , 8    ));
		RoS.add(new Minion("Oblivitron"," Legendary"," Minion"," Mech","  Hunter", 6 , 3 , 4    ));
		RoS.add(new Minion("Vereesa Windrunner"," Legendary"," Minion"," General","  Hunter", 7 , 5 , 6    ));
		RoS.add(new Minion("Kalecgos"," Legendary"," Minion"," Dragon","  Mage", 10 , 4 , 12    ));
		RoS.add(new Minion("Khadgar"," Legendary"," Minion"," General","  Mage", 2 , 2 , 2    ));
		RoS.add(new Minion("Commander Rhyssa"," Legendary"," Minion"," General","  Paladin", 3 , 4 , 3    ));
		RoS.add(new Minion("Nozari"," Legendary"," Minion"," Dragon","  Paladin", 10 , 4 , 12    ));
		RoS.add(new Minion("Catrina Muerte"," Legendary"," Minion"," General","  Priest", 8 , 6 , 8    ));
		RoS.add(new Minion("Madame Lazul"," Legendary"," Minion"," General","  Priest", 3 , 3 , 2    ));
		RoS.add(new Minion("Heistbaron Togwaggle"," Legendary"," Minion"," General","  Rogue", 6 , 5 , 5    ));
		RoS.add(new Minion("Tak Nozwhisker"," Legendary"," Minion"," General","  Rogue", 7 , 6 , 6    ));
		RoS.add(new Minion("Scargil"," Legendary"," Minion"," Murloc","  Shaman", 4 , 4 , 4    ));
		RoS.add(new Minion("Swampqueen Hagatha"," Legendary"," Minion"," General","  Shaman", 7 , 5 , 5    ));
		RoS.add(new Minion("Arch-Villain Rafaam"," Legendary"," Minion"," General","  Warlock", 7 , 7 , 8    ));
 		RoS.add(new Minion("Fel Lord Betrug"," Legendary"," Minion"," Demon","  Warlock", 8 , 5 , 7    ));
		RoS.add(new Minion("Blastmaster Boom"," Legendary"," Minion"," General","  Warrior", 7 , 7 , 7    ));
		RoS.add(new Minion("The Boom Reaver"," Legendary"," Minion"," Mech","  Warrior", 10 , 7 , 9    ));
		return RoS;
	}
	

}
