package cardSets;
import java.util.ArrayList;

import cardFunctions.Card;
import cardFunctions.Minion;
import cardFunctions.Spell;

public class CardSetBasic {

	public ArrayList<Card> basicList() {
		ArrayList<Card> basic = new ArrayList<Card>();
		
		basic.add(new Spell("Ancestral Healing"," Common"," Spell"," ","  Shaman",0," ","  "));
		basic.add(new Spell("Backstab"," Common"," Spell"," ","  Rogue",0," ","  "));
		basic.add(new Spell("Innervate"," Common"," Spell"," ","  Druid",0," ","  "));
		basic.add(new Spell("Moonfire"," Common"," Spell"," ","  Druid",0," ","  "));
		basic.add(new Spell("Sacrificial Pact"," Common"," Spell"," ","  Warlock",0," ","  "));
		basic.add(new Spell("Totemic Might"," Common"," Spell"," ","  Shaman",0," ","  "));
		basic.add(new Spell("Arcane Missiles"," Common"," Spell"," ","  Mage",1," ","  "));
		basic.add(new Spell("Arcane Shot"," Common"," Spell"," ","  Hunter",1," ","  "));
		basic.add(new Spell("Blessing of Might"," Common"," Spell"," ","  Paladin",1," ","  "));
		basic.add(new Spell("Charge"," Common"," Spell"," ","  Warrior",1," ","  "));
		basic.add(new Spell("Claw"," Common"," Spell"," ","  Druid",1," ","  "));
		basic.add(new Spell("Corruption"," Common"," Spell"," ","  Warlock",1," ","  "));
		basic.add(new Spell("Deadly Poison"," Common"," Spell"," ","  Rogue",1," ","  "));
		basic.add(new Minion("Elven Archer"," Common"," Minion"," General","  Any", 1 , 1 , 1    ));
		basic.add(new Spell("Frost Shock"," Common"," Spell"," ","  Shaman",1," ","  "));
		basic.add(new Minion("Goldshire Footman"," Common"," Minion"," General","  Any", 1 , 1 , 2    ));
		basic.add(new Minion("Grimscale Oracle"," Common"," Minion"," Murloc","  Any", 1 , 1 , 1    ));
		basic.add(new Spell("Hand of Protection"," Common"," Spell"," ","  Paladin",1," ","  "));
		basic.add(new Spell("Holy Smite"," Common"," Spell"," ","  Priest",1," ","  "));
		basic.add(new Spell("Humility"," Common"," Spell"," ","  Paladin",1," ","  "));
		basic.add(new Minion("Light's Justice"," Common"," Weapon"," ","  Paladin", 1 , 1 , 4    ));
		basic.add(new Spell("Mind Vision"," Common"," Spell"," ","  Priest",1," ","  "));
		basic.add(new Spell("Mirror Image"," Common"," Spell"," ","  Mage",1," ","  "));
		basic.add(new Spell("Mortal Coil"," Common"," Spell"," ","  Warlock",1," ","  "));
		basic.add(new Minion("Murloc Raider"," Common"," Minion"," Murloc","  Any", 1 , 2 , 1    ));
		basic.add(new Minion("Northshire Cleric"," Common"," Minion"," General","  Priest", 1 , 1 , 3    ));
		basic.add(new Spell("Power Word: Shield"," Common"," Spell"," ","  Priest",1," ","  "));
		basic.add(new Spell("Radiance"," Common"," Spell"," ","  Priest",1," ","  "));
		basic.add(new Spell("Sinister Strike"," Common"," Spell"," ","  Rogue",1," ","  "));
		basic.add(new Spell("Soulfire"," Common"," Spell"," ","  Warlock",1," ","  "));
		basic.add(new Minion("Stonetusk Boar"," Common"," Minion"," Beast","  Any", 1 , 1 , 1    ));
		basic.add(new Minion("Timber Wolf"," Common"," Minion"," Beast","  Hunter", 1 , 1 , 1    ));
		basic.add(new Spell("Tracking"," Common"," Spell"," ","  Hunter",1," ","  "));
		basic.add(new Minion("Voidwalker"," Common"," Minion"," Demon","  Warlock", 1 , 1 , 3    ));
		basic.add(new Minion("Voodoo Doctor"," Common"," Minion"," General","  Any", 1 , 2 , 1    ));
		basic.add(new Spell("Whirlwind"," Common"," Spell"," ","  Warrior",1," ","  "));
		basic.add(new Minion("Acidic Swamp Ooze"," Common"," Minion"," General","  Any", 2 , 3 , 2    ));
		basic.add(new Spell("Arcane Explosion"," Common"," Spell"," ","  Mage",2," ","  "));
		basic.add(new Minion("Bloodfen Raptor"," Common"," Minion"," Beast","  Any", 2 , 3 , 2    ));
		basic.add(new Minion("Bluegill Warrior"," Common"," Minion"," Murloc","  Any", 2 , 2 , 1    ));
		basic.add(new Spell("Cleave"," Common"," Spell"," ","  Warrior",2," ","  "));
		basic.add(new Spell("Divine Spirit"," Common"," Spell"," ","  Priest",2," ","  "));
		basic.add(new Spell("Execute"," Common"," Spell"," ","  Warrior",2," ","  "));
		basic.add(new Minion("Felstalker"," Common"," Minion"," Demon","  Warlock", 2 , 4 , 3    ));
		basic.add(new Spell("Frostbolt"," Common"," Spell"," ","  Mage",2," ","  "));
		basic.add(new Minion("Frostwolf Grunt"," Common"," Minion"," General","  Any", 2 , 2 , 2    ));
		basic.add(new Spell("Heroic Strike"," Common"," Spell"," ","  Warrior",2," ","  "));
		basic.add(new Spell("Holy Light"," Common"," Spell"," ","  Paladin",2," ","  "));
		basic.add(new Spell("Hunter's Mark"," Common"," Spell"," ","  Hunter",2," ","  "));
		basic.add(new Minion("Kobold Geomancer"," Common"," Minion"," General","  Any", 2 , 2 , 2    ));
		basic.add(new Spell("Mark of the Wild"," Common"," Spell"," ","  Druid",2," ","  "));
		basic.add(new Minion("Murloc Tidehunter"," Common"," Minion"," Murloc","  Any", 2 , 2 , 1    ));
		basic.add(new Minion("Novice Engineer"," Common"," Minion"," General","  Any", 2 , 1 , 1    ));
		basic.add(new Minion("River Crocolisk"," Common"," Minion"," Beast","  Any", 2 , 2 , 3    ));
		basic.add(new Spell("Rockbiter Weapon"," Common"," Spell"," ","  Shaman",2," ","  "));
		basic.add(new Spell("Sap"," Common"," Spell"," ","  Rogue",2," ","  "));
		basic.add(new Spell("Shadow Word: Pain"," Common"," Spell"," ","  Priest",2," ","  "));
		basic.add(new Spell("Shiv"," Common"," Spell"," ","  Rogue",2," ","  "));
		basic.add(new Spell("Windfury"," Common"," Spell"," ","  Shaman",2," ","  "));
		basic.add(new Spell("Animal Companion"," Common"," Spell"," ","  Hunter",3," ","  "));
		basic.add(new Spell("Arcane Intellect"," Common"," Spell"," ","  Mage",3," ","  "));
		basic.add(new Minion("Dalaran Mage"," Common"," Minion"," General","  Any", 3 , 1 , 4    ));
		basic.add(new Spell("Drain Life"," Common"," Spell"," ","  Warlock",3," ","  "));
		basic.add(new Spell("Fan of Knives"," Common"," Spell"," ","  Rogue",3," ","  "));
		basic.add(new Minion("Fiery War Axe"," Common"," Weapon"," ","  Warrior", 3 , 3 , 2    ));
		basic.add(new Minion("Flametongue Totem"," Common"," Minion"," Totem","  Shaman", 3 , 0 , 3    ));
		basic.add(new Spell("Frost Nova"," Common"," Spell"," ","  Mage",3," ","  "));
		basic.add(new Spell("Healing Touch"," Common"," Spell"," ","  Druid",3," ","  "));
		basic.add(new Minion("Ironforge Rifleman"," Common"," Minion"," General","  Any", 3 , 2 , 2    ));
		basic.add(new Minion("Ironfur Grizzly"," Common"," Minion"," Beast","  Any", 3 , 3 , 3    ));
		basic.add(new Spell("Kill Command"," Common"," Spell"," ","  Hunter",3," ","  "));
		basic.add(new Minion("Magma Rager"," Common"," Minion"," Elemental","  Any", 3 , 5 , 1    ));
		basic.add(new Minion("Raid Leader"," Common"," Minion"," General","  Any", 3 , 2 , 2    ));
		basic.add(new Minion("Razorfen Hunter"," Common"," Minion"," General","  Any", 3 , 2 , 3    ));
		basic.add(new Spell("Savage Roar"," Common"," Spell"," ","  Druid",3," ","  "));
		basic.add(new Spell("Shadow Bolt"," Common"," Spell"," ","  Warlock",3," ","  "));
		basic.add(new Spell("Shadow Word: Death"," Common"," Spell"," ","  Priest",3," ","  "));
		basic.add(new Minion("Shattered Sun Cleric"," Common"," Minion"," General","  Any", 3 , 3 , 2    ));
		basic.add(new Spell("Shield Block"," Common"," Spell"," ","  Warrior",3," ","  "));
		basic.add(new Minion("Silverback Patriarch"," Common"," Minion"," Beast","  Any", 3 , 1 , 4    ));
		basic.add(new Minion("Warsong Commander"," Common"," Minion"," General","  Warrior", 3 , 2 , 3    ));
		basic.add(new Spell("Wild Growth"," Common"," Spell"," ","  Druid",3," ","  "));
		basic.add(new Minion("Wolfrider"," Common"," Minion"," General","  Any", 3 , 3 , 1    ));
		basic.add(new Spell("Blessing of Kings"," Common"," Spell"," ","  Paladin",4," ","  "));
		basic.add(new Minion("Chillwind Yeti"," Common"," Minion"," General","  Any", 4 , 4 , 5    ));
		basic.add(new Spell("Consecration"," Common"," Spell"," ","  Paladin",4," ","  "));
		basic.add(new Minion("Dragonling Mechanic"," Common"," Minion"," General","  Any", 4 , 2 , 4    ));
		basic.add(new Spell("Fireball"," Common"," Spell"," ","  Mage",4," ","  "));
		basic.add(new Minion("Gnomish Inventor"," Common"," Minion"," General","  Any", 4 , 2 , 4    ));
		basic.add(new Spell("Hammer of Wrath"," Common"," Spell"," ","  Paladin",4," ","  "));
		basic.add(new Spell("Hellfire"," Common"," Spell"," ","  Warlock",4," ","  "));
		basic.add(new Spell("Hex"," Common"," Spell"," ","  Shaman",4," ","  "));
		basic.add(new Minion("Houndmaster"," Common"," Minion"," General","  Hunter", 4 , 4 , 3    ));
		basic.add(new Minion("Kor'kron Elite"," Common"," Minion"," General","  Warrior", 4 , 4 , 3    ));
		basic.add(new Spell("Multi-Shot"," Common"," Spell"," ","  Hunter",4," ","  "));
		basic.add(new Minion("Oasis Snapjaw"," Common"," Minion"," Beast","  Any", 4 , 2 , 7    ));
		basic.add(new Minion("Ogre Magi"," Common"," Minion"," General","  Any", 4 , 4 , 4    ));
		basic.add(new Minion("Plaguebringer"," Common"," Minion"," General","  Rogue", 4 , 3 , 3    ));
		basic.add(new Spell("Polymorph"," Common"," Spell"," ","  Mage",4," ","  "));
		basic.add(new Minion("Sen'jin Shieldmasta"," Common"," Minion"," General","  Any", 4 , 3 , 5    ));
		basic.add(new Minion("Stormwind Knight"," Common"," Minion"," General","  Any", 4 , 2 , 5    ));
		basic.add(new Spell("Swipe"," Common"," Spell"," ","  Druid",4," ","  "));
		basic.add(new Minion("Truesilver Champion"," Common"," Weapon"," ","  Paladin", 4 , 4 , 2    ));
		basic.add(new Minion("Water Elemental"," Common"," Minion"," Elemental","  Mage", 4 , 3 , 6    ));
		basic.add(new Minion("Windspeaker"," Common"," Minion"," General","  Shaman", 4 , 3 , 3    ));
		basic.add(new Minion("Arcanite Reaper"," Common"," Weapon"," ","  Warrior", 5 , 5 , 2    ));
		basic.add(new Minion("Assassin's Blade"," Common"," Weapon"," ","  Rogue", 5 , 3 , 4    ));
		basic.add(new Spell("Assassinate"," Common"," Spell"," ","  Rogue",5," ","  "));
		basic.add(new Spell("Bloodlust"," Common"," Spell"," ","  Shaman",5," ","  "));
		basic.add(new Minion("Booty Bay Bodyguard"," Common"," Minion"," General","  Any", 5 , 5 , 4    ));
		basic.add(new Minion("Darkscale Healer"," Common"," Minion"," General","  Any", 5 , 4 , 5    ));
		basic.add(new Minion("Frostwolf Warlord"," Common"," Minion"," General","  Any", 5 , 4 , 4    ));
		basic.add(new Minion("Gurubashi Berserker"," Common"," Minion"," General","  Any", 5 , 2 , 7    ));
		basic.add(new Spell("Holy Nova"," Common"," Spell"," ","  Priest",5," ","  "));
		basic.add(new Minion("Nightblade"," Common"," Minion"," General","  Any", 5 , 4 , 4    ));
		basic.add(new Minion("Starving Buzzard"," Common"," Minion"," Beast","  Hunter", 5 , 3 , 2    ));
		basic.add(new Minion("Stormpike Commando"," Common"," Minion"," General","  Any", 5 , 4 , 2    ));
		basic.add(new Minion("Tundra Rhino"," Common"," Minion"," Beast","  Hunter", 5 , 2 , 5    ));
		basic.add(new Minion("Archmage"," Common"," Minion"," General","  Any", 6 , 4 , 7    ));
		basic.add(new Minion("Boulderfist Ogre"," Common"," Minion"," General","  Any", 6 , 6 , 7    ));
		basic.add(new Minion("Dread Infernal"," Common"," Minion"," Demon","  Warlock", 6 , 6 , 6    ));
		basic.add(new Minion("Fire Elemental"," Common"," Minion"," Elemental","  Shaman", 6 , 6 , 5    ));
		basic.add(new Minion("Lord of the Arena"," Common"," Minion"," General","  Any", 6 , 6 , 5    ));
		basic.add(new Minion("Reckless Rocketeer"," Common"," Minion"," General","  Any", 6 , 5 , 2    ));
		basic.add(new Spell("Starfire"," Common"," Spell"," ","  Druid",6," ","  "));
		basic.add(new Minion("Core Hound"," Common"," Minion"," Beast","  Any", 7 , 9 , 5    ));
		basic.add(new Spell("Flamestrike"," Common"," Spell"," ","  Mage",7," ","  "));
		basic.add(new Minion("Guardian of Kings"," Common"," Minion"," General","  Paladin", 7 , 5 , 6    ));
		basic.add(new Spell("Sprint"," Common"," Spell"," ","  Rogue",7," ","  "));
		basic.add(new Minion("Stormwind Champion"," Common"," Minion"," General","  Any", 7 , 6 , 6    ));
		basic.add(new Minion("War Golem"," Common"," Minion"," General","  Any", 7 , 7 , 7    ));
		basic.add(new Minion("Ironbark Protector"," Common"," Minion"," General","  Druid", 8 , 8 , 8    ));
		basic.add(new Spell("Mind Control"," Common"," Spell"," ","  Priest",10," ","  "));

		return basic;
	}

}
